#! /usr/bin/perl -w
use strict;

# Update the module include path
BEGIN
{
    my $Dir = $0;
    if ( $Dir =~ /(.*)\/.*/ )
    {
	push @INC, "$1";
    }
}
use HawkeyePublish;
use HawkeyeLib;

# Prototypes
sub Init( );
sub RunIt( );

# Setup the hawkeye stuff
my $Hawkeye;
my $Hash;
my @Params = "";
my $CmdLine = join( " ", $0, @ARGV );

# Do it
Init();
RunIt();

sub Init()
{
    HawkeyeLib::DoConfig( );

    $Hawkeye = HawkeyePublish->new;
    $Hawkeye->Quiet( 1 );
    $Hawkeye->AutoIndexSet( 1 );

    # Read the config info..
    $Params[0] = HawkeyeLib::ReadConfig( "_Param0", "true" );
    $Params[1] = HawkeyeLib::ReadConfig( "_Param1", "xyzzy" );
    $Params[2] = HawkeyeLib::ReadConfig( "_Param2", 1 );
    $Params[3] = HawkeyeLib::ReadConfig( "_Param3", "/bin/echo");
    $Params[4] = HawkeyeLib::ReadConfig( "_Param4", 0 );

    # Finally, parse the command line...
    foreach my $Arg ( @ARGV )
    {
	# Cluster on/off
	if ( $Arg =~ /-param(\d)=(.*)/ )
	{
	    $Params[$1] = $2;
	}
	else
	{
	    print STDERR "Unknown option '$Arg'\n";
	    print STDERR "Usage: test [name [options]]\n";
	    print STDERR
		"  [name]         \tModules logical name\n" .
		"  [-paramN=X]    \tSet parameter N to X\n" ;
	    exit 1;
	}
    }
}

# Do the real work here...
sub RunIt()
{

    print STDERR "Test module message to stderr\n";

    # Start things off
    $Hash = HawkeyeHash->new( \$Hawkeye, "" );

    $Hash->Add( "CmdLine", "s", $CmdLine );
    $Hash->Add( "ModuleName", "s", HawkeyeLib::GetModuleName() );
    foreach my $Env ( keys %ENV )
    {
	$Hash->AddNew( "Env_" . $Env, HawkeyePublish::TypeAuto, $ENV{$Env} );
    }

    foreach my $Num ( 0 .. $#Params )
    {
	$Hash->AddNew( "Param$Num", HawkeyePublish::TypeAuto, $Params[$Num] );
    }

    # Simle test values
    $Hash->AddNew( "zero", HawkeyePublish::TypeNumber, "0" );
    $Hash->AddNew( "one", HawkeyePublish::TypeNumber, "1" );
    $Hash->AddNew( "True", HawkeyePublish::TypeBool, "True" );
    $Hash->AddNew( "False", HawkeyePublish::TypeBool, "False" );
    $Hash->AddNew( "string", HawkeyePublish::TypeString, "string #1" );
    $Hash->AddNew( "string2", HawkeyePublish::TypeString, "string #2" );
    $Hash->AddNew( "pi", HawkeyePublish::TypeAuto, "3.1415926" );
    $Hash->AddNew( "IP", HawkeyePublish::TypeAuto, "192.168.1.1" );
    $Hash->AddNew( "three", HawkeyePublish::TypeAuto, "3" );

    # Ok, summary is done...
    $Hash->Store( );
    $Hawkeye->Publish( );

    print STDERR "Test module done\n";
}
