
#include "CondorSubmit.h"
#include "util.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <iostream.h>

// Required for linking with condor libs
extern "C" int SetSyscalls() { return 0; }

static const int MAX_CMD_LENGTH = 200;

static char ErrorBuffer[MAX_CMD_LENGTH];

// CondorSubmit returns 0 on success, non-zero on failure

int CondorSubmit(const char *cmdfile, char *&errorString,
		 int &cluster, int &proc, int &subproc) {
    FILE *fp;
    char *command;
    char buffer[MAX_CMD_LENGTH];
    int status;
    char *executable;
    
    // the '-p' parameter to condor_submit will now cause condor_submit
    // to pause ~4 seconds after a successfull submit.  this prevents
    // the race condition of condor_submit finishing before dagman
    // does a pclose, which at least on SGI IRIX causes a nasty 'Broken Pipe'
    // [j] - took this out on Todd's advice ....
    
    //    executable = "condor_submit -p";
    executable = "condor_submit";


    // 'subproc' is not used in newer versions of condor
    // Version 6 doesnt use 'proc' either.
    // we set this to zero for now

    cluster = 0;
    proc = 0;
    subproc = 0;


    errorString = ErrorBuffer;
    
    command = new char[strlen(executable) + strlen(cmdfile) + 10];
    if (command == NULL) {
      strcpy(ErrorBuffer, "new() failed");
      return 1;
    }
    sprintf(command, "%s %s 2>&1", executable, cmdfile);

    fp = popen(command, "r");
    if (fp == NULL) {
      strcpy(ErrorBuffer, "popen() failed");
      return 1;
    }
    
#ifdef DEBUG
    // [j] NEED TO CHANGE THIS! NOT STABLE!
    // [j] right now we parse condor's return message for 
    // [j] condor id

    if (getline(fp, buffer, MAX_CMD_LENGTH) <= 0) {
      pclose(fp);
      strcpy(ErrorBuffer, "No output generated by condor_submit");
      return 1;
    }

    while ( (strstr(buffer, "cluster")) == NULL ) {
      getline(fp, buffer, MAX_CMD_LENGTH);
      cout << buffer << endl;
    }
#endif

    status = pclose(fp);

#ifdef DEBUG

    printf("%s exited with status %d\n", executable, status);

    // read values into cluster and proc
    // This is not necessary and can be deleted
    // -- used only to print out a DEBUG message

      /*
	This is for version 5
	status = sscanf(buffer, "Proc %d.%d", &cluster, &proc);
      */
    
    status = sscanf(buffer, "1 job(s) submitted to cluster %d", &cluster);

    cout << "CONDOR_SUBMIT -> Proc " << cluster << "." << proc << endl;
#endif

    /*    
	  if (status != 2) {
	//
	// If the word "ERROR" appears in the output, assume that
	// the output is an error message that needs to be returned
	// to the caller
	//
	if (strstr(buffer, "ERROR") || strstr(buffer, "Error") ||
	    strstr(buffer, "error")) {
	    strcpy(ErrorBuffer, buffer);
	    return 1;
	}
	// Truncate error string to 40 characters
	buffer[40] = '\0';
	// If the word "ERROR" was not in the output line, then I
	// don't know how to interpret the output line. So just copy
	// 40 characters into the error buffer
	sprintf(ErrorBuffer,
		"Could not parse condor_submit output: %s", buffer);
	return 1;
    }
    */
    
    return 0;

}
