#!/bin/bash

./rst-cleanup.py ../../overview/index.rst ../../overview/index.rst
./rst-cleanup.py ../../overview/high-throughput-computing-requirements.rst ../../overview/high-throughput-computing-requirements.rst
./rst-cleanup.py ../../overview/htcondors-power.rst ../../overview/htcondors-power.rst
./rst-cleanup.py ../../overview/exceptional-features.rst ../../overview/exceptional-features.rst
./rst-cleanup.py ../../overview/current-limitations.rst ../../overview/current-limitations.rst
./rst-cleanup.py ../../overview/availability.rst ../../overview/availability.rst
./rst-cleanup.py ../../overview/contributions-and-acknowledgments.rst ../../overview/contributions-and-acknowledgments.rst
./rst-cleanup.py ../../overview/contact-information.rst ../../overview/contact-information.rst
./rst-cleanup.py ../../overview/privacy-notice.rst ../../overview/privacy-notice.rst
./rst-cleanup.py ../../users-manual/index.rst ../../users-manual/index.rst
./rst-cleanup.py ../../users-manual/welcome-to-htcondor.rst ../../users-manual/welcome-to-htcondor.rst
./rst-cleanup.py ../../users-manual/introduction-users-manual.rst ../../users-manual/introduction-users-manual.rst
./rst-cleanup.py ../../users-manual/matchmaking-with-classads.rst ../../users-manual/matchmaking-with-classads.rst
./rst-cleanup.py ../../users-manual/running-a-job-steps.rst ../../users-manual/running-a-job-steps.rst
./rst-cleanup.py ../../users-manual/submitting-a-job.rst ../../users-manual/submitting-a-job.rst
./rst-cleanup.py ../../users-manual/managing-a-job.rst ../../users-manual/managing-a-job.rst
./rst-cleanup.py ../../users-manual/priorities-and-preemption.rst ../../users-manual/priorities-and-preemption.rst
./rst-cleanup.py ../../users-manual/java-applications.rst ../../users-manual/java-applications.rst
./rst-cleanup.py ../../users-manual/parallel-applications.rst ../../users-manual/parallel-applications.rst
./rst-cleanup.py ../../users-manual/dagman-applications.rst ../../users-manual/dagman-applications.rst
./rst-cleanup.py ../../users-manual/virtual-machine-applications.rst ../../users-manual/virtual-machine-applications.rst
./rst-cleanup.py ../../users-manual/docker-universe-applications.rst ../../users-manual/docker-universe-applications.rst
./rst-cleanup.py ../../users-manual/time-scheduling-for-job-execution.rst ../../users-manual/time-scheduling-for-job-execution.rst
./rst-cleanup.py ../../users-manual/special-environment-considerations.rst ../../users-manual/special-environment-considerations.rst
./rst-cleanup.py ../../users-manual/potential-problems.rst ../../users-manual/potential-problems.rst
./rst-cleanup.py ../../admin-manual/index.rst ../../admin-manual/index.rst
./rst-cleanup.py ../../admin-manual/introduction-admin-manual.rst ../../admin-manual/introduction-admin-manual.rst
./rst-cleanup.py ../../admin-manual/installation-startup-shutdown-reconfiguration.rst ../../admin-manual/installation-startup-shutdown-reconfiguration.rst
./rst-cleanup.py ../../admin-manual/introduction-to-configuration.rst ../../admin-manual/introduction-to-configuration.rst
./rst-cleanup.py ../../admin-manual/configuration-templates.rst ../../admin-manual/configuration-templates.rst
./rst-cleanup.py ../../admin-manual/configuration-macros.rst ../../admin-manual/configuration-macros.rst
./rst-cleanup.py ../../admin-manual/user-priorities-negotiation.rst ../../admin-manual/user-priorities-negotiation.rst
./rst-cleanup.py ../../admin-manual/policy-configuration.rst ../../admin-manual/policy-configuration.rst
./rst-cleanup.py ../../admin-manual/security.rst ../../admin-manual/security.rst
./rst-cleanup.py ../../admin-manual/networking.rst ../../admin-manual/networking.rst
./rst-cleanup.py ../../admin-manual/checkpoint-server.rst ../../admin-manual/checkpoint-server.rst
./rst-cleanup.py ../../admin-manual/daemoncore.rst ../../admin-manual/daemoncore.rst
./rst-cleanup.py ../../admin-manual/monitoring.rst ../../admin-manual/monitoring.rst
./rst-cleanup.py ../../admin-manual/high-availability.rst ../../admin-manual/high-availability.rst
./rst-cleanup.py ../../admin-manual/setting-up-special-environments.rst ../../admin-manual/setting-up-special-environments.rst
./rst-cleanup.py ../../admin-manual/java-support-installation.rst ../../admin-manual/java-support-installation.rst
./rst-cleanup.py ../../admin-manual/setting-up-vm-docker-universes.rst ../../admin-manual/setting-up-vm-docker-universes.rst
./rst-cleanup.py ../../admin-manual/singularity-support.rst ../../admin-manual/singularity-support.rst
./rst-cleanup.py ../../admin-manual/power-management.rst ../../admin-manual/power-management.rst
./rst-cleanup.py ../../misc-concepts/index.rst ../../misc-concepts/index.rst
./rst-cleanup.py ../../misc-concepts/classad-mechanism.rst ../../misc-concepts/classad-mechanism.rst
./rst-cleanup.py ../../misc-concepts/checkpoint-mechanism.rst ../../misc-concepts/checkpoint-mechanism.rst
./rst-cleanup.py ../../misc-concepts/computing-on-demand.rst ../../misc-concepts/computing-on-demand.rst
./rst-cleanup.py ../../misc-concepts/hooks.rst ../../misc-concepts/hooks.rst
./rst-cleanup.py ../../misc-concepts/logging.rst ../../misc-concepts/logging.rst
./rst-cleanup.py ../../grid-computing/index.rst ../../grid-computing/index.rst
./rst-cleanup.py ../../grid-computing/introduction-grid-computing.rst ../../grid-computing/introduction-grid-computing.rst
./rst-cleanup.py ../../grid-computing/connecting-pools-with-flocking.rst ../../grid-computing/connecting-pools-with-flocking.rst
./rst-cleanup.py ../../grid-computing/grid-universe.rst ../../grid-computing/grid-universe.rst
./rst-cleanup.py ../../grid-computing/job-router.rst ../../grid-computing/job-router.rst
./rst-cleanup.py ../../cloud-computing/index.rst ../../cloud-computing/index.rst
./rst-cleanup.py ../../cloud-computing/introduction-cloud-computing.rst ../../cloud-computing/introduction-cloud-computing.rst
./rst-cleanup.py ../../cloud-computing/annex-users-guide.rst ../../cloud-computing/annex-users-guide.rst
./rst-cleanup.py ../../cloud-computing/using-annex-first-time.rst ../../cloud-computing/using-annex-first-time.rst
./rst-cleanup.py ../../cloud-computing/annex-customization-guide.rst ../../cloud-computing/annex-customization-guide.rst
./rst-cleanup.py ../../cloud-computing/annex-configuration.rst ../../cloud-computing/annex-configuration.rst
./rst-cleanup.py ../../apis/index.rst ../../apis/index.rst
./rst-cleanup.py ../../apis/python-bindings.rst ../../apis/python-bindings.rst
./rst-cleanup.py ../../apis/chirp.rst ../../apis/chirp.rst
./rst-cleanup.py ../../apis/user-job-log-reader-api.rst ../../apis/user-job-log-reader-api.rst
./rst-cleanup.py ../../apis/command-line-interface.rst ../../apis/command-line-interface.rst
./rst-cleanup.py ../../apis/drmaa-api.rst ../../apis/drmaa-api.rst
./rst-cleanup.py ../../platform-specific/index.rst ../../platform-specific/index.rst
./rst-cleanup.py ../../platform-specific/linux.rst ../../platform-specific/linux.rst
./rst-cleanup.py ../../platform-specific/microsoft-windows.rst ../../platform-specific/microsoft-windows.rst
./rst-cleanup.py ../../platform-specific/macintosh-osx.rst ../../platform-specific/macintosh-osx.rst
./rst-cleanup.py ../../faq/index.rst ../../faq/index.rst
./rst-cleanup.py ../../contrib-source-modules/index.rst ../../contrib-source-modules/index.rst
./rst-cleanup.py ../../contrib-source-modules/introduction-contrib-source-modules.rst ../../contrib-source-modules/introduction-contrib-source-modules.rst
./rst-cleanup.py ../../contrib-source-modules/view-client-contrib-module.rst ../../contrib-source-modules/view-client-contrib-module.rst
./rst-cleanup.py ../../contrib-source-modules/job-monitor-log-viewer.rst ../../contrib-source-modules/job-monitor-log-viewer.rst
./rst-cleanup.py ../../version-history/index.rst ../../version-history/index.rst
./rst-cleanup.py ../../version-history/introduction-version-history.rst ../../version-history/introduction-version-history.rst
./rst-cleanup.py ../../version-history/upgrading-from-86-to-88-series.rst ../../version-history/upgrading-from-86-to-88-series.rst
./rst-cleanup.py ../../version-history/development-release-series-89.rst ../../version-history/development-release-series-89.rst
./rst-cleanup.py ../../version-history/stable-release-series-88.rst ../../version-history/stable-release-series-88.rst
./rst-cleanup.py ../../version-history/development-release-series-87.rst ../../version-history/development-release-series-87.rst
./rst-cleanup.py ../../version-history/stable-release-series-86.rst ../../version-history/stable-release-series-86.rst
./rst-cleanup.py ../../man-pages/index.rst ../../man-pages/index.rst
./rst-cleanup.py ../../man-pages/bosco_cluster.rst ../../man-pages/bosco_cluster.rst
./rst-cleanup.py ../../man-pages/bosco_findplatform.rst ../../man-pages/bosco_findplatform.rst
./rst-cleanup.py ../../man-pages/bosco_install.rst ../../man-pages/bosco_install.rst
./rst-cleanup.py ../../man-pages/bosco_sshstart.rst ../../man-pages/bosco_sshstart.rst
./rst-cleanup.py ../../man-pages/bosco_start.rst ../../man-pages/bosco_start.rst
./rst-cleanup.py ../../man-pages/bosco_stop.rst ../../man-pages/bosco_stop.rst
./rst-cleanup.py ../../man-pages/bosco_uninstall.rst ../../man-pages/bosco_uninstall.rst
./rst-cleanup.py ../../man-pages/condor_advertise.rst ../../man-pages/condor_advertise.rst
./rst-cleanup.py ../../man-pages/condor_annex.rst ../../man-pages/condor_annex.rst
./rst-cleanup.py ../../man-pages/condor_checkpoint.rst ../../man-pages/condor_checkpoint.rst
./rst-cleanup.py ../../man-pages/condor_check_userlogs.rst ../../man-pages/condor_check_userlogs.rst
./rst-cleanup.py ../../man-pages/condor_chirp.rst ../../man-pages/condor_chirp.rst
./rst-cleanup.py ../../man-pages/condor_cod.rst ../../man-pages/condor_cod.rst
./rst-cleanup.py ../../man-pages/condor_compile.rst ../../man-pages/condor_compile.rst
./rst-cleanup.py ../../man-pages/condor_configure.rst ../../man-pages/condor_configure.rst
./rst-cleanup.py ../../man-pages/condor_config_val.rst ../../man-pages/condor_config_val.rst
./rst-cleanup.py ../../man-pages/condor_continue.rst ../../man-pages/condor_continue.rst
./rst-cleanup.py ../../man-pages/condor_convert_history.rst ../../man-pages/condor_convert_history.rst
./rst-cleanup.py ../../man-pages/condor_dagman.rst ../../man-pages/condor_dagman.rst
./rst-cleanup.py ../../man-pages/condor_dagman_metrics_reporter.rst ../../man-pages/condor_dagman_metrics_reporter.rst
./rst-cleanup.py ../../man-pages/condor_drain.rst ../../man-pages/condor_drain.rst
./rst-cleanup.py ../../man-pages/condor_fetchlog.rst ../../man-pages/condor_fetchlog.rst
./rst-cleanup.py ../../man-pages/condor_findhost.rst ../../man-pages/condor_findhost.rst
./rst-cleanup.py ../../man-pages/condor_gather_info.rst ../../man-pages/condor_gather_info.rst
./rst-cleanup.py ../../man-pages/condor_gpu_discovery.rst ../../man-pages/condor_gpu_discovery.rst
./rst-cleanup.py ../../man-pages/condor_history.rst ../../man-pages/condor_history.rst
./rst-cleanup.py ../../man-pages/condor_hold.rst ../../man-pages/condor_hold.rst
./rst-cleanup.py ../../man-pages/condor_install.rst ../../man-pages/condor_install.rst
./rst-cleanup.py ../../man-pages/condor_job_router_info.rst ../../man-pages/condor_job_router_info.rst
./rst-cleanup.py ../../man-pages/condor_master.rst ../../man-pages/condor_master.rst
./rst-cleanup.py ../../man-pages/condor_now.rst ../../man-pages/condor_now.rst
./rst-cleanup.py ../../man-pages/condor_off.rst ../../man-pages/condor_off.rst
./rst-cleanup.py ../../man-pages/condor_on.rst ../../man-pages/condor_on.rst
./rst-cleanup.py ../../man-pages/condor_ping.rst ../../man-pages/condor_ping.rst
./rst-cleanup.py ../../man-pages/condor_pool_job_report.rst ../../man-pages/condor_pool_job_report.rst
./rst-cleanup.py ../../man-pages/condor_power.rst ../../man-pages/condor_power.rst
./rst-cleanup.py ../../man-pages/condor_preen.rst ../../man-pages/condor_preen.rst
./rst-cleanup.py ../../man-pages/condor_prio.rst ../../man-pages/condor_prio.rst
./rst-cleanup.py ../../man-pages/condor_procd.rst ../../man-pages/condor_procd.rst
./rst-cleanup.py ../../man-pages/condor_qedit.rst ../../man-pages/condor_qedit.rst
./rst-cleanup.py ../../man-pages/condor_q.rst ../../man-pages/condor_q.rst
./rst-cleanup.py ../../man-pages/condor_qsub.rst ../../man-pages/condor_qsub.rst
./rst-cleanup.py ../../man-pages/condor_reconfig.rst ../../man-pages/condor_reconfig.rst
./rst-cleanup.py ../../man-pages/condor_release.rst ../../man-pages/condor_release.rst
./rst-cleanup.py ../../man-pages/condor_reschedule.rst ../../man-pages/condor_reschedule.rst
./rst-cleanup.py ../../man-pages/condor_restart.rst ../../man-pages/condor_restart.rst
./rst-cleanup.py ../../man-pages/condor_rmdir.rst ../../man-pages/condor_rmdir.rst
./rst-cleanup.py ../../man-pages/condor_rm.rst ../../man-pages/condor_rm.rst
./rst-cleanup.py ../../man-pages/condor_router_history.rst ../../man-pages/condor_router_history.rst
./rst-cleanup.py ../../man-pages/condor_router_q.rst ../../man-pages/condor_router_q.rst
./rst-cleanup.py ../../man-pages/condor_router_rm.rst ../../man-pages/condor_router_rm.rst
./rst-cleanup.py ../../man-pages/condor_run.rst ../../man-pages/condor_run.rst
./rst-cleanup.py ../../man-pages/condor_set_shutdown.rst ../../man-pages/condor_set_shutdown.rst
./rst-cleanup.py ../../man-pages/condor_sos.rst ../../man-pages/condor_sos.rst
./rst-cleanup.py ../../man-pages/condor_sshtojob.rst ../../man-pages/condor_sshtojob.rst
./rst-cleanup.py ../../man-pages/condor_stats.rst ../../man-pages/condor_stats.rst
./rst-cleanup.py ../../man-pages/condor_status.rst ../../man-pages/condor_status.rst
./rst-cleanup.py ../../man-pages/condor_storecred.rst ../../man-pages/condor_storecred.rst
./rst-cleanup.py ../../man-pages/condor_submitdag.rst ../../man-pages/condor_submitdag.rst
./rst-cleanup.py ../../man-pages/condor_submit.rst ../../man-pages/condor_submit.rst
./rst-cleanup.py ../../man-pages/condor_suspend.rst ../../man-pages/condor_suspend.rst
./rst-cleanup.py ../../man-pages/condor_tail.rst ../../man-pages/condor_tail.rst
./rst-cleanup.py ../../man-pages/condor_top.rst ../../man-pages/condor_top.rst
./rst-cleanup.py ../../man-pages/condor_transfer_data.rst ../../man-pages/condor_transfer_data.rst
./rst-cleanup.py ../../man-pages/condor_transform_ads.rst ../../man-pages/condor_transform_ads.rst
./rst-cleanup.py ../../man-pages/condor_update_machine_ad.rst ../../man-pages/condor_update_machine_ad.rst
./rst-cleanup.py ../../man-pages/condor_updates_stats.rst ../../man-pages/condor_updates_stats.rst
./rst-cleanup.py ../../man-pages/condor_urlfetch.rst ../../man-pages/condor_urlfetch.rst
./rst-cleanup.py ../../man-pages/condor_userlog.rst ../../man-pages/condor_userlog.rst
./rst-cleanup.py ../../man-pages/condor_userprio.rst ../../man-pages/condor_userprio.rst
./rst-cleanup.py ../../man-pages/condor_vacate.rst ../../man-pages/condor_vacate.rst
./rst-cleanup.py ../../man-pages/condor_vacate_job.rst ../../man-pages/condor_vacate_job.rst
./rst-cleanup.py ../../man-pages/condor_version.rst ../../man-pages/condor_version.rst
./rst-cleanup.py ../../man-pages/condor_wait.rst ../../man-pages/condor_wait.rst
./rst-cleanup.py ../../man-pages/condor_who.rst ../../man-pages/condor_who.rst
./rst-cleanup.py ../../man-pages/giddalloc.rst ../../man-pages/giddalloc.rst
./rst-cleanup.py ../../man-pages/procdctl.rst ../../man-pages/procdctl.rst
./rst-cleanup.py ../../classad-attributes/index.rst ../../classad-attributes/index.rst
./rst-cleanup.py ../../classad-attributes/classad-types.rst ../../classad-attributes/classad-types.rst
./rst-cleanup.py ../../classad-attributes/job-classad-attributes.rst ../../classad-attributes/job-classad-attributes.rst
./rst-cleanup.py ../../classad-attributes/machine-classad-attributes.rst ../../classad-attributes/machine-classad-attributes.rst
./rst-cleanup.py ../../classad-attributes/daemon-master-classad-attributes.rst ../../classad-attributes/daemon-master-classad-attributes.rst
./rst-cleanup.py ../../classad-attributes/scheduler-classad-attributes.rst ../../classad-attributes/scheduler-classad-attributes.rst
./rst-cleanup.py ../../classad-attributes/negotiator-classad-attributes.rst ../../classad-attributes/negotiator-classad-attributes.rst
./rst-cleanup.py ../../classad-attributes/submitter-classad-attributes.rst ../../classad-attributes/submitter-classad-attributes.rst
./rst-cleanup.py ../../classad-attributes/defrag-classad-attributes.rst ../../classad-attributes/defrag-classad-attributes.rst
./rst-cleanup.py ../../classad-attributes/collector-classad-attributes.rst ../../classad-attributes/collector-classad-attributes.rst
./rst-cleanup.py ../../classad-attributes/classad-attributes-added-by-collector.rst ../../classad-attributes/classad-attributes-added-by-collector.rst
./rst-cleanup.py ../../classad-attributes/daemon-core-statistics-attributes.rst ../../classad-attributes/daemon-core-statistics-attributes.rst
./rst-cleanup.py ../../codes-other-values/index.rst ../../codes-other-values/index.rst
./rst-cleanup.py ../../man-pages/condor_shadow-exit-codes.rst ../../man-pages/condor_shadow-exit-codes.rst
./rst-cleanup.py ../../codes-other-values/job-event-log-codes.rst ../../codes-other-values/job-event-log-codes.rst
./rst-cleanup.py ../../codes-other-values/well-known-port-numbers.rst ../../codes-other-values/well-known-port-numbers.rst
./rst-cleanup.py ../../codes-other-values/daemoncore-command-numbers.rst ../../codes-other-values/daemoncore-command-numbers.rst
./rst-cleanup.py ../../codes-other-values/daemoncore-daemon-exit-codes.rst ../../codes-other-values/daemoncore-daemon-exit-codes.rst
