#ifndef __STATUS_TYPES_H__
#define __STATUS_TYPES_H__

// pretty-printing options
enum ppOption {
    PP_NOTSET,

    PP_STARTD_NORMAL,
    PP_STARTD_SERVER,
	PP_STARTD_STATE,
    PP_STARTD_RUN,

	PP_SCHEDD_NORMAL,
	PP_SCHEDD_SUBMITTORS,	

	PP_MASTER_NORMAL,
	PP_CKPT_SRVR_NORMAL,

    PP_VERBOSE,
    PP_CUSTOM
};


// modes for condor_status
enum Mode {
    MODE_NOTSET,
    MODE_STARTD_NORMAL,
    MODE_STARTD_AVAIL,
    MODE_STARTD_RUN,
	MODE_SCHEDD_NORMAL,
	MODE_SCHEDD_SUBMITTORS,
	MODE_MASTER_NORMAL,
	MODE_CKPT_SRVR_NORMAL
};
   
#endif //__STATUS_TYPES_H__
