/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
  *
  * Condor Software Copyright Notice
  * Copyright (C) 1990-2004, Condor Team, Computer Sciences Department,
  * University of Wisconsin-Madison, WI.
  *
  * This source code is covered by the Condor Public License, which can
  * be found in the accompanying LICENSE.TXT file, or online at
  * www.condorproject.org.
  *
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  * AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
  * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  * WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
  * FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
  * HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
  * MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
  * ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
  * PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
  * RIGHT.
  *
  ****************************Copyright-DO-NOT-REMOVE-THIS-LINE**/
#ifndef __STATUS_TYPES_H__
#define __STATUS_TYPES_H__

// pretty-printing options
enum ppOption {
    PP_NOTSET,

    PP_STARTD_NORMAL,
    PP_STARTD_SERVER,
	PP_STARTD_STATE,
    PP_STARTD_RUN,
    PP_STARTD_COD,

	PP_SCHEDD_NORMAL,
	PP_SCHEDD_SUBMITTORS,	

	PP_MASTER_NORMAL,
	PP_COLLECTOR_NORMAL,
	PP_CKPT_SRVR_NORMAL,
	PP_STORAGE_NORMAL,
	PP_ANY_NORMAL,
    PP_VERBOSE,
    PP_XML,
    PP_CUSTOM
};


// modes for condor_status
enum Mode {
    MODE_NOTSET,
    MODE_STARTD_NORMAL,
    MODE_STARTD_AVAIL,
    MODE_STARTD_RUN,
    MODE_STARTD_COD,
	MODE_SCHEDD_NORMAL,
	MODE_SCHEDD_SUBMITTORS,
	MODE_MASTER_NORMAL,
	MODE_COLLECTOR_NORMAL,
	MODE_CKPT_SRVR_NORMAL,
	MODE_LICENSE_NORMAL,
	MODE_STORAGE_NORMAL,
	MODE_ANY_NORMAL
};
   
#endif //__STATUS_TYPES_H__


