#!/bin/bash

USR_HOST=`echo "$1" | awk -F ':' '{print $1}'`
REMOTE=`echo "$1" | awk -F ':' '{print $2}'`
LOCAL=$2

install -d $HOME/.rcondor
cat > $HOME/.rcondor/rcondor.conf <<EOF
USR_HOST = $USR_HOST
LOCAL = $LOCAL
REMOTE = $REMOTE
EOF
