{
    printf"sed -e \"s/$(CONDOR_OPENSSL_INCLUDE)/$(CONDOR_OPENSSL_INCLUDE) $(CONDOR_POSTGRESQL_INCLUDE)/g\" -e \"s/$(CONDOR_OPENSSL_LIB)/$(CONDOR_OPENSSL_LIB) $(CONDOR_POSTGRESQL_LIB)/g\" -e \"s/$(CONDOR_OPENSSL_LIBPATH)/$(CONDOR_OPENSSL_LIBPATH) $(CONDOR_POSTGRESQL_LIBPATH)/g\" %s > backup\\%s\n",$0,$0 
}
