nmake /f condor_util_lib.mak
nmake /f condor_cpp_util.mak
nmake /f condor_io.mak
nmake /f condor_classad.mak
nmake /f condor_kbdd_dll.mak
nmake /f condor_procapi.mak
nmake /f condor_sysapi.mak
nmake /f condor_daemon_core.mak
nmake /f condor_acct.mak
nmake /f condor_ckpt_server_api.mak
nmake /f condor_qmgmt.mak
nmake /f condor_collector.mak
nmake /f condor_config_val.mak
# nmake /f condor_give_interactive.mak
nmake /f condor_history.mak
nmake /f condor_mail.mak
nmake /f condor_master.mak
nmake /f condor_negotiator.mak
nmake /f condor_preen.mak
nmake /f condor_prio.mak
nmake /f condor_q.mak
nmake /f condor_qedit.mak
nmake /f condor_rm.mak
nmake /f condor_schedd.mak
nmake /f condor_shadow.mak
nmake /f condor_startd.mak
nmake /f condor_starter.mak
nmake /f condor_stats.mak
nmake /f condor_status.mak
nmake /f condor_submit.mak
nmake /f condor_tool.mak
nmake /f condor_userprio.mak
