#! /usr/bin/perl -w
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


##*****************************************************************
## Creates a vanilla condor job that starts a condor installation
## on a remote host.
## Author: Joe Meehean
## Date: 7/21/05
##*****************************************************************

#***
# Uses
#***
use strict;
use Getopt::Long;

#***
# Constant Static Variables
#***
my $USAGE = "Usage: condor_flying_start\n".
    "<condor_config_file1> <condor_config_file2>\n".
    "[condor_config_file3 condor_config_file4 ...]\n".
    "[-help]\n";
