#if !defined(_CARMIPRO_H)
#define _CARMIPRO_H
#include "pvmsdpro.h"

#define CARMI_FIRST	(SM_LAST+1)

#define CARMI_RESPAWN (CARMI_FIRST+1)
#define CARMI_CHKPT   (CARMI_FIRST+2)
#define CARMI_ADDHOST (CARMI_FIRST+3)
#define CARMI_SPAWN	  (CARMI_FIRST+4)
#define CARMI_VACATE  (CARMI_FIRST + 6)
#define CARMI_CANCEL_REQ (CARMI_FIRST + 7)
#define CARMI_REQ_URL_FOR_FILE (CARMI_FIRST + 8)
#define CARMI_NOTIFY (CARMI_FIRST + 9)
#define CARMI_LAST    (CARMI_NOTIFY)

#define CO_CHECK_FIRST 						(CARMI_LAST+1)
#define CO_CHECK_REQ_CKPT					(CO_CHECK_FIRST + 1)
#define CO_CHECK_REQ_RESTART				(CO_CHECK_FIRST + 2)
#define CO_CHECK_REQ_MIGRATE				(CO_CHECK_FIRST + 3)
#define CO_CHECK_RM_CKPT					(CO_CHECK_FIRST + 4)
#endif
