/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
  *
  * Condor Software Copyright Notice
  * Copyright (C) 1990-2004, Condor Team, Computer Sciences Department,
  * University of Wisconsin-Madison, WI.
  *
  * This source code is covered by the Condor Public License, which can
  * be found in the accompanying LICENSE.TXT file, or online at
  * www.condorproject.org.
  *
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  * AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
  * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  * WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
  * FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
  * HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
  * MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
  * ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
  * PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
  * RIGHT.
  *
  ****************************Copyright-DO-NOT-REMOVE-THIS-LINE**/
#if !defined(_CARMIPRO_H)
#define _CARMIPRO_H

#ifdef PVM34
#include "pvmproto.h"
#else
#include "pvmsdpro.h"
#endif


#define CARMI_FIRST	(SM_LAST+1)

#define CARMI_RESPAWN (CARMI_FIRST+1)
#define CARMI_CHKPT   (CARMI_FIRST+2)
#define CARMI_ADDHOST (CARMI_FIRST+3)
#define CARMI_SPAWN	  (CARMI_FIRST+4)
#define CARMI_VACATE_NOTIFY  (CARMI_FIRST + 6)
#define CARMI_CANCEL_REQ (CARMI_FIRST + 7)
#define CARMI_REQ_URL_FOR_FILE (CARMI_FIRST + 8)
#define CARMI_NOTIFY (CARMI_FIRST + 9)
#define CARMI_LAST    (CARMI_NOTIFY)

#define CO_CHECK_FIRST 						(CARMI_LAST+1)
#define CO_CHECK_REQ_CKPT					(CO_CHECK_FIRST + 1)
#define CO_CHECK_REQ_RESTART				(CO_CHECK_FIRST + 2)
#define CO_CHECK_REQ_MIGRATE				(CO_CHECK_FIRST + 3)
#define CO_CHECK_RM_CKPT					(CO_CHECK_FIRST + 4)
#endif
