#if !defined(_CARMIPRO_H)
#define _CARMIPRO_H
#include "pvmsdpro.h"

#define CARMI_FIRST	(SM_LAST+1)

#define CARMI_RESPAWN (CARMI_FIRST+1)
#define CARMI_CHKPT   (CARMI_FIRST+2)
#define CARMI_ADDHOST (CARMI_FIRST+3)
#define CARMI_SPAWN	  (CARMI_FIRST+4)
#define CARMI_CKPT_ON_VACATE (CARMI_FIRST + 5)
#define CARMI_VACATE  (CARMI_FIRST + 6)
#define CARMI_LAST    (CARMI_VACATE)

#define CO_CHECK_FIRST (CARMI_LAST+1)
#define CO_CHECK_SIMPLE_CKPT_TASK_TO_FILE (CO_CHECK_FIRST + 1)
#define CO_CHECK_RESTART_TASK_FROM_FILE (CO_CHECK_FIRST + 2)
#define CO_CHECK_SIMPLE_CKPT_TASK (CO_CHECK_FIRST + 3)
#define CO_CHECK_RESTART_TASK (CO_CHECK_FIRST + 4)
#define CO_CHECK_SIMPLE_MIGRATE_TASK_TO_HOST (CO_CHECK_FIRST + 5)
#define CO_CHECK_SIMPLE_MIGRATE_TASK (CO_CHECK_FIRST + 6)
#endif
