/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
  *
  * Condor Software Copyright Notice
  * Copyright (C) 1990-2004, Condor Team, Computer Sciences Department,
  * University of Wisconsin-Madison, WI.
  *
  * This source code is covered by the Condor Public License, which can
  * be found in the accompanying LICENSE.TXT file, or online at
  * www.condorproject.org.
  *
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  * AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
  * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  * WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
  * FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
  * HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
  * MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
  * ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
  * PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
  * RIGHT.
  *
  ****************************Copyright-DO-NOT-REMOVE-THIS-LINE**/
#ifndef CONDOR_ERROR_CODES_H_INCLUDE
#define CONDOR_ERROR_CODES_H_INCLUDE


const int AUTHENTICATE_ERR_NOT_BUILT = 1001;
const int AUTHENTICATE_ERR_HANDSHAKE_FAILED = 1002;
const int AUTHENTICATE_ERR_OUT_OF_METHODS = 1003;
const int AUTHENTICATE_ERR_METHOD_FAILED = 1004;
const int AUTHENTICATE_ERR_KEYEXCHANGE_FAILED = 1005;

const int SECMAN_ERR_INTERNAL = 2001;
const int SECMAN_ERR_INVALID_POLICY = 2002;
const int SECMAN_ERR_CONNECT_FAILED = 2003;
const int SECMAN_ERR_NO_SESSION = 2004;
const int SECMAN_ERR_ATTRIBUTE_MISSING = 2005;
const int SECMAN_ERR_NO_KEY = 2006;
const int SECMAN_ERR_COMMUNICATIONS_ERROR = 2007;
const int SECMAN_ERR_AUTHENTICATION_FAILED = 2008;

const int DAEMON_ERR_INTERNAL = 3001;

const int SCHEDD_ERR_JOB_ACTION_FAILED = 4001;
const int SCHEDD_ERR_SPOOL_FILES_FAILED = 4002;
const int SCHEDD_ERR_UPDATE_GSI_CRED_FAILED = 4003;

const int GSI_ERR_AQUIRING_SELF_CREDINTIAL_FAILED = 5001;
const int GSI_ERR_REMOTE_SIDE_FAILED = 5002;
const int GSI_ERR_ACQUIRING_SELF_CREDINTIAL_FAILED = 5003;
const int GSI_ERR_AUTHENTICATION_FAILED = 5004;
const int GSI_ERR_COMMUNICATIONS_ERROR = 5005;
const int GSI_ERR_UNAUTHORIZED_SERVER = 5006;
const int GSI_ERR_NO_VALID_PROXY = 5007;

const int CEDAR_ERR_CONNECT_FAILED = 6001;


#endif

