#include "condor_fix_stdio.h"
#include <stdlib.h>
#include "condor_fix_unistd.h"
#include <limits.h>
#include <string.h>
#include <ctype.h>
#include <fcntl.h>
#include "_condor_fix_types.h"
#include <errno.h>
