#!/bin/sh

if [ "$_condor_LOCAL_DIR" = "." ]; then
  export _condor_LOCAL_DIR=$(pwd)
fi

#If we have an X509 user proxy, use it as the Condor daemon proxy.
if [ "$_condor_GSI_DAEMON_PROXY" = "" ] && [ -a "$X509_USER_PROXY" ]; then
  export _condor_GSI_DAEMON_PROXY="$X509_USER_PROXY"
fi

exec ${_condor_SBIN}/condor_master "$@"

