# Copyright 2025 HTCondor Team, Computer Sciences Department,
# University of Wisconsin-Madison, WI.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from adstash.mapping.common import MAX_KEYWORD_LEN, METADATA_MAPPING, OTHER_MAPPING_SETTINGS


# INDEXED_TEXT_ATTRS should only contain string attrs that
# require full text search.
INDEXED_TEXT_ATTRS = set()

# NON_INDEXED_TEXT_ATTRS should contain string attrs that
# are highly variable and not likely to be searched on.
# These could always be "upgraded" to indexed text/keywords
# by adding your own mapping.
NON_INDEXED_TEXT_ATTRS = {
    "Args",
    "Arguments",
    "AutoClusterAttrs",
    "DAG_Address",
    "EditedClusterAttrs",
    "JobAdInformationAttrs",
    "JobMachineAttrs",
    "JobMaterializeDigestFile",
    "JobMaterializeItemsFile",
    "OtherJobRemoveRequirements",
    "Requirements",
    "SubmitEventNotes",
    "SubmitEventUserNotes",
    "UserLogExecuteEventAttrs",
    "VMPARAM_vm_Disk",
}

# INDEXED_KEYWORD_ATTRS should contain string attrs
# with relatively few unique values.
INDEXED_KEYWORD_ATTRS = {
    "AccountingGroup",
    "AcctGroup",
    "AcctGroupUser",
    "AllRemoteHosts",
    "AppendFiles",
    "AssignedGPUs",
    "AutoClusterId",
    "AWSRegion",
    "BatchProject",
    "BatchQueue",
    "CloudLabelNames",
    "Cmd",
    "CommonInputFiles",
    "CompressFiles",
    "ConcurrencyLimits",
    "CondorPlatform",
    "CondorVersion",
    "ContainerImage",
    "ContainerImageSource",
    "ContainerServiceNames",
    "ContainerTargetDir",
    "CronDayOfMonth",
    "CronDayOfWeek",
    "CronHour",
    "CronMinute",
    "CronMonth",
    "CUDAVersion",
    "DAGManNodesLog",
    "DAGManNodesMask",
    "DAGNodeName",
    "DAGParentNodeNames",
    "DockerImage",
    "DockerNetworkType",
    "DockerPullPolicy",
    "DontEncryptInputFiles",
    "DontEncryptOutputFiles",
    "EncryptInputFiles",
    "EncryptOutputFiles",
    "EpochAdType",
    "Err",
    "ExitReason",
    "FetchFiles",
    "FileRemaps",
    "FileSystemDomain",
    "GlobalJobId",
    "GridJobId",
    "GridJobStatus",
    "GridResource",
    "HoldKillSig",
    "HoldReason",
    "In",
    "Iwd",
    "JobBatchName",
    "JobDescription",
    "JobKeyword",
    "JobStarterDebug",
    "JobStarterLog",
    "JobState",
    "JobSubmitFile",
    "JobVMType",
    "KillSig",
    "LastFileTransferErrorProtocol",
    "LastHoldReason",
    "LastRejMatchNegotiator",
    "LastRejMatchReason",
    "LastReleaseReason",
    "LastRemoteHost",
    "LastRemotePool",
    "LastShadowException",
    "LocalFiles",
    "Managed",
    "ManifestDir",
    "MyAddress",
    "MyType",
    "NotifyUser",
    "NTDomain",
    "OAuthServicesNeeded",
    "OnExitHoldReason",
    "OnExitRemoveReason",
    "OriginalErr",
    "OriginalOut",
    "OSHomeDir",
    "OsUser",
    "Out",
    "OutputDestination",
    "OutputDirectory",
    "Owner",
    "PeriodicHoldReason",
    "PeriodicReleaseReason",
    "PeriodicRemoveReason",
    "PeriodicVacateReason",
    "PostCmd",
    "PreCmd",
    "PrimaryUnixGroup",
    "ProjectName",
    "ProvisionedResources",
    "PublicInputFiles",
    "ReleaseReason",
    "RemoteHost",
    "RemoteIwd",
    "RemotePool",
    "RemoveKillSig",
    "RemoveReason",
    "RequestedAcctGroup",
    "RequeueReason",
    "RetryRequestMemory",
    "RootDir",
    "ScheddName",
    "ShadowIpAddr",
    "ShadowVersion",
    "ShouldTransferFiles",
    "SingularityImage",
    "StartdIpAddr",
    "StartdName",
    "StartdPrincipal",
    "StartdSlot",
    "StarterIpAddr",
    "StarterPrincipal",
    "Status",
    "SubmitVersion",
    "SubmitterGlobalJobId",
    "SubmitterGroup",
    "SubmitterNegotiatingGroup",
    "TargetAnnexName",
    "TargetType",
    "TransferCheckpoint",
    "TransferInput",
    "TransferInputRemaps",
    "TransferIntermediate",
    "TransferOutput",
    "TransferOutputRemaps",
    "TransferPlugins",
    "TransformOnEvict",
    "Universe",
    "User",
    "UserLog",
    "UserLogFile",
    "VacateReason",
    "WantTransferPluginMethods",
    "WhenToTransferOutput",
}

# NON_INDEXED_KEYWORD_ATTRS will be stored as keywords
# but not indexed.
NON_INDEXED_KEYWORD_ATTRS = set()

FLOAT_ATTRS = {
    "CPUsUsage",
    "GPUsAverageUsage",
    "GPUsMemoryUsage",
    "JobBatchId",
    "JobDuration",
    "JobVMCpuUtilization",
    "NetworkInputMb",
    "NetworkOutputMb",
    "Rank",
}

INT_ATTRS = {
    "ActivationDuration",
    "ActivationExecutionDuration",
    "ActivationSetupDuration",
    "ActivationTeardownDuration",
    "AllowedExecuteDuration",
    "AllowedJobDuration",
    "AutoClusterId",
    "BatchRuntime",
    "BlockReadBytes",
    "BlockReadKbytes",
    "BlockReads",
    "BlockWriteBytes",
    "BlockWriteKbytes",
    "BlockWrites",
    "BufferBlockSize",
    "BufferSize",
    "BytesRecvd",
    "BytesSent",
    "CheckpointNumber",
    "ClusterId",
    "CommittedSlotTime",
    "CommittedSuspensionTime",
    "CommittedTime",
    "CoreSize",
    "CPUInstructions",
    "CpusProvisioned",
    "CumulativeRemoteSysCpu",
    "CumulativeRemoteUserCpu",
    "CumulativeSlotTime",
    "CumulativeSuspensionTime",
    "CumulativeTransferTime",
    "CurrentHosts",
    "DAG_JobsCompleted",
    "DAG_JobsHeld",
    "DAG_JobsIdle",
    "DAG_JobsRunning",
    "DAG_JobsSubmitted",
    "DAG_NodesDone",
    "DAG_NodesFailed",
    "DAG_NodesFutile",
    "DAG_NodesHoldrun",
    "DAG_NodesPostrun",
    "DAG_NodesPrerun",
    "DAG_NodesQueued",
    "DAG_NodesReady",
    "DAG_NodesTotal",
    "DAG_NodesUnready",
    "DAG_Status",
    "DAGMan_MaxHoldScripts",
    "DAGMan_MaxIdle",
    "DAGMan_MaxJobs",
    "DAGMan_MaxPostScripts",
    "DAGMan_MaxPreScripts",
    "DAGManJobId",
    "DAGManNodeRetry",
    "DataLocationsCount",
    "DeferralPrepTime",
    "DeferralWindow",
    "DiskProvisioned",
    "DiskUsage_RAW",
    "DiskUsage",
    "ErrSize",
    "ExecutableSize_RAW",
    "ExecutableSize",
    "ExitCode",
    "ExitSignal",
    "ExitStatus",
    "GPUsMaxCapability",
    "GPUsMinCapability",
    "GPUsMinMemory",
    "GPUsMinRuntime",
    "GpusProvisioned",
    "HoldReasonCode",
    "HoldReasonSubCode",
    "ImageSize_RAW",
    "ImageSize",
    "InitialWaitDuration",
    "IOWait",
    "JobCurrentReconnectAttempt",
    "JobLeaseDuration",
    "JobMachineAttrsHistoryLength",
    "JobMaterializeLimit",
    "JobMaterializeMaxIdle",
    "JobMaterializeNextProcId",
    "JobMaterializeNextRow",
    "JobMaterializePaused",
    "JobMaxRetries",
    "JobMaxVacateTime",
    "JobPid",
    "JobPrio",
    "JobRunCount",
    "JobStatus",
    "JobStatusOnRelease",
    "JobSubmitMethod",
    "JobSuccessExitCode",
    "JobUniverse",
    "JobVM_VCPUS",
    "JobVMMemory",
    "KeepClaimIdle",
    "KillSigTimeout",
    "LastHoldReasonCode",
    "LastHoldReasonSubCode",
    "LastJobStatus",
    "LastRemoteWallClockTime",
    "LocalSysCpu",
    "LocalUserCpu",
    "MachineAttrCpus0",
    "MachineAttrSlotWeight0",
    "MachineCount",
    "MaxHosts",
    "MaxJobRetirementTime",
    "MaxRequestMemory",
    "MaxTransferInputMB",
    "MaxTransferOutputMB",
    "MaxWallTimeMins_RAW",
    "MaxWallTimeMins",
    "MemoryProvisioned",
    "MemoryUsage",
    "MinHosts",
    "NextJobStartDelay",
    "NoopJobExitCode",
    "NoopJobExitSignal",
    "NumCkpts_RAW",
    "NumCkpts",
    "NumHolds",
    "NumInputTransferStarts",
    "NumJobCompletions",
    "NumJobCoolDowns",
    "NumJobMatches",
    "NumJobReconnects",
    "NumJobStarts",
    "NumOutputTransferStarts",
    "NumPids",
    "NumRestarts",
    "NumShadowExceptions",
    "NumShadowStarts",
    "NumSystemHolds",
    "NumVacates",
    "NumVacatesPreExecution",
    "OnExitHoldSubCode",
    "OrigMaxHosts",
    "OutSize",
    "PelicanRetryDelay",
    "PeriodicHoldSubCode",
    "PilotRestLifeTimeMins",
    "PostCmdExitCode",
    "PostCmdExitSignal",
    "PostJobPrio1",
    "PostJobPrio2",
    "PreCmdExitCode",
    "PreCmdExitSignal",
    "PreJobPrio1",
    "PreJobPrio2",
    "ProcId",
    "ProportionalSetSizeKb_RAW",
    "ProportionalSetSizeKb",
    "RecentBlockReadBytes",
    "RecentBlockReadKbytes",
    "RecentBlockReads",
    "RecentBlockWriteBytes",
    "RecentBlockWriteKbytes",
    "RecentBlockWrites",
    "RecentStatsLifetime",
    "RecentStatsLifetimeStarter",
    "RecentWindowMax",
    "RecentWindowMaxStarter",
    "RemoteSlotID",
    "RemoteSysCpu",
    "RemoteUserCpu",
    "RemoteWallClockTime",
    "RequestCpus",
    "RequestDisk",
    "RequestGpus",
    "RequestMemory",
    "RequestVirtualMemory",
    "ResidentSetSize_RAW",
    "ResidentSetSize",
    "ScheddInterval",
    "ScratchDirFileCount",
    "StackSize",
    "StatsLifetime",
    "StatsLifetimeStarter",
    "SuccessCheckpointExitCode",
    "SuccessCheckpointExitSignal",
    "SuccessPostExitCode",
    "SuccessPostExitSignal",
    "SuccessPreExitCode",
    "SuccessPreExitSignal",
    "TotalJobReconnectAttempts",
    "TotalSubmitProcs",
    "TotalSuspensions",
    "TransferInputSizeMB",
    "VacateReasonCode",
    "VacateReasonSubCode",
    "WallClockCheckpoint",
    "WindowsBuildNumber",
    "WindowsMajorVersion",
    "WindowsMinorVersion",
}

# Date attrs will be stored as epoch_seconds.
DATE_ATTRS = {
    "@timestamp",
    "CompletionDate",
    "DAG_AdUpdateTime",
    "DeferralTime",
    "EnteredCurrentStatus",
    "EpochWriteDate",
    "FirstJobMatchDate",
    "JobCoolDownExpiration",
    "JobCurrentFinishTransferInputDate",
    "JobCurrentFinishTransferOutputDate",
    "JobCurrentStartDate",
    "JobCurrentStartExecutingDate",
    "JobCurrentStartTransferInputDate",
    "JobCurrentStartTransferOutputDate",
    "JobDisconnectedDate",
    "JobFinishedHookDone",
    "JobLastCheckpointTime",
    "JobLastStartDate",
    "JobLeaseExpiration",
    "JobMaterializeDate",
    "JobQueueBirthdate",
    "JobStartDate",
    "LastJobLeaseRenewal",
    "LastMatchTime",
    "LastRejMatchTime",
    "LastRemoteStatusUpdate",
    "LastSuspensionTime",
    "LastVacateTime_RAW",
    "LastVacateTime",
    "QDate",
    "RecentStatsTickTime",
    "RecentStatsTickTimeStarter",
    "RecordTime",
    "ShadowBday",
    "StageInFinish",
    "StageInStart",
    "StageOutFinish",
    "StageOutStart",
    "StatsLastUpdateTime",
    "StatsLastUpdateTimeStarter",
    "StderrMtime",
    "StdoutMtime",
    "TransferInFinished",
    "TransferInQueued",
    "TransferInStarted",
    "TransferOutFinished",
    "TransferOutQueued",
    "TransferOutStarted",
}

BOOL_ATTRS = {
    "BufferFiles",
    "ContainerIsCommon",
    "CurrentStatusUnknown",
    "DAG_InRecovery",
    "DAGLifetimeJob",
    "DataflowJobSkipped",
    "DockerOverrideEntrypoint",
    "EncryptExecuteDirectory",
    "EraseOutputAndErrorOnRestart",
    "ExecuteDirWasEncrypted",
    "ExitBySignal",
    "GlobusResubmit",
    "IsDaemonCore",
    "IsNoopJob",
    "JobCoreDumped",
    "JobRequiresSandbox",
    "JobVMCheckpoint",
    "JobVMNetworking",
    "JobVMVNCConsole",
    "LeaveJobInQueue",
    "LoadProfile",
    "ManifestDesired",
    "NiceUser",
    "Nonessential",
    "OnExitHold",
    "OnExitRemove",
    "PelicanRetryEnabled",
    "PeriodicHold",
    "PeriodicRelease",
    "PeriodicRemove",
    "PeriodicVacate",
    "PostCmdExitBySignal",
    "PreCmdExitBySignal",
    "PreserveRelativeExecutable",
    "PreserveRelativePath",
    "PreserveRelativePaths",
    "RequireGPUs",
    "RunAsOwner",
    "SendCredential",
    "SkipIfDataflow",
    "SpoolOnEvict",
    "StreamErr",
    "StreamIn",
    "StreamOut",
    "SuccessCheckpointExitBySignal",
    "SuccessPostExitBySignal",
    "SuccessPreExitBySignal",
    "TerminationPending",
    "TransferContainer",
    "TransferErr",
    "TransferExecutable",
    "TransferIn",
    "TransferOut",
    "TransferQueued",
    "TransferringInput",
    "TransferringOutput",
    "Use_x509UserProxy",
    "UserLogUseXML",
    "VMPARAM_No_Output_VM",
    "WantAdRevaluate",
    "WantCheckpoint",
    "WantCheckpointSignal",
    "WantClaiming",
    "WantCompletionVisaFromSchedD",
    "WantContainer",
    "WantDelayedUpdates",
    "WantDocker",
    "WantDockerImage",
    "WantExecutionVisaFromStarter",
    "WantFTOnCheckpoint",
    "WantGracefulRemoval",
    "WantIOProxy",
    "WantJobNetworking",
    "WantMatchDiagnostics",
    "WantMatching",
    "WantParallelScheduling",
    "WantParallelSchedulingGroups",
    "WantPslotPreemption",
    "WantRemoteIO",
    "WantRemoteSyscalls",
    "WantRemoteUpdates",
    "WantResAd",
    "WantSandboxImage",
    "WantSIF",
}

# Object attrs should be used for nested ClassAds
# and either dynamic templates should be used to
# refine the types for the child ClassAd attrs or
# the types should be explicitly defined.
OBJECT_ATTRS = {
    "DAG_Stats",
    "NumHoldsByReason",
    "NumVacatesByReason",
    "NumVacatesByReasonPreExecution",
    "ToE",
    "TransferInputFileCounts",
    "TransferInputStats",
    "TransferOutputFileCounts",
    "TransferOutputStats",
}

# Nested attrs should be used for lists of nested
# ClassAds. In the future, it would be nice to split
# lists of files (e.g. TransferIn/Out) and machine attrs
# into nested fields.
NESTED_ATTRS = set()

# Ignore attrs are generally assumed to potentially
# contain secrets (or paths to secrets) or are otherwise
# not considered useful for keeping around.
IGNORE_ATTRS = {
    "AuthTokenGroups",
    "AuthTokenId",
    "AuthTokenIssuer",
    "AuthTokenScopes",
    "AuthTokenSubject",
    "AzureAdminKey",
    "AzureAdminUsername",
    "AzureAuthFile",
    "ClaimId",
    "CmdHash",
    "DelegatedProxyExpiration",
    "EC2AccessKeyId",
    "EC2KeyPair",
    "EC2KeyPairFile",
    "EC2SecretAccessKey",
    "EC2SecurityGroups",
    "EC2SecurityIDs",
    "EC2UserData",
    "EC2UserDataFile",
    "Env",
    "EnvDelim",
    "Environment",
    "GceAccount",
    "GceAuthFile",
    "GceJsonFile",
    "GceMetadataFile",
    "GlideinCredentialIdentifier",
    "GlideinSecurityClass",
    "JobCoreFileName",
    "JobNotification",
    "KeystoreAlias",
    "KeystoreFile",
    "KeystorePassphraseFile",
    "LastPublicClaimId",
    "orig_environment",
    "osg_environment",
    "PostArgs",
    "PostArguments",
    "PostEnv",
    "PostEnvironment",
    "PreArgs",
    "PreArguments",
    "PreEnv",
    "PreEnvironment",
    "PublicClaimId",
    "RunInstanceID",
    "ScitokensFile",
    "SpooledOutputFiles",
    "TransferSocket",
    "UidDomain",
    "x509UserProxy",
    "x509UserProxyEmail",
    "x509UserProxyExpiration",
    "x509UserProxyFirstFQAN",
    "x509UserProxyFQAN",
    "x509UserProxySubject",
    "x509UserProxyVOName",
}

# Dynamic templates allow for matching unmapped field names using patterns,
# and are evaluated in order. Once one field matches, the remaining
# templates are ignored.
DYNAMIC_TEMPLATES = [
    {"raw_expression": {  # Attrs ending in "_EXPR" are generated during
        "match": r"*_EXPR",  # ad conversion for expressions that cannot be evaluated
        "mapping": {"type": "keyword", "ignore_above": MAX_KEYWORD_LEN},
    }},
    {"transformbody_attrs": {  # Retry request attr expressions
        "match": r"TransformBody_*",
        "mapping": {"type": "keyword", "ignore_above": MAX_KEYWORD_LEN},
    }},
    {"date_attrs": {  # Attrs ending in "Date" are usually timestamps
        "match": r"*Date",
        "mapping": {"type": "date", "format": "epoch_second||strict_date_optional_time"},
    }},
    {"provisioned_attrs": {  # Attrs ending in "Provisioned" are
        "match": r"*Provisioned",  # resource numbers
        "mapping": {"type": "long"},
    }},
    {"num_attrs": {  # Attrs starting with Num are usually numbers
        "match_pattern": "regex",
        "match": r"Num[A-Z].*",
     "mapping": {"type": "long"},
    }},
    {"stats_attrs": {  # Attrs ending with Stats are usually
        "match_pattern": "regex",  # ClassAds containing floating point numbers
        "match": r".+Stats\..+",
        "mapping": {"type": "double"},
    }},
    {"counts_attrs": {  # Attrs ending with Counts are usually
        "match_pattern": "regex",  # ClassAds containing numbers
        "match": r".+Counts\..+",
        "mapping": {"type": "long"},
    }},
    {"resource_request_attrs": {  # Attrs starting with "Request" are
        "match_pattern": "regex",  # usually resource numbers
        "match": r"^Request[A-Z].*$",
        "mapping": {"type": "long"},
    }},
    {"target_bool_attrs": {  # Attrs starting with "Want", "Has", or
        "match_pattern": "regex",  # "Is" are usually boolean checks
        "match": r"(?i)^(Want|Has|Is).+$",
        "mapping": {"type": "boolean"},
    }},
    {"DEFAULT": {  # DEFAULT MAPPING - will be evaluated last
        "match_mapping_type": "string",  # Store unknown attrs as indexed keywords
        "mapping": {"type": "keyword", "ignore_above": MAX_KEYWORD_LEN},  # https://www.elastic.co/guide/en/elasticsearch/reference/7.17/tune-for-disk-usage.html#default-dynamic-string-mapping
    }}
]
