updated_urls = {

    # Overview
    "Overview.html": "../overview/index.html",
    "HighThroughputComputingHTCanditsRequirements.html": "../overview/high-throughput-computing-requirements.html",
    "HTCondorsPower.html": "../overview/htcondors-power.html",
    "ExceptionalFeatures.html": "../overview/exceptional-features.html",
    "CurrentLimitations.html": "../overview/current-limitations.html",
    "Availability.html": "../overview/availability.html",
    "ContributionsandAcknowledgments.html": "../overview/contributions-and-acknowledgments.html",
    "ContactInformation.html": "../overview/contact-information.html",
    "PrivacyNotice.html": "../overview/privacy-notice.html",

    # User's Manual
    "UsersManual.html": "../users-manual/index.html",
    "WelcometoHTCondor.html": "../users-manual/welcome-to-htcondor.html",
    "Introduction.html": "../users-manual/introduction-users-manual.html",
    "MatchmakingwithClassAds.html": "../users-manual/matchmaking-with-classads.html",
    "RunningaJobtheStepsToTake.html": "../users-manual/running-a-job-steps.html",
    "SubmittingaJob.html": "../users-manual/submitting-a-job.html",
    "ManagingaJob.html": "../users-manual/managing-a-job.html",
    "PrioritiesandPreemption.html": "../users-manual/priorities-and-preemption.html",
    "JavaApplications.html": "../users-manual/java-applications.html",
    "ParallelApplicationsIncludingMPIApplications.html": "../users-manual/parallel-applications.html",
    "DAGManApplications.html": "../users-manual/dagman-applications.html",
    "VirtualMachineApplications.html": "../users-manual/virtual-machine-applications.html",
    "DockerUniverseApplications.html": "../users-manual/docker-universe-applications.html",
    "TimeSchedulingforJobExecution.html": "../users-manual/time-scheduling-for-job-execution.html",
    "SpecialEnvironmentConsiderations.html": "../users-manual/special-environment-considerations.html",
    "PotentialProblems.html": "../users-manual/potential-problems.html",

    # Administrator's Manual
    "AdministratorsManual.html": "../admin-manual/index.html",
    "Introduction1.html": "../admin-manual/introduction-admin-manual.html",
    "InstallationStartUpShutDownandReconfiguration.html": "../admin-manual/installation-startup-shutdown-reconfiguration.html",
    "IntroductiontoConfiguration.html": "../admin-manual/introduction-to-configuration.html",
    "ConfigurationTemplates.html": "../admin-manual/configuration-templates.html",
    "ConfigurationMacros.html": "../admin-manual/configuration-macros.html",
    "UserPrioritiesandNegotiation.html": "../admin-manual/user-priorities-negotiation.html",
    "PolicyConfigurationforExecuteHostsandforSubmitHosts.html": "../admin-manual/policy-configuration.html",
    "Security.html": "../admin-manual/security.html",
    "NetworkingincludessectionsonPortUsageandCCB.html": "../admin-manual/networking.html",
    "TheCheckpointServer.html": "../admin-manual/checkpoint-server.html",
    "DaemonCore.html": "../admin-manual/daemoncore.html",
    "Monitoring.html": "../admin-manual/monitoring.html",
    "TheHighAvailabilityofDaemons.html": "../admin-manual/high-availability.html",
    "SettingUpforSpecialEnvironments.html": "../admin-manual/setting-up-special-environments.html",
    "JavaSupportInstallation.html": "../admin-manual/java-support-installation.html",
    "SettingUptheVMandDockerUniverses.html": "../admin-manual/setting-up-vm-docker-universes.html",
    "SingularitySupport.html": "../admin-manual/singularity-support.html",
    "PowerManagement.html": "../admin-manual/power-management.html",

    # Miscellaneous Concepts
    "MiscellaneousConcepts.html": "../misc-concepts/index.html",
    "HTCondorsClassAdMechanism.html": "../misc-concepts/classad-mechanism.html",
    "HTCondorsCheckpointMechanism.html": "../misc-concepts/checkpoint-mechanism.html",
    "ComputingOnDemandCOD.html": "../misc-concepts/computing-on-demand.html",
    "Hooks.html": "../misc-concepts/hooks.html",
    "LogginginHTCondor.html": "../misc-concepts/logging.html",

    # Grid Computing
    "GridComputing.html": "../grid-computing/index.html",
    "Introduction2.html": "../grid-computing/introduction-grid-computing.html",
    "ConnectingHTCondorPoolswithFlocking.html": "../grid-computing/connecting-pools-with-flocking.html",
    "TheGridUniverse.html": "../grid-computing/grid-universe.html",
    "TheHTCondorJobRouter.html": "../grid-computing/job-router.html",

    # Cloud Computing
    "CloudComputing.html": "../cloud-computing/index.html",
    "Introduction3.html": "../cloud-computing/introduction-cloud-computing.html",
    "HTCondorAnnexUsersGuide.html": "../cloud-computing/annex-users-guide.html",
    "UsingCondorannexfortheFirstTime.html": "../cloud-computing/using-annex-first-time.html",
    "HTCondorAnnexCustomizationGuide.html": "../cloud-computing/annex-customization-guide.html",
    "HTCondorAnnexConfiguration.html": "../cloud-computing/annex-configuration.html",

    # Application Programming Interfaces (APIs)
    "ApplicationProgrammingInterfacesAPIs.html": "../apis/index.html",
    "PythonBindings.html": "../apis/python-bindings.html",
    "Chirp.html": "../apis/chirp.html",
    "TheHTCondorUserandJobLogReaderAPI.html": "../apis/user-job-log-reader-api.html",
    "TheCommandLineInterface.html": "../apis/command-line-interface.html",
    "TheDRMAAAPI.html": "../apis/drmaa-api.html",

    # Platform-Specific Information
    "PlatformSpecificInformation.html": "../platform-specific/index.html",
    "Linux.html": "../platform-specific/linux.html",
    "MicrosoftWindows.html": "../platform-specific/microsoft-windows.html",
    "MacintoshOSX.html": "../platform-specific/macintosh-osx.html",

    # Frequently Asked Questions
    "FrequentlyAskedQuestionsFAQ.html": "../faq/index.html",

    # Contrib and Source Modules
    "ContribandSourceModules.html": "../contrib-source-modules/index.html",
    "Introduction4.html": "../contrib-source-modules/introduction-contrib-source-modules.html",
    "TheHTCondorViewClientContribModule.html": "../contrib-source-modules/view-client-contrib-module.html",
    "JobMonitorLogViewer.html": "../contrib-source-modules/job-monitor-log-viewer.html",

    # Version History and Release Notes
    "VersionHistoryandReleaseNotes.html": "../version-history/index.html",
    "IntroductiontoHTCondorVersions.html": "../version-history/introduction-version-history.html",
    "Upgradingfromthe86seriestothe88seriesofHTCondor.html": "../version-history/upgrading-from-86-to-88-series.html",
    "DevelopmentReleaseSeries89.html": "../version-history/development-release-series-89.html",
    "StableReleaseSeries88.html": "../version-history/stable-release-series-88.html",
    "DevelopmentReleaseSeries87.html": "../version-history/development-release-series-87.html",
    "StableReleaseSeries86.html": "../version-history/stable-release-series-86.html",

    # Command Reference Manual (man-pages)
    "CommandReferenceManualmanpages.html": "../man-pages/index.html",
    "Boscocluster.html": "../man-pages/bosco_cluster.html",
    "Boscofindplatform.html": "../man-pages/bosco_findplatform.html",
    "Boscoinstall.html": "../man-pages/bosco_install.html",
    "Boscosshstart.html": "../man-pages/bosco_sshstart.html",
    "Boscostart.html": "../man-pages/bosco_start.html",
    "Boscostop.html": "../man-pages/bosco_stop.html",
    "Boscouninstall.html": "../man-pages/bosco_uninstall.html",
    "Condoradvertise.html": "../man-pages/condor_advertise.html",
    "Condorannex.html": "../man-pages/condor_annex.html",
    "Condorcheckpoint.html": "../man-pages/condor_checkpoint.html",
    "Condorcheckuserlogs.html": "../man-pages/condor_check_userlogs.html",
    "Condorchirp.html": "../man-pages/condor_chirp.html",
    "Condorcod.html": "../man-pages/condor_cod.html",
    "Condorcompile.html": "../man-pages/condor_compile.html",
    "Condorconfigure.html": "../man-pages/condor_configure.html",
    "Condorconfigval.html": "../man-pages/condor_config_val.html",
    "Condorcontinue.html": "../man-pages/condor_continue.html",
    "Condorconverthistory.html": "../man-pages/condor_convert_history.html",
    "Condordagman.html": "../man-pages/condor_dagman.html",
    "Condordagmanmetricsreporter.html": "../man-pages/condor_dagman_metrics_reporter.html",
    "Condordrain.html": "../man-pages/condor_drain.html",
    "Condorfetchlog.html": "../man-pages/condor_fetchlog.html",
    "Condorfindhost.html": "../man-pages/condor_findhost.html",
    "Condorgatherinfo.html": "../man-pages/condor_gather_info.html",
    "Condorgpudiscovery.html": "../man-pages/condor_gpu_discovery.html",
    "Condorhistory.html": "../man-pages/condor_history.html",
    "Condorhold.html": "../man-pages/condor_hold.html",
    "Condorinstall.html": "../man-pages/condor_install.html",
    "Condorjobrouterinfo.html": "../man-pages/condor_job_router_info.html",
    "Condormaster.html": "../man-pages/condor_master.html",
    "Condornow.html": "../man-pages/condor_now.html",
    "Condoroff.html": "../man-pages/condor_off.html",
    "Condoron.html": "../man-pages/condor_on.html",
    "Condorping.html": "../man-pages/condor_ping.html",
    "Condorpooljobreport.html": "../man-pages/condor_pool_job_report.html",
    "Condorpower.html": "../man-pages/condor_power.html",
    "Condorpreen.html": "../man-pages/condor_preen.html",
    "Condorprio.html": "../man-pages/condor_prio.html",
    "Condorprocd.html": "../man-pages/condor_procd.html",
    "Condorqedit.html": "../man-pages/condor_qedit.html",
    "Condorq.html": "../man-pages/condor_q.html",
    "Condorqsub.html": "../man-pages/condor_qsub.html",
    "Condorreconfig.html": "../man-pages/condor_reconfig.html",
    "Condorrelease.html": "../man-pages/condor_release.html",
    "Condorreschedule.html": "../man-pages/condor_reschedule.html",
    "Condorrestart.html": "../man-pages/condor_restart.html",
    "Condorrmdir.html": "../man-pages/condor_rmdir.html",
    "Condorrm.html": "../man-pages/condor_rm.html",
    "Progcondorrouterhistory.html": "../man-pages/condor_router_history.html",
    "Progcondorrouterq.html": "../man-pages/condor_router_q.html",
    "Condorrouterrm.html": "../man-pages/condor_router_rm.html",
    "Condorrun.html": "../man-pages/condor_run.html",
    "Condorsetshutdown.html": "../man-pages/condor_set_shutdown.html",
    "Condorsos.html": "../man-pages/condor_sos.html",
    "Condorsshtojob.html": "../man-pages/condor_sshtojob.html",
    "Condorstats.html": "../man-pages/condor_stats.html",
    "Condorstatus.html": "../man-pages/condor_status.html",
    "Condorstorecred.html": "../man-pages/condor_storecred.html",
    "Condorsubmitdag.html": "../man-pages/condor_submitdag.html",
    "Condorsubmit.html": "../man-pages/condor_submit.html",
    "Condorsuspend.html": "../man-pages/condor_suspend.html",
    "Condortail.html": "../man-pages/condor_tail.html",
    "Condortop.html": "../man-pages/condor_top.html",
    "Condortransferdata.html": "../man-pages/condor_transfer_data.html",
    "Condortransformads.html": "../man-pages/condor_transform_ads.html",
    "Condorupdatemachinead.html": "../man-pages/condor_update_machine_ad.html",
    "Condorupdatesstats.html": "../man-pages/condor_updates_stats.html",
    "Condorurlfetch.html": "../man-pages/condor_urlfetch.html",
    "Condoruserlog.html": "../man-pages/condor_userlog.html",
    "Condoruserprio.html": "../man-pages/condor_userprio.html",
    "Condorvacate.html": "../man-pages/condor_vacate.html",
    "Condorvacatejob.html": "../man-pages/condor_vacate_job.html",
    "Condorversion.html": "../man-pages/condor_version.html",
    "Condorwait.html": "../man-pages/condor_wait.html",
    "Condorwho.html": "../man-pages/condor_who.html",
    "giddalloc.html": "../man-pages/giddalloc.html",
    "procdctl.html": "../man-pages/procdctl.html",

    # ClassAd Attributes
    "ClassAdAttributes.html": "../classad-attributes/index.html",
    "ClassAdTypes.html": "../classad-attributes/classad-types.html",
    "JobClassAdAttributes.html": "../classad-attributes/job-classad-attributes.html",
    "MachineClassAdAttributes.html": "../classad-attributes/machine-classad-attributes.html",
    "DaemonMasterClassAdAttributes.html": "../classad-attributes/daemon-master-classad-attributes.html",
    "SchedulerClassAdAttributes.html": "../classad-attributes/scheduler-classad-attributes.html",
    "NegotiatorClassAdAttributes.html": "../classad-attributes/negotiator-classad-attributes.html",
    "SubmitterClassAdAttributes.html": "../classad-attributes/submitter-classad-attributes.html",
    "DefragClassAdAttributes.html": "../classad-attributes/defrag-classad-attributes.html",
    "CollectorClassAdAttributes.html": "../classad-attributes/collector-classad-attributes.html",
    "ClassAdAttributesAddedbytheCondorcollector.html": "../classad-attributes/classad-attributes-added-by-collector.html",
    "DaemonCoreStatisticsAttributes.html": "../classad-attributes/daemon-core-statistics-attributes.html",

    # Codes and Other Needed Values
    "CodesandOtherNeededValues.html": "../codes-other-values/index.html",
    "CondorshadowExitCodes.html": "../man-pages/condor_shadow-exit-codes.html",
    "JobEventLogCodes.html": "../codes-other-values/job-event-log-codes.html",
    "WellknownPortNumbers.html": "../codes-other-values/well-known-port-numbers.html",
    "DaemonCoreCommandNumbers.html": "../codes-other-values/daemoncore-command-numbers.html",
    "DaemonCoreDaemonExitCodes.html": "../codes-other-values/daemoncore-daemon-exit-codes.html",

}

