#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;
use CondorCmdStatusWorker2;
use strict;
use warnings;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

my $testdesc =  'cmd_status_shows-slots';
my $testname = "cmd_status_shows-slots";
my $debuglevel = 2;

print scalar localtime() . "\n";

my $mypid = $$;

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

CondorTest::debug("Master PID is $mypid\n",$debuglevel);

my $outsource = CondorCmdStatusWorker2::SetUp("cmd_status_shows-slots");
CondorUtils::fullchomp($outsource);

if($outsource eq "") {
    # assume all cleanup of personals which did start occurred in worker
    print "OOOOPPPPSSSSSSSSSSSSyyyyy\n";
    exit(1);
}

( my $locconfig, my $scheddoneconfig) = split('&',$outsource);
CondorTest::debug("Two pools are $locconfig and $scheddoneconfig\n",$debuglevel);

my $done = 0;
my $stable = CondorCmdStatusWorker2::IsSystemStable();
my @adarray; 
my $numstartd = 0;

if($stable == 1) {
	# allow time for all the nodes to update the collector
	# by allowing N attempts
	# with  6 slots configured we should find 6 unique startds
	my $nattempts = 8;
	my $count = 0;

	print "Looking for 6 slots condor_status ... - ";
	while($count < $nattempts) {
		my $cmd = "condor_status -af name";
		CondorTest::debug("Looking for exactly 6 slots\n",$debuglevel);
		my $cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);
    	if(!$cmdstatus)
    	{
        	CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
			RegisterResult(0,"test_name", "$testname");
			#CondorTest::EndTest();
        	#exit(1)
			last;
    	}
	
		# better be 6
	
		$numstartd = 0;
		foreach my $line (@adarray) {
			if($line =~ /^\s*slot(\d+)[@]master_(.*)$/) {
				#print "found startd slot: $line\n";
				$numstartd = $numstartd + 1;;
				CondorTest::debug("found startd slot: $numstartd of 9\n",$debuglevel);
			} else {
				#print "skip: $line\n";
			}
		}

		if($numstartd == 6) {
			CondorTest::debug("Condor_status found the expected 6 slots\n",$debuglevel);
			print "ok\n";
			$done = 1;
			last;
		} else {
			CondorTest::debug("Condor_status found incorrect startd slot count<$numstartd>\n",$debuglevel);
		}

		$count = $count + 1;
		sleep($count * 5);
	}
}
my $test_ok = 1;
if($done == 0) {
	print "did not see expected number of slots\n";
	$test_ok = 0;
}


CondorTest::debug("Saving things and cleaning up....\n",$debuglevel);

#fails due to directory that matches symbol

my $res = 1;
my @rm1 = ();
my @rm2 = ();
$ENV{CONDOR_CONFIG} = $locconfig;
$res = runCondorTool("condor_rm -all",\@rm1,2,{emit_output=>0});
$ENV{CONDOR_CONFIG} = $scheddoneconfig;
$res = runCondorTool("condor_rm -all",\@rm2,2,{emit_output=>0});

RegisterResult($test_ok,"test_name", "$testname");
CondorTest::EndTest();
print scalar localtime() . "\n";

if( $done == 0 )
{
	# actual test failed but we allowed cleanup
	exit(1);
}

CondorTest::debug("cmd_status_shows-slots SUCCESS\n",$debuglevel);
exit(0);
