#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;
use CondorCmdStatusWorker2;
use strict;
use warnings;


# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

my $testdesc =  'cmd_status_shows-avail';
my $testname = "cmd_status_shows-avail";
my $corename = "cmd_status_shows-avail";
my $debuglevel = 2;

# where am I running

print scalar localtime() . "\n";

my $mypid = $$;
my $mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

my $mysubmitnm = $corename . $mypid . ".cmd";
my $mysubmitnmlog = $corename . $mypid . ".log";
my $mysubmitnmout = $corename . $mypid . ".out";
my $mycorenm = $corename . ".cmd";
my $mycorenmout = $corename . ".cmd.out";
my $mycorenmlog = $corename . ".log";

CondorTest::debug("Master PID is $mypid\n",$debuglevel);
CondorTest::debug("Master PID submit file is $mysubmitnm\n",$debuglevel);

my $outsource = CondorCmdStatusWorker2::SetUp("cmd_status_shows-avail");
CondorUtils::fullchomp($outsource);

if($outsource eq "") {
    # assume all cleanup of personals which did start occurred in worker
    print "OOOOPPPPSSSSSSSSSSSSyyyyy\n";
    exit(1);
}

( my $locconfig, my $scheddoneconfig) = split('&',$outsource);
CondorTest::debug("Two pools are $locconfig and $scheddoneconfig\n",$debuglevel);
 
my $stable = CondorCmdStatusWorker2::IsSystemStable();
my $done = 0;

if($stable == 1) {
	# allow time for all the nodes to update the collector
	# by allowing N attempts
	# with 4 run forever jobs we are not stable until -avail finds exactly 5
	my $nattempts = 8;
	my $count = 0;
	my @adarray;

	print "Looking for at least 2 available slots - ";
	while($count < $nattempts) {
		my $cmd = "condor_status -avail";
		CondorTest::debug("Looking for exactly 2 available slots\n",$debuglevel);
		my $cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);
    	if(!$cmdstatus)
    	{
        	CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
			CondorTest::KillPersonal($locconfig);
			CondorTest::KillPersonal($scheddoneconfig);
        	exit(1)
    	}
	
		# 4 are busy so 2 should be available....
		# nah sometimes more are available.
	
		my $numavail = 0;
		foreach my $line (@adarray) {
			if($line =~ /^\s*Total.*Unclaimed.*$/) {
				#print "skip: $line\n";
			} elsif($line =~ /^.*Unclaimed.*$/) {
				#print "found available slot: $line\n";
				$numavail = $numavail + 1;;
				CondorTest::debug("found available slot: $numavail of 5\n",$debuglevel);
			} else {
				#print "skip: $line\n";
			}
		}

		if($numavail >= 2) {
			print "ok\n";
			CondorTest::debug("Condor_status -avail found the expected 2 slots\n",$debuglevel);
			$done = 1;
			last;
		} else {
			CondorTest::debug("Condor_status -avail found < 2 available slot count<$numavail>\n",$debuglevel);
		}

		$count = $count + 1;
		sleep($count * 2);
	}
}
if($done == 0) {
	print "bad\n";
}


CondorTest::debug("Saving things and cleaning up....\n",$debuglevel);

#fails due to finding the directory of same name...
runcmd("cp *cmd_status_shows-avail* $mysaveme", {expect_result=>\&ANY});

if( -e "$mysubmitnm" )
{
	runcmd("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	runcmd("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	runcmd("cp $mysubmitnmlog $mycorenmlog");
}

CondorTest::KillPersonal($locconfig);
CondorTest::KillPersonal($scheddoneconfig);
print scalar localtime() . "\n";

if( $done == 0 )
{
	# actual test failed but we allowed cleanup
	exit(1);
}

CondorTest::debug("cmd_q_shows-avail SUCCESS\n",$debuglevel);
exit(0);
