#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use strict;
use warnings;

my $cmd = 'cmd_q_shows-format.cmd';
my $cmdout = $cmd . ".out";
my $testdesc =  'cmd_q_shows-format  ';
my $testname = "cmd_q_shows-format";
my $debuglevel = 2;

my $whoami = "";

my @adarray;

my $submit = sub {
	my %info = @_;
	my $cmd = "condor_q -format \"%s\" Owner -format \" ClusterId = %d\n\" ClusterId";

	print "Running cmd $cmd - ";
	my $cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);
	if(!$cmdstatus)
	{
		print "bad\n";
		CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
		exit(1)
	}
	print "ok\n";
	my $submitline = "";
	my $cluster = "";

	print "Looking for cluster - ";
	open(CMD, "<$cmdout") || die "Can not find submit output:$!\n";;
	while(<CMD>) {
		chomp($_);
		$submitline = $_;
		CondorTest::debug("Scraping cluster from submit file\n",$debuglevel);
		CondorTest::debug("hmmmm<$submitline>\n",$debuglevel);
		if($submitline =~ /^.*cluster\s+(\d+).*$/) {
			$cluster = $1;
			CondorTest::debug("Found my cluster which is $cluster!\n",$debuglevel);
		}
	}

	print "$cluster\n";

	$cmd = "condor_rm $cluster";

	print "Looking for owner of cluster - ";
	foreach my $line (@adarray) {
		chomp($line);
		CondorTest::debug("$line\n",$debuglevel);
		if($line =~ /^\s*([\w\-]+)\s+ClusterId\s+=\s+$cluster.*$/) {
				CondorTest::debug("Bingo: found <$line> shows I am $1\n",$debuglevel);
				$cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,8);
				print "ok\n";
				return(0);
		} else {
			CondorTest::debug("<<<$line>>>\n",$debuglevel);
		}
	}

	print "bad\n";
	$cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,8);
	exit(1);
};

my $aborted = sub {
	CondorTest::debug("If all is good we abort our own job.......\n",$debuglevel);
};

my $ExitSuccess = sub {
	my %info = @_;
};

CondorTest::RegisterAbort($testname, $aborted);
CondorTest::RegisterSubmit($testname, $submit);
CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",$debuglevel);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}


