#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorCmdStatusWorker;
use strict;
use warnings;

my $testdesc =  'cmd_status_shows-schedd';
my $testname = "cmd_status_shows-schedd";
my $corename = "cmd_status_shows-schedd";
my $bail = 0;
my $debuglevel = 2;

# where am I running
my $currenthost = CondorTest::getFqdnHost();
chomp($currenthost);
my @adarray;

CondorTest::fullchomp($currenthost);

print scalar localtime() . "\n";

my $mypid = $$;
my $mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

my $mysubmitnm = $corename . $mypid . ".cmd";
my $mysubmitnmlog = $corename . $mypid . ".log";
my $mysubmitnmout = $corename . $mypid . ".out";
my $mycorenm = $corename . ".cmd";
my $mycorenmout = $corename . ".cmd.out";
my $mycorenmlog = $corename . ".log";

CondorTest::debug("Master PID is $mypid\n",$debuglevel);
CondorTest::debug("Master PID submit file is $mysubmitnm\n",$debuglevel);

my $outsource = CondorCmdStatusWorker::SetUp("cmd_status_shows-schedd");
CondorTest::fullchomp($outsource);

if($outsource eq "") {
	# assume all cleanup of personals which did start occurred in worker
	print "OOOOPPPPSSSSSSSSSSSSyyyyy\n";
	exit(1);
}

( my $locconfig, my $scheddoneconfig) = split('&',$outsource);
CondorTest::debug("Two pools are $locconfig and $scheddoneconfig\n",$debuglevel);

my $cmdstatus;
my $sched1 = "master_" . $mypid . "local" . "@" . $currenthost;;
my $sched2 = "master_" . $mypid . "scheddone" . "@" . $currenthost;;

#Place condor_q back into the original condor config
#and aim the -global -pool command at this new collector.
#$ENV{CONDOR_CONFIG} = $saveconfig;
$ENV{CONDOR_CONFIG} = $scheddoneconfig;

#print "Lets look at status from second pool....\n";
#system("condor_status");

# allow time for all the nodes to update the collector
# by allowing N attempts
my $nattempts = 8;
my $count = 0;
my $done = 0;
my $found1 = 0;
my $cmd = "";

my $numschedd = 0;

if($bail == 0) {
	print "Looking for both schedds - ";
	# allow time for all the nodes to update the collector
	# by allowing N attempts
	$nattempts = 8;
	$count = 0;
	$done = 0;

	while($count < $nattempts) {
		$cmd = "condor_status -schedd -format \"%s\\n\" name";
		CondorTest::debug("Looking for exactly 2 schedds\n",$debuglevel);
		$cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);
    	if(!$cmdstatus)
    	{
			print "bad\n";
        	CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
			CondorTest::KillPersonal($locconfig);
			CondorTest::KillPersonal($scheddoneconfig);
        	exit(1)
    	}
	
		#  we are running a local and a remote schedd, should be two
	
		$numschedd = 0;
		foreach my $line (@adarray) {
			if($line =~ /^\s*master_(.*)_schd.*$/) {
				CondorTest::debug("found schedd:($1) $line\n",$debuglevel);
				$numschedd = $numschedd + 1;;
				CondorTest::debug("found schedd: $numschedd of 2\n",$debuglevel);
			} else {
				#print "skip: $line\n";
			}
		}

		if($numschedd == 2) {
			CondorTest::debug("Condor_status -schedd found the expected 2 schedds\n",$debuglevel);
			print "ok\n";
			$done = 1;
			last;
		} else {
			CondorTest::debug("Condor_status -schedd found incorrect schedd count<$numschedd>((2))\n",$debuglevel);
		}

		$count = $count + 1;
		sleep($count * 5);
	}
} else {
	print "bad\n";
}

if($done != 1) {
	print "bad\n";
}



CondorTest::debug("Saving things and cleaning up....\n",$debuglevel);

system("cp *cmd_status_shows-schedd* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

CondorTest::KillPersonal($locconfig);
CondorTest::KillPersonal($scheddoneconfig);
print scalar localtime() . "\n";

if( $done == 0 )
{
	# actual test failed but we allowed cleanup
	exit(1);
}

CondorTest::debug("cmd_status_shows-schedd SUCCESS\n",$debuglevel);
exit(0);
