#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use strict;
use warnings;

my $cmd = 'cmd_q_shows-analyze.cmd';
my $cmdout = $cmd . ".out";
my $testdesc =  'cmd_q_shows-analyze  ';
my $testname = "cmd_q_shows-analyze";
my $debuglevel = 2;

my $whoami = `whoami`;
chomp($whoami);

my @adarray;

my $submit = sub {
	my %info = @_;

	my $foundcluster = 0;
	my $foundanalyze = 0;
	my $foundnegotiator = 0;
	my $cmd = "";
	my $timecollector = 0;
	my $maxwait = 600;
	my $interval = 30;

	# This is the first test run, so we need to make sure that
	# the negotiator has reported to the collector.  If it started
	# before the collector was ready, it takes five minutes
	# for it to show up in the collector.

	#Condor::DebugOn();

	$cmd = "condor_status -negotiator";

	print "Do we have a negotiator yet - ";
	while($timecollector < $maxwait) {
		my $cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);
		CondorTest::debug("runCondorTool returned <<$cmdstatus>>\n",$debuglevel);
		if(!$cmdstatus)
		{
			CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
			exit(1);
		}
		foreach my $line (@adarray) {
			chomp($line);
			CondorTest::debug("Examing line $line\n",$debuglevel);
			if($line =~ /^\s*(\w+).*\s*(\w+)\s*.*$/) {
				CondorTest::debug("Score!!!!! something for a negotiator <<$1/$2>>\n",$debuglevel);
				$foundnegotiator = 1;
				last;
			}
		}
		if($foundnegotiator == 1) {
			last;
		} else {
			sleep($interval);
		}
		$timecollector = $timecollector + $interval;
	}

	if($timecollector == $maxwait) {
		print "bad\n";
		die "Failed to ever find a usable negotiator!!!!\n";
	}
	print "ok\n";

	print "Does condor_q -analyze run - ";
	$cmd = "condor_q -analyze";

	my $cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);
	CondorTest::debug("runCondorTool returned <<$cmdstatus>>\n",$debuglevel);
	if(!$cmdstatus)
	{
		print "bad\n";
		CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
		system("ps auxww | grep negotiator");
		CondorTest::debug("NegotiatorLog:--------------------------------\n",$debuglevel);
		system("cat `condor_config_val LOG`/NegotiatorLog");
		CondorTest::debug("condor_status -any -l:--------------------------------\n",$debuglevel);
		system("condor_status -any -l");
		exit(1);
	}

	print "ok\n";
	my $submitline = "";
	my $cluster = -1;

	print "Looking for cluster - ";
	open(CMD, "<$cmdout") || die "Can not find analyze output:$!\n";;
	while(<CMD>) {
		chomp($_);
		$submitline = $_;
		if($submitline =~ /^.*cluster\s+(\d+).*$/) {
			$cluster = $1;
			CondorTest::debug("Found my cluster which is $cluster!\n",$debuglevel);
		}
		CondorTest::debug("$_\n",$debuglevel);
	}

	if ($cluster == -1) {
		print "bad\n";
		die("Can not find a cluster in $cmdout\n");	
	}
	print "$cluster\n";

	print "Checking cluster and other output - ";
	foreach my $line (@adarray) {
		chomp($line);
		CondorTest::debug("Examing line $line\n",$debuglevel);
		if($line =~ /^\s*(\d+)\.(\d+):\s*Run\s+analysis\s+summary\.\s+.*$/) {
			CondorTest::debug("Score!!!!! found cluster $1\n",$debuglevel);
			CondorTest::debug("$line\n",$debuglevel);
			$foundcluster = 1;
		}
		if($line =~ /^\s*Requirements\s+=\s+.*$/) {
			CondorTest::debug("Score!!!!! found -analyze\n",$debuglevel);
			CondorTest::debug("$line\n",$debuglevel);
			CondorTest::debug("condor_q -analyse prints Requirements like this\n",$debuglevel);
			$foundanalyze = 1;
		}
	}

	$cmd = "condor_rm $cluster";
	$cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);

	if(($foundcluster) && ($foundanalyze)) {
		print "ok\n";
		CondorTest::debug("Found analyze output\n",$debuglevel);
	} else {
		print "bad\n";
		die("Could not parse condor_q -analyze output\n");
	}
};

my $aborted = sub {
	CondorTest::debug("If all is good we abort our own job.......\n",$debuglevel);
};

my $ExitSuccess = sub {
	my %info = @_;
};

CondorTest::RegisterSubmit( $testname, $submit );
CondorTest::RegisterAbort($testname, $aborted);
CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",$debuglevel);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

