#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;
use CondorCmdStatusWorker2;
use strict;
use warnings;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

my $testname = "cmd_status_shows-constraint";
my $debuglevel = 2;

print scalar localtime() . "\n";

my $mypid = $$;

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

CondorTest::debug("Master PID is $mypid\n",$debuglevel);

my $outsource = CondorCmdStatusWorker2::SetUp("cmd_status_shows-constraint");
CondorUtils::fullchomp($outsource);

if($outsource eq "") {
    # assume all cleanup of personals which did start occurred in worker
    print "OOOOPPPPSSSSSSSSSSSSyyyyy\n";
    exit(1);
}

( my $locconfig, my $scheddoneconfig) = split('&',$outsource);
CondorTest::debug("Two pools are $locconfig and $scheddoneconfig\n",$debuglevel);

my $done = 0;
my $stable = CondorCmdStatusWorker2::IsSystemStable();
my @adarray = (); 
my $numidle = 0;

if($stable == 1) {
	# allow time for all the nodes to update the collector
	# by allowing N attempts
	my $nattempts = 8;
	my $count = 0;

	print "Using condor_status -constraint Activity=='Idle' to find\n";
	print "at least 2 Idle slots - ";
	while($count < $nattempts) {
		my $cmd = "condor_status -constraint Activity==\\\"Idle\\\"";
		my $cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);
    	if(!$cmdstatus)
    	{
        	CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
			$done = 0;
			last;
    	}
	
		CondorTest::debug("Looking for at least 2 idle slots\n",$debuglevel);
		$numidle = 0;
		foreach my $line (@adarray) {
			if($line =~ /^\s*slot\d+.*Idle.*\s*$/) {
				CondorTest::debug("found Idle: $line\n",$debuglevel);
				$numidle = $numidle + 1;;
			} else {
				#print "skip: $line\n";
			}
		}

		# with more tests running we can not assume all 4 jobs
		# we started are still running so idle can be more then 2 12/15/08
		if($numidle >= 2) {
			$done = 1;
			last;
		}

		$count = $count + 1;
		sleep($count * 5);
	}
}


if($done == 1) {
	print "ok\n";
} else {
	print "bad\n";
}


CondorTest::debug("Saving things and cleaning up....\n",$debuglevel);

#fails due to directory that matches symbol

my $res = 1;
my @rm1 = ();
my @rm2 = ();
$ENV{CONDOR_CONFIG} = $locconfig;
$res = runCondorTool("condor_rm -all",\@rm1,2,{emit_output=>0});
$ENV{CONDOR_CONFIG} = $scheddoneconfig;
$res = runCondorTool("condor_rm -all",\@rm2,2,{emit_output=>0});

print scalar localtime() . "\n";

if( $done == 0 )
{
	# actual test failed but we allowed cleanup
	RegisterResult(0,"test_name", "$testname");
	CondorTest::EndTest();
	exit(1);
} else {
	RegisterResult(1,"test_name", "$testname");
	CondorTest::EndTest();
	CondorTest::debug("cmd_status_shows-constraint SUCCESS\n",$debuglevel);
}
exit(0);
