#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Cwd;
#use Time::localtime;

$cmd = "cmd_wait_shows.cmd";

my $pid = $$;
system("rm -rf $pid");
system("mkdir $pid");
my $curcwd = getcwd();
print "current directory is $curcwd\n";

my $socketname = "cmd_wait";
my $resultfile = $curcwd . "/" . $pid . "/results";
my $flowlog = $curcwd . "/" . $pid . "/cmd_wait_shows.log";
my $writelog = "./x_write_joblog_events.exe";

print "Result File is $resultfile\n";

system("chmod -R 777 .");

####################################################################
####################################################################
#
# Base operation of having one cluster in the userlog
# and telling condor_wait to wait. Then post execute
# and terminated events and expect a happy result.
#
####################################################################
####################################################################

# seed log with 1 runs
system("$writelog $flowlog submit 1");

my $count = 0;
while(!(-f $flowlog)) {
	print "<<$flowlog>> should have been here by now....\n";
	$count += 1;
	if($count > 20) {
		system("ls -lR $pid");
		die "Flowlog should have existed by now\n";
	}
	sleep(1);
}

print "About to spawn condor_wait -wait 30\n";
system("date");

# Start condor_wait
$spawncmd = "condor_wait -wait 30 $flowlog";
CondorTest::spawn_cmd($spawncmd, $resultfile);

print "Back from spawn condor_wait -wait 30\n";
system("date");

sleep(5);

print "Slept 5, about to drop execute event\n";
system("date");

# start 1 runs
system("$writelog $flowlog execute 1");

print "droped execute event, about to drop terminated event\n";
system("date");

# end 1 runs
system("$writelog $flowlog terminated 1");

print "droped terminate event, about to check results\n";
system("date");

while(!(-f $resultfile)) {
	print "Waiting for $resultfile to exist\n";
	sleep(2);
}

print "$resultfile exits!\n";

while( (-s $resultfile) == 0 ) {
	print "Waiting for results\n";
	sleep(2);
}

print "$resultfile not empty!\n";

open(RES,"<$resultfile") || die "Can not open <$resultfile>:$!\n";
$line = "";
while(<RES>) {
	$line = $_;
	print "RESULTS: $line\n";
	if($line =~ /^Exit\s+(\d+)\s+Signal\s+\d+$/) {
		if($1 == 0) {
			print "Exit status of 0, expected. Good!\n";
			exit(0);
		} else {
			print "Exit status of non-0, not expected. ERROR!\n";
			exit(1);
		}
	} else {
			print "This was an unexpected result. ERROR\n";
			exit(1);
	}
}
