#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorCmdStatusWorker;
use strict;
use warnings;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

my $testdesc =  'cmd_status_shows-format';
my $testname = "cmd_status_shows-format";
my $corename = "cmd_status_shows-format";
my $debuglevel = 2;

print scalar localtime() . "\n";

my $mypid = $$;
my $mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

my $mysubmitnm = $corename . $mypid . ".cmd";
my $mysubmitnmlog = $corename . $mypid . ".log";
my $mysubmitnmout = $corename . $mypid . ".out";
my $mycorenm = $corename . ".cmd";
my $mycorenmout = $corename . ".cmd.out";
my $mycorenmlog = $corename . ".log";

CondorTest::debug("Master PID is $mypid\n",$debuglevel);
CondorTest::debug("Master PID submit file is $mysubmitnm\n",$debuglevel);

my $outsource = CondorCmdStatusWorker::SetUp("cmd_status_shows-format");
CondorTest::fullchomp($outsource);

if($outsource eq "") {
	# assume all cleanup of personals which did start occurred in worker
	print "OOOOPPPPSSSSSSSSSSSSyyyyy\n";
	exit(1);
}

( my $locconfig, my $scheddoneconfig) = split('&',$outsource);
CondorTest::debug("Two pools are $locconfig and $scheddoneconfig\n",$debuglevel);

my $done = 0;
my $stable = CondorCmdStatusWorker::IsSystemStable();
my $numformated = 0;
my @adarray;

if($stable == 1) {
	# allow time for all the nodes to update the collector
	# by allowing N attempts
	my $nattempts = 8;
	my $count = 0;

	print "Looking for 6 lines from condor_status -format .... - ";
	while($count < $nattempts) {
		my $cmd = "condor_status -format \"%s \" Activity -format \"%d \" Memory -format \"%f\\n\" LoadAvg";
		my $cmdstatus = CondorTest::runCondorTool($cmd,\@adarray,2);
    	if(!$cmdstatus)
    	{
        	CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
			CondorTest::KillPersonal($locconfig);
			CondorTest::KillPersonal($scheddoneconfig);
        	exit(1)
    	}
	
		CondorTest::debug("Looking for exactly 6 formatted lines\n",$debuglevel);
		$numformated = 0;
		foreach my $line (@adarray) {
			if($line =~ /^\s*(\w+)\s*(\d+)\s*(\d+\.\d+).*\s*$/) {
				CondorTest::debug("found Idle: $line\n",$debuglevel);
				$numformated = $numformated + 1;;
			} else {
				#print "skip: $line\n";
			}
		}

		if($numformated == 6) {
			print "ok\n";
			$done = 1;
			last;
		}

		$count = $count + 1;
		sleep($count * 2);
	}
}
if($done == 0) {
	print "bad\n";
}

CondorTest::debug("Saving things and cleaning up....\n",$debuglevel);

system("cp *cmd_status_shows-format* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

CondorTest::KillPersonal($locconfig);
CondorTest::KillPersonal($scheddoneconfig);
print scalar localtime() . "\n";

if( $done == 0 )
{
	# actual test failed but we allowed cleanup
	exit(1);
}

CondorTest::debug("cmd_status_shows-format SUCCESS\n",$debuglevel);
exit(0);
