#!/usr/bin/env python

import os
import sys

from pytest.CondorJob import CondorJob
from pytest.CondorTest import CondorTest
from pytest.Globals import *
from pytest.HTTPServer import HTTPServer
from pytest.PersonalCondor import PersonalCondor
from pytest.Utils import Utils


def SuccessCallback():
    Utils.TLog("Job successful as expected. Test passed.")
    sys.exit(TEST_SUCCESS)

def FailureCallback():
    Utils.TLog("Job failed unexpectedly. Test failed.")
    sys.exit(TEST_FAILURE)

def HttpSuccessUrlHandler(request):
    request.protocol_version = "HTTP/1.1"
    request.send_response(200)
    request.send_header("Content-type", "text/html")
    request.end_headers()
    request.wfile.write("<html>Great success!</html>")


def main():

    # Create a new test environment
    test = CondorTest("cmd_curl_plugin_singlefile_success")

    # Start a HTTP server, and register the /success URL to return a 
    httpd = HTTPServer()
    httpd.Start()
    httpd.RegisterUrlHandler("/success", HttpSuccessUrlHandler)
    success_url = "http://127.0.0.1:" + str(httpd._port) + "/success"

    # Stand up a PersonalCondor
    personal_handle = test.StartPersonalCondor()
    if personal_handle == -1:
        Utils.TLog("Failed to start the PersonalCondor environment. Exiting.")
        sys.exit(1)
    else:
        Utils.TLog("PersonalCondor environment started successfully with handle " + str(personal_handle))

    # Setup a new test job
    job_args = {
        "executable":               "cmd_curl_plugin_singlefile_success.py",
        "output":                   "cmd_curl_plugin_singlefile_success.out",
        "transfer_input_files":     success_url,
        "should_transfer_files":    "YES"
    }
    test_job = CondorJob(job_args)

    # Register job handlers
    test_job.RegisterJobTerminated(SuccessCallback)
    test_job.RegisterJobHeld(FailureCallback)

    # Submit the test job
    test_job.Submit()
    result = test_job.WaitUntilJobTerminated()
    Utils.TLog("Job returned result: " + str(result))

    # The success/failure callbacks handle the sys.exit() calls
    # All our testing infrastructure will shut down via destructors
    # Nothing left to do at this point.



if __name__ == "__main__":
    main()
