#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Cwd;
#use Time::localtime;
use strict;
use warnings;

my $cmd = "cmd_wait_shows.cmd";
my $debuglevel = 2;

my $pid = $$;
system("rm -rf $pid");
system("mkdir $pid");
my $curcwd = getcwd();
CondorTest::debug("current directory is $curcwd\n",$debuglevel);

my $socketname = "cmd_wait";
my $resultfile = $curcwd . "/" . $pid . "/results";
my $outputfile = $curcwd . "/" . $pid . "/condor_wait.out";
CondorTest::debug("condor_wait output is in $outputfile\n",$debuglevel);

my $flowlog = $curcwd . "/" . $pid . "/cmd_wait_shows-partial.log";
my $writelog = "./x_write_joblog_events.exe";

CondorTest::debug("Result File is $resultfile\n",$debuglevel);

system("chmod -R 777 .");

####################################################################
####################################################################
#
# Base operation of having one cluster in the userlog
# and telling condor_wait to wait. Then post execute
# and terminated events and expect a happy result.
#
####################################################################
####################################################################

# seed log with 1 runs
system("$writelog $flowlog submit 4");
print "Drop 4 submits into the log\n";

# Start condor_wait
my $spawncmd = "_CONDOR_TOOL_DEBUG=D_FULLDEBUG condor_wait -debug -num 2 $flowlog >$outputfile 2>&1";
#my $spawncmd = "condor_wait -num 2 $flowlog";
CondorTest::spawn_cmd($spawncmd, $resultfile);
print "Have condor_wait wait for 2\n";

sleep(5);
# start 1 runs
system("$writelog $flowlog execute 2");

# end 1 runs
system("$writelog $flowlog terminated 2");
print "Add log entries to complete 2 jobs\n";

print "Wait for results - ";
while(!(-f $resultfile)) {
	CondorTest::debug("Waiting for $resultfile to exist\n",$debuglevel);
	sleep(2);
}

CondorTest::debug("$resultfile exits!\n",$debuglevel);

my $waitmax = 14;
my $waittime = 0;
my $inc = 2;

while( (-s $resultfile) == 0 ) {
	CondorTest::debug("Waiting for results\n",$debuglevel);
	$waittime = $waittime + $inc;
	if($waittime >= $waitmax) {
		die "Waited $waitmax seconds when 2 jobs are already done\n";
	}
	sleep($inc);
}

CondorTest::debug("$resultfile not empty!\n",$debuglevel);
print "ok\n";

print "Checking result status - ";
open(RES,"<$resultfile") || die "Can not open <$resultfile>:$!\n";
my $line = "";
while(<RES>) {
	$line = $_;
	if($line =~ /^Exit\s+(\d+).*$/) {
		if($1 == 0) {
			CondorTest::debug("Exit status of 0, expected. Good!\n",$debuglevel);
			print "ok\n";
			exit(0);
		} else {
			print "bad\n";
			exit(1);
		}
	} else {
			print "bad\n";
			exit(1);
	}
}
