#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use Cwd;
use File::Copy;
use CondorTest;
use Check::CondorLog;

my $cwd = getcwd();
my $configd = $cwd . '/x_ganglia_d';
if( ! -d $configd ) {
    mkdir $configd or die "Failed to create $configd";
}
copy("../gangliad/ganglia_default_metrics",$configd . "/ganglia_default_metrics") or die "Failed to copy ganglia_default_metrics";

my $append_condor_config = '
  DAEMON_LIST = MASTER,SCHEDD,COLLECTOR,NEGOTIATOR,STARTD,GANGLIAD

  GANGLIA_CONFIG = ' . $cwd . '/x_ganglia_config
  GANGLIA_INTERVAL = 5
  GANGLIAD_DEBUG = D_FULLDEBUG
  GANGLIA_METRICS_CONFIG_DIR = ' . $configd . '
';

CondorTest::StartCondorWithParams(
    append_condor_config => $append_condor_config
);

# sleep for twice ganglia interval
sleep(10);

# Verify that at least one metric was successfully parsed and
# attempted to be published.  The actual publication will fail,
# because we have not set up ganglia, and we are intentionally using a
# port that will not work.
CondorLog::RunCheck(
    daemon => "GANGLIAD",
    match_regexp => "publishing Jobs in Pool"
);

CondorTest::EndTest();
