#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_cycle-A.dag';
$testdesc =  'Condor submit dag - basic cycle test - scheduler U';
$testname = "job_dagman_cycle-A";
$dagman_args = "-verbose";

$statusfile = "job_dagman_cycle-A.status";
# Lines must be found in order.
@status_blocks = (
	["DagStatus = 6;", "DagStatusName = \"STATUS_ERROR\";", "DagStatusDetails = \"cycle\";",
	 "NodesTotal = 3;", "NodesDone = 1;", "NodesPre = 0;", "NodesQueued = 0;", "NodesPost = 0;",
	 "NodesReady = 0;", "NodesUnready = 2;", "NodesFailed = 0;", "JobProcsHeld = 0;", "JobProcsIdle = 0;"],
	["Node = \"A\";", "NodeStatus = 5;", "NodeStatusName = \"STATUS_DONE\";"],
	["Node = \"B\";", "NodeStatus = 0;", "NodeStatusName = \"STATUS_NOT_READY\";"],
	["Node = \"C\";", "NodeStatus = 0;", "NodeStatusName = \"STATUS_NOT_READY\";"],
);

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# clean out old output files
runcmd("rm -f $statusfile");

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	die("DAG is expected to fail.\n");
};

$failure = sub
{
	CondorTest::debug("DAG failed as expected\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	# Check the node status file.
	$statuserr = CondorTest::CheckNodeStatusFile($statusfile, \@status_blocks);
	if ($statuserr ne "") {
		CondorTest::debug("$statuserr\n",1);
		$diditpass = 0;
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

