#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd = 'job_core_initialdir_sched.cmd';
$testname = 'condor_submit initialdir works - scheduler U';


system("mkdir -p initd_sched");

#CondorTest::RegisterExitedSuccess( $testname, \&CondorTest::DefaultOutputTest );


$ExitSuccess = sub 
{
	my %info = @_;

	my $goal = "";
	print "Looking for $goal\n";
#	# Pull out requested environment values
	my $logs   = $info{"log"};
	print "Log is $logs\n";
	my $initialdir = $info{"initialdir"};
	print "initialdir is $initialdir\n";
	$goal = "$initialdir" . "/" . "$logs";
	if( ! -s $goal )
	{
		print "Expected logfile not found<$goal>\n";
		die "Initialdir does not contain user log\n";
	}
	# clean up
	print "Expected logfile found<$goal>\n";
	system("rm -rf initd_sched");
};


CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

