#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;

$cmd = 'job_ckpt_floats-async_std.cmd';
$testdesc =  'Condition Test';
$testname = "job_ckpt_floats-async_std";

my $on_evictedwithcheckpoint = sub {
	CondorTest::debug("Evicted With Checkpoint expected.\n",1);
	CondorTest::AddCheckpoint();
};

my @expected_output = 
( 'Program completed successfully.',
  'Be sure that it checkpointed at least once.' );
CondorTest::SetExpected(\@expected_output);

CondorTest::RegisterEvictedWithCheckpoint($testname, $on_evictedwithcheckpoint);
CondorTest::RegisterExitedSuccess( $testname, 
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 1) ) {
    CondorTest::debug("$testname: SUCCESS\n",1);
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}


