#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;

$cmd = 'job_ckpt_longjmp_std.cmd';
$testname = 'Threads Test';

for( $i=0; $i<10; $i++ ) {
     push( @CondorTest::expected_output, "i = $i" );
     push( @CondorTest::expected_output, 'About to Ckpt from STACK' );
     push( @CondorTest::expected_output, 'Returned from ckpt_and_exit' );
     push( @CondorTest::expected_output, 'About to Ckpt from DATA' );
     push( @CondorTest::expected_output, 'Returned from ckpt_and_exit' );
}

push( @CondorTest::expected_output, 'Normal End_Of_Job' );

# Skip all the lines that print out explicit STACK and DATA addresses
@CondorTest::skipped_output_lines = 
(2, 5, 9, 12, 16, 19, 23, 26, 30, 33, 37, 40, 44, 47, 51, 54, 58, 61, 65, 68);

CondorTest::RegisterExitedSuccess( $testname,
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}

