#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd = 'job_dagman_splice-3.dag';
$testname = 'Condor submit dag - basic splice test - scheduler U';
$dagman_args = "-verbose";

@outfiles = (
				"S1+A", "S1+B", "S1+C", "S1+D", "S1+E",
				"S1+F", "S1+G", "S1+H", "S1+I",
			);

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

$abnormal = sub 
{

	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	print "Good. We need the dag to run<$info{cluster}>\n";
};

$submitted = sub
{
	print "submitted: This test will see submit, executing and successful completion\n";
};

$success = sub
{
	print "executed successfully\n";
	print "Verifying output\n";
	$diditpass = 1;
	foreach $name (@outfiles) {
		$line = "";
		$passed = 0;
		$canopen = open(OUT,"<$name.out");
		if( ! (defined $canopen)) {
			print "Can not open outfile<$name.out>:$!\n";
			$diditpass = 0;
		}
		while(<OUT>) {
			chomp();
			$line = $_;
			if( $line =~ /^OK.*$/ ) {
				$passed = 1;
				print "$name.out: $line\n";
			}
		}
		close(OUT);
		if($passed == 1 ) {
			;
		} else {
			print "failed $name.out: $line\n";
			$diditpass = 0;
		}
	}
	# clean out old output files
	foreach $name (@outfiles) {
		system("rm -f $name.out $name.err");
	}
	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

