#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd = 'job_core_plus_sched.cmd';
$testdesc =  'Condor_submit correctly places attributes into JobAd - scheduler U';
$testname = "job_core_plus_sched";

my $alreadydone=0;
my $foundcount=0;

$success = sub 
{
	my %info = @_;
	my $cluster = $info{"cluster"};
	my $job     = $info{"job"};
};

$died = sub 
{
	my %info = @_;
	my $expectedsig = $info{"job"}+1;
	my $gotsig      = $info{"signal"};
	my $error 		= $info{"error"};
};


$submit = sub 
{
	my %args = @_;
	my $cluster = $args{"cluster"};

	# avoid reentrant death
	if($alreadydone != 0) 
	{
		return true;
	} 
	else 
	{
		$alreadydone = 1;
	}

	system("condor_config_val -config");
	CondorTest::debug("Checking Job Ads for $cluster\n",1);
	my @adarray;
	my $status = 1;
	my $cmd = "condor_q -l $cluster";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);
	if(!$status)
	{
		CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",1);
		exit(1)
	}
	foreach $name (@adarray)
	{
		#print "job_core_plus_sched: $name\n";

		if( $name =~ /^foo\s*=\s*"(.*)"\s*$/)
		{
			CondorTest::debug("************** $1 ************\n",1);
			$foundcount += 1;
		}
		elsif( $name =~ /^bar\s*=\s*"(.*)"\s*$/)
		{
			CondorTest::debug("************** $1 ************\n",1);
			$foundcount += 1;
		}
		elsif( $name =~ /^last\s*=\s*"(.*)"\s*$/)
		{
			CondorTest::debug("************** $1 ************\n",1);
			$foundcount += 1;
		}
		elsif( $name =~ /^done\s*=\s*(.*)\s*$/)
		{
			CondorTest::debug("************** $1 ************\n",1);
			$foundcount += 1;
		}
	}
	$status = CondorTest::runCondorTool("condor_rm $cluster",\@adarray,2);
	CondorTest::debug("Expect to see 4 attributes {foo,bar,last and done}\n",1);
	die "Missed some attributes" unless $foundcount == 4;
	if(!$status)
	{
		CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",1);
		exit(1)
	}
};

$aborted = sub {
	CondorTest::debug("If all is good we abort our own job.......\n",1);
};


CondorTest::RegisterAbort($testname, $aborted);
CondorTest::RegisterSubmit($testname, $submit);
CondorTest::RegisterExitedFailure( $testname, $died );
CondorTest::RegisterExitedSuccess( $testname, $success );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

