#! /usr/bin/env perl
use CondorTest;

$testname = 'Condor PERIODIC_REMOVE policy test - vanilla U';

my $nostatus = CondorTest::verbose_system("./job_core_perremove-false_van.pl");
my $willstatus = CondorTest::verbose_system("./job_core_perremove-true_van.pl");

if($nostatus != 0)
{
	print "PERIODIC_REMOVE: failed no trigger test\n";
}

if($willstatus != 0)
{
	print "PERIODIC_REMOVE: failed trigger test\n";
}

if(($willstatus != 0) || ($nostatus != 0))
{
	die "Failed one PERIODIC_REMOVE test\n";
}


