#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use strict;
use warnings;


my $cmd_template = "job_condorc_abc_van.template";
my $testdesc =  'job_condorc_abc_van - Chained Condor-C A&B&C with Vanilla job';
my $testname = "job_condorc_abc_van";
my $corename = "job_condorc_abc_van";
my $debuglevel = 2;

# where are we running
my $currenthost = CondorTest::getFqdnHost();
CondorTest::fullchomp($currenthost);
CondorTest::debug("Running on $currenthost\n",$debuglevel);

print scalar localtime() . "\n";

my $mypid = $$;
my $mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

my $mysubmitnm = $corename . $mypid . ".cmd";
my $mysubmitnmlog = $corename . $mypid . ".log";
my $mycorenamecmd = $corename . ".cmd";
my $mycorenamecmdout = $corename . ".cmd.out";
my $mycorenamelog = $corename . ".log";

print scalar localtime() . "\n";
CondorTest::debug("Master PID is $mypid\n",$debuglevel);
CondorTest::debug("Master PID submit file is $mysubmitnm\n",$debuglevel);


# get a remote scheduler running (side c)
my $configrem = CondorTest::StartPersonal( "job_condorc_abc_van", "x_param.condorcremote" ,"remote");
my @remote = split /\+/, $configrem;
my $remconfig = shift @remote;
my $remport = shift @remote;

CondorTest::debug("---Remote config(c) is $remconfig and remote port is $remport---\n",$debuglevel);

print "Dropped a full pool to push Condor-C to\n";

# get a middle scheduler running (side b)
my $configmid = CondorTest::StartPersonal( "job_condorc_abc_van", "x_param.condorcmiddle" ,"middle");
my @middle = split /\+/, $configmid;
my $midconfig = shift @middle;
my $midport = shift @middle;

print "Dropped a collector, schedd and master as an intermediary for Condor-C job.\n";

CondorTest::debug("---Middle config(b) is $midconfig and remote port is $midport---\n",$debuglevel);

# Edit submit file to submit to scheduler at remote (side b) schedd.
my $line;
open(CSUB,">$mysubmitnm") || die "Can't open new submit file $mysubmitnm: $!\n";
open(TPLATE,"<$cmd_template") || die "Can't open submit file template $cmd_template: $!\n";
while(<TPLATE>)
{
	CondorTest::fullchomp($_);
	$line = $_;
	if( $line =~ /^\s*remote_pool\s*=.*$/ )
	{
		CondorTest::debug("remote pool is $currenthost:$midport\n",$debuglevel);
		print CSUB "remote_pool = $currenthost:$midport\n";
	}
	elsif( $line =~ /^\s*remote_schedd\s*=.*$/ )
	{
		my $schedd = "schedd$mypid" . "middle\@$currenthost";
		print CSUB "remote_schedd = $schedd\n";
	}
	elsif( $line =~ /^\s*\+Remote_RemotePool\s*=.*$/ )
	{
		CondorTest::debug("remote pool is $currenthost: port $remport\n",$debuglevel);
		print CSUB "+Remote_RemotePool = \"$currenthost:$remport\"\n";
	}
	elsif( $line =~ /^\s*\+Remote_RemoteSchedd\s*=\s*.*$/ )
	{
		my $schedd = "schedd$mypid" . "remote\@$currenthost";
		print CSUB "+Remote_RemoteSchedd = \"$schedd\"\n";
	}
	# do not leave the log file name alone
	# because we are always cluster 1 as we
	# are always a fresh personal condor and we
	# do not want to trip on it if we fire the test
	# locally a number of times.
	elsif( $line =~ /^\s*log\s*= .*$/)
	{
		my $lognm = $mysubmitnmlog;
		CondorTest::debug("New log name: $lognm\n",$debuglevel);
		print CSUB "log = $lognm\n";
	}
	else
	{
		CondorTest::debug("template: $line\n",$debuglevel);
		print CSUB "$line\n";
	}
}
close(TPLATE);
close(CSUB);

# get a local scheduler running (side a)
my $configloc = CondorTest::StartPersonal( "job_condorc_abc_van", "x_param.condorclocal" ,"local");
my @local = split /\+/, $configloc;
my $locconfig = shift @local;
my $locport = shift @local;

print "Dropped a master and a schedd to send Condor-C job on its way\n";

CondorTest::debug("---local config is $locconfig and local port is $locport---\n",$debuglevel);

$ENV{CONDOR_CONFIG} = $locconfig;
# submit into local schedd (side a)

if( ! -e "job_condorc_xxx_van.in" )
{
	system("date > job_condorc_xxx_van.in");
}

print "Looking for schedds at B middle point of ABC - Condor-C\n";
system("condor_status -pool $currenthost:$midport -schedd -format '%s\n' Name");
print "Looking for schedds at C remote point of ABC - Condor-C\n";
system("condor_status -pool $currenthost:$remport -schedd -format '%s\n' Name");

my $result = system("./job_condorc_ab_van.pl $mysubmitnm job_condorc_abc_van");
CondorTest::debug("Result of crafted Condor-C job is  $result\n",$debuglevel);

system("cp *condorc* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenamecmd");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenamelog");
}


CondorTest::KillPersonal($locconfig);
CondorTest::KillPersonal($midconfig);
CondorTest::KillPersonal($remconfig);
print scalar localtime() . "\n";

if($result != 0)
{
	# actuaal job failed but we allowed cleanup
	exit(1);
}

CondorTest::debug("job_condorc_abc_van SUCCESS\n",$debuglevel);
exit(0);
