#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_abort-B.dag';
$testdesc =  'Condor submit dag - basic abort-dag-on test - scheduler U';
$testname = "job_dagman_abort-B";
$dagman_args = "-verbose";

@outfiles = ("job_dagman_abort-B-node.A", "job_dagman_abort-B-node.B");
$statusfile = "job_dagman_abort-B.status";
# Lines must be found in order.
@statuslines = ("DagStatus = 6;.*STATUS_ERROR \\(aborted\\)",
    "NodesTotal = 4;",
    "NodesDone = 2;",
    "NodesPre = 0;",
    "NodesQueued = 0;",
    "NodesPost = 0;",
    "NodesReady = 0;",
    "NodesUnready = 0;",
    "NodesFailed = 2;",
    "JobProcsHeld = 0;",
    "JobProcsIdle = 0;",
	"Node = \"A\";",
	"NodeStatus = 5;.*STATUS_DONE",
	"Node = \"B\";",
	"NodeStatus = 5;.*STATUS_DONE",
	"Node = \"C\";",
	"NodeStatus = 6;.*STATUS_ERROR",
	"Node = \"D\";",
	# We really should see this job getting removed by the abort, but
	# at this point we don't look for any more events after we abort.
	# wenger 2014-04-02
	# As per gittrac #4686, we now show this node as failed even
	# though we haven't seen the aborted event.
	"NodeStatus = 6;.*STATUS_ERROR");

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

my @failcmd = (
	"executable           	= ./x_dagman_retry-monitor.pl",
	"arguments		= 5",
	"universe             	= scheduler",
	"notification         	= NEVER",
	"getenv               	= true",
	"output			= job_dagman_abort-B-node.\$(nodename).out",
	"error			= job_dagman_abort-B-node.err",
	"queue",
);

my @goodcmd = (
	"executable              = /bin/echo",
	"arguments               = job_dagman_abort-B-node.cmd \$(nodename) OK",
	"universe                = scheduler",
	"notification            = NEVER",
	"getenv                  = true",
	"output                  = job_dagman_abort-B-node.\$(nodename).out",
	"error                   = job_dagman_abort-B-node.err",
	"queue",
);

# clean out old output files
my $iswindows = is_windows();

foreach $name (@outfiles) {
	if($iswindows == 1) {
		runcmd("del /F /Q $name.out $name.err");
	} else {
		runcmd("rm -f $name.out $name.err");
	}
}
if($iswindows == 1) {
	runcmd("del /F /Q $statusfile
	");
} else {
	runcmd("rm -f $statusfile");
}


open(FCMD,">job_dagman_abort-B-node-fail.cmd") or die "failed tom open:job_dagman_abort-B-node-fail.cmd:$!\n";

foreach my $line (@failcmd) {
	if($line =~ /^executable.*/) {
		if($iswindows == 1) {
			print FCMD "executable = makeexit.bat\n";
		} else {
			print FCMD "$line\n";
		}
	} else {
		print FCMD "$line\n";
	}
}

close(FCMD);

open(GCMD,">job_dagman_abort-B-node-succeed.cmd") or die "failed tom open:job_dagman_abort-B-node-succeed.cmd:$!\n";

foreach my $line (@goodcmd) {
	if($line =~ /^executable.*/) {
		if($iswindows == 1) {
			print GCMD "executable = echo.bat\n";
		} else {
			print GCMD "$line\n";
		}
	} else {
		print GCMD "$line\n";
	}
}

close(GCMD);

$abnormal = sub 
{
	die "Error: Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Error: Abort event NOT expected\n";
};

$held = sub 
{
	die "Error: Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	die("Error: DAG is expected to fail.\n");
};

$failure = sub
{
	CondorTest::debug("DAG failed as expected\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;
	foreach $name (@outfiles) {
		$line = "";
		$passed = 0;
		$canopen = open(OUT,"<$name.out");
		if( ! (defined $canopen)) {
			CondorTest::debug("Can not open outfile<$name.out>:$!\n",1);
			$diditpass = 0;
		}
		while(<OUT>) {
			chomp();
			$line = $_;
			if( $line =~ /^.*OK$/ ) {
				$passed = 1;
				CondorTest::debug("$name.out: $line\n",1);
			}
		}
		close(OUT);
		if($passed == 1 ) {
			;
		} else {
			CondorTest::debug("failed $name.out: $line\n",1);
			$diditpass = 0;
		}
	}

	# Check the node status file.
	$line = "";
	$passed = 0;
	$canopen = open(STATUS,"<$statusfile");
	if( ! (defined $canopen)) {
		CondorTest::debug("Can not open statusfile<$statusfile>:$!\n",1);
		$diditpass = 0;
	}
	while(<STATUS>) {
		chomp();
		$line = $_;
		$target = $statuslines[0];
		if( $line =~ /$target/ ) {
			CondorTest::debug("$name: $line\n",1);
			# Remove the target we just found from the array.
			shift @statuslines;
			if ($#statuslines < 0) {
				last;
			}
		}
	}
	close(STATUS);

	if ($#statuslines >= 0) {
		CondorTest::debug("failed missing node status lines:\n");
		foreach $missing (@statuslines) {
			print "  $missing\n";
		}
		$diditpass = 0;
	}

	if($diditpass == 0) {
		die "Error: All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "Error: $testname: CondorTest::RunTest() failed\n";
}

