#! /usr/bin/env perl
use CondorTest;

$cmd = 'job_filexfer_streamout_van.cmd';
$out = 'job_filexfer_streamout_van.out';
$testname = 'Stream output works - vanilla U';

$submitted = sub
{
	my %info = @_;
	my $name = $info{"output"};
	system("rm $name");
};

$aborted = sub 
{
	my %info = @_;
	my $done;
	print "Abort event expected as we clear job\n";
};

$timed = sub
{
	die "Job should have ended by now. file streaming output file broken!\n";
};

$execute = sub
{
	my %info = @_;
	my $job = "good";
	my $cluster = $info{"cluster"};
	my $name = $info{"output"};
	CondorTest::RegisterTimed($testname, $timed, 120);

	#job sleeps forever and will be there for removal
	sleep(60);
	if( -f $name )
	{
		print "YEAH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n";
	}
	else
	{
		$job = "bad";
	}

	print "OK remove the job!\n";
	my @adarray;
	my $status = 1;
	my $cmd = "condor_rm $cluster";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);

	if($job eq "bad")
	{
		die "Test failed to stream output!\n";
	}

	if(!$status)
	{
		print "Test failure due to Condor Tool Failure<$cmd>\n";
		exit(0)
	}
};

$ExitSuccess = sub {
	my %info = @_;
};


# before the test let's throw some weird crap into the environment

CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );
CondorTest::RegisterExecute($testname, $execute);
CondorTest::RegisterSubmit( $testname, $submitted );

#empty local environment and add only a few things that way......
my $path = $ENV{"PATH"};

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

