#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$testdesc =  'Condor ON_EXIT_REMOVE policy test - scheduler U';
$testname = "job_core_onexitrem_sched";

my $nostatus = CondorTest::verbose_system("./job_core_onexitrem-false_sched.pl");
my $willstatus = CondorTest::verbose_system("./job_core_onexitrem-true_sched.pl");

my %listoftests; 
$listoftests{"corename"} = "job_core_onexitrem_sched";
$listoftests{"tests"} = [ "job_core_onexitrem-false_sched", "job_core_onexitrem-true_sched"];
$listoftests{"extensions"} = [ ".cmd", ".cmd.out", ".err", ".out", ".log"];
CondorTest::MergeOutputFiles(\%listoftests);

if($nostatus != 0)
{
	CondorTest::debug("ON_EXIT_REMOVE: failed no trigger test\n",1);
}

if($willstatus != 0)
{
	CondorTest::debug("ON_EXIT_REMOVE: failed trigger test\n",1);
}

if(($willstatus != 0) || ($nostatus != 0))
{
	die "Failed one ON_EXIT_REMOVE test\n";
}


