#! /usr/bin/env perl
use CondorTest;

$cmd = 'job_filexfer_basic_sched.cmd';
$testname = 'Do file transfers work - scheduler U';


$success = sub {
	open(SENT,    "<job_filexfer_basic.data")|| die "Can't open job_filexfer_basic.data: $!\n";
	open(GOTBACK, "<submit_transferfile_scheduler.txtdata") || die "Can't open submit_transferfile_scheduler.txtdata: $!\n";
	local $/;
	my $sent = <SENT>;
	my $got  = <GOTBACK>;
	close SENT;
	close GOTBACK;
	if($sent ne $got) {
		die "Data was not preserved between file transfers\n";
	}
	system("rm submit_transferfile_scheduler.txtdata");
};

CondorTest::RegisterExitedSuccess($testname, $success);
if(CondorTest::RunTest($testname, $cmd, 0)) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

