#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd = 'job_filexfer_streamerr_van.cmd';
$out = 'job_filexfer_streamerr_van.out';
$testname = 'Stream error works - vanilla U';

$submitted = sub
{
	my %info = @_;
	my $name = $info{"error"};
	system("rm $name");
};

$aborted = sub 
{
	my %info = @_;
	my $done;
	print "Abort event expected as we clear job\n";
};

$timed = sub
{
	die "Job should have ended by now. file streaming error file broken!\n";
};

$execute = sub
{
	my %info = @_;
	my $job = "good";
	my $cluster = $info{"cluster"};
	my $name = $info{"error"};
	CondorTest::RegisterTimed($testname, $timed, 300);

	#job sleeps forever and will be there for removal
	sleep(60);
	if( -f $name )
	{
		print "YEAH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n";
	}
	else
	{
		$job = "bad";
	}

	print "OK remove the job!\n";
	my @adarray;
	my $status = 1;
	my $cmd = "condor_rm $cluster";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);

	if($job eq "bad")
	{
		die "Test failed to stream error!\n";
	}

	if(!$status)
	{
		print "Test failure due to Condor Tool Failure<$cmd>\n";
		exit(0)
	}
};

$ExitSuccess = sub {
	my %info = @_;
};


# before the test let's throw some weird crap into the environment

CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );
CondorTest::RegisterExecute($testname, $execute);
CondorTest::RegisterSubmit( $testname, $submitted );

#empty local environment and add only a few things that way......
my $path = $ENV{"PATH"};

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

