#! /usr/bin/env perl
use CondorTest;

$testname = 'Condor STREAM_ERROR policy test - vanilla U';

my $nostatus = CondorTest::verbose_system("job_core_streamerr-false_van.pl");
my $willstatus = CondorTest::verbose_system("job_core_streamerr-true_van.pl");

my %listoftests;
$listoftests{"corename"} = "job_core_streamerr_van";
$listoftests{"tests"} = [ "job_core_streamerr-false_van", "job_core_streamerr-true_van"];
$listoftests{"extensions"} = [ ".cmd", ".cmd.out", ".err", ".out", ".log"];
CondorTest::MergeOutputFiles(\%listoftests);

if($nostatus != 0)
{
	print "STREAM_ERROR: failed no trigger test\n";
}

if($willstatus != 0)
{
	print "STREAM_ERROR: failed trigger test\n";
}

if(($willstatus != 0) || ($nostatus != 0))
{
	die "Failed one STREAM_ERROR test\n";
}


