#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;

$cmd = 'job_ckpt_f-reader_std.cmd';
$testdesc =  'Fortran Reader Test';
$testname = "job_ckpt_f-reader_std";

$OutputTest = sub
{
    my %info = @_;
    my $output = $info{"output"};
    my $error = $info{"error"};

    $_ = `wc -l /etc/passwd`;
    /\s*(\d+).*/;
    $lines = $1;

    -f $error || 
	die "$testname: FAILURE ($error doesn't exist)\n";

    -z $error || 
	die "$testname: FAILURE (STDERR contains data)\n";

    open( OUTPUT, "<$output" ) || die "Can't open $output: $!\n";
    $line = 1;
    while( <OUTPUT> ) {
	if( /^\s*Read\s*(\d+)\s*lines/ ) {
	    if( $lines != $1 ) {
		die "$testname: FAILURE (Actual lines read [$1] " .
		    "doesn't match expected [$lines] on line $line)\n";
	    }
	} else {
	    die "$testname: FAILURE (Can't parse output on line $line)\n";
	}
	$line++;
    }
};

CondorTest::RegisterExitedSuccess( $testname, $OutputTest );
CondorTest::RegisterExitedFailure( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
        CondorTest::debug("$testname: SUCCESS\n",1);
        exit(0);
} else {
        die "$testname: CondorTest::RunTest() failed\n";
}

