#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Cwd;
use Sys::Hostname;

$cmd = 'job_core_macros_java.cmd';
$testname = 'condor_submit macros - java U';


@CondorTest::skipped_output_lines = ( 3, 4, 5, 6 );
@CondorTest::expected_output =
(
'foobar',
'0',
);



$ExitSuccessBase = sub {
	my %info = @_;

	#$output = $info{"output"};

};

my @lines;

sub load_up_lines
{
	open(IN,"<submit_macros_java.out") || die "Can not open submit_macros_java.out: $!\n";
	while(<IN>)
	{
		CondorTest::fullchomp($_);
		push @lines, $_;
	}
};

$success = sub
{
    my %args = @_;
	my $cluster = $args{"cluster"};
	my $home;
	my $workdir = getcwd();
	my $host = CondorTest::getFqdnHost();
	my $random;

	chdir;
	$home = getcwd;
	print "My home is $home\n";
	print "My host is $host\n";
	chdir($workdir);
	load_up_lines();
	foreach my $item ( @lines )
	{
		print "ARG -$item-\n";
	}
	$random = $lines[4];
	print "RANDOM is $random\n";

	if( $random < 2 )
	{
		die "Random value below range\n";
	}
	elsif( $random > 5 )
	{
		die "Random value above range\n";
	}
};

#CondorTest::RegisterExecute($testname, $execute);
#CondorTest::RegisterExitedSuccess( $testname, \&CondorTest::DefaultOutputTest );
CondorTest::RegisterExitedSuccess( $testname, $success );


if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

