#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use x_vm_utils;

$corename = 'job_vmu_ckpt';
$testname = 'job_vmu_ckpt';
$testdesc = 'VM universe checkpoint test';

x_vm_utils::initialize($corename);

$start_flag = 0;
$waiting_for_vm = 1;
$timed = sub
{
	CondorTest::debug("Checking VM output\n",1);
	if ($waiting_for_vm == 0) {
		CondorTest::RemoveTimed( $testname );
		return;
	}
	unless (x_vm_utils::check_output("STARTED")) {
		CondorTest::RegisterTimed( $testname, $timed, 5 );
		return;
	}
	$waiting_for_vm = 0;
	CondorTest::RemoveTimed( $testname );
	CondorTest::debug("VM has STARTED\n",1);
	unless (CondorTest::runCondorTool("condor_qedit " .
	                                      "-constraint True " .
	                                      "Requirements False")) {
		die "condor_qedit failure\n";
	}
	unless (CondorTest::runCondorTool("condor_vacate_job -a")) {
		die "condor_hold failure\n";
	}
};
$started = sub
{
	CondorTest::debug("Job is running\n",1);
	if ($start_flag == 1) {
		return;
	}
	$start_flag = 1;
	CondorTest::RegisterTimed( $testname, $timed, 5 );
};
$evicted = sub
{
	CondorTest::debug("Job is checkpointed\n",1);
	x_vm_utils::set_data("CHECKPOINTED");
	unless (CondorTest::runCondorTool("condor_qedit " .
	                                      "-constraint True " .
	                                      "Requirements True")) {
		die "condor_release failure\n";
	}
};
$completed = sub
{
	CondorTest::debug("Job has completed\n",1);
	unless (x_vm_utils::check_output("DONE")) {
		die "output check failed\n";
	}
};
CondorTest::RegisterExecute( $testname, $started );
CondorTest::RegisterEvicted( $testname, $evicted );
CondorTest::RegisterExitedSuccess( $testname, $completed );

x_vm_utils::add_submit_command("vmware_should_transfer_files = yes");
x_vm_utils::add_submit_command("vmware_snapshot_disk = false");
x_vm_utils::add_submit_command("vm_checkpoint = true");
x_vm_utils::add_submit_command("periodic_remove = (CurrentTime - QDate) > 600");
$success = x_vm_utils::run_test($testname);

x_vm_utils::cleanup();

if( not $success )
{
	CondorTest::debug("$corename FAILED\n",1);
	exit(1);
}
CondorTest::debug("$corename SUCCESS\n",1);
exit(0);
