#!/usr/bin/python3

import os
import sys

# If your test needs to start a custom personal HTCondor, you can use StartPersonalCondor() of the CondorTest class
# If your test just needs to have HTCondor running, you can use testreq/CONDOR_TESTREQ_CONFIG comment mechanism instead.
# see job_late_materialize_py for an example of the testreq mechanism

from pytest_old.CondorCluster import CondorCluster
from pytest_old.CondorTest import CondorTest
from pytest_old.PersonalCondor import PersonalCondor
from pytest_old.Utils import Utils
from pytest_old.Globals import *


def submit_callback():
    Utils.TLog("Custom submit callback called!")

def success_callback():
    Utils.TLog("Test succeded. Exiting with status TEST_SUCCCESS")
    sys.exit( TEST_SUCCESS )

def failure_callback():
    Utils.TLog("Test failed. Exiting with status TEST_FAILURE")
    sys.exit( TEST_FAILURE )


def main():
    # Stand up a PersonalCondor
    personal_handle = CondorTest.StartPersonalCondor("job_basic_pytest")
    if not personal_handle:
        Utils.TLog("Failed to start the PersonalCondor environment. Exiting.")
        sys.exit( TEST_FAILURE )
    else:
        Utils.TLog("PersonalCondor environment started successfully")

    # Setup a new test job
    job_args = {
        "executable":   "x_echostring.pl",
        "output":       "job_basic_pytest.out",
        "error":        "job_basic_pytest.err",
        "log":          "job_basic_pytest.log",
        "arguments":    "\"Basic Python pytest submission, cluster $(cluster)\""
    }
    test_job = CondorCluster(job_args)

    # Register handlers
    test_job.RegisterSubmit(submit_callback)
    test_job.RegisterJobTerminated(success_callback)
    test_job.RegisterJobHeld(failure_callback)

    # Submit the test job
    if test_job.Submit() == JOB_FAILURE:
        Utils.TLog( "Failed to submit job!" )
        sys.exit( TEST_FAILURE )
    test_job.WaitUntilJobTerminated()

    Utils.TLog("Test continued unexpectedly while waiting for job to terminate.  Test failed.")
    sys.exit(TEST_FAILURE)


if __name__ == "__main__":
    main()
