#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Cwd;
use Sys::Hostname;

my $cmd = 'job_core_macros_sched.cmd';
my $testdesc =  'condor_submit macros - scheduler U';
my $testname = "job_core_macros_sched";

my $debuglevel = 2;

my @skipped_output_lines = ( 1, 4, 5, 6 );
my @expected_output =
(
'foobar',
'0',
);

CondorTest::SetExpected(\@expected_output);
CondorTest::SetSkipped(\@skipped_output_lines);

print "Set expected output\n";

$ExitSuccessBase = sub {
	my %info = @_;

	#$output = $info{"output"};

};

my @lines;

sub load_up_lines
{
	open(IN,"<job_core_macros_sched.out") || die "Can not open job_core_macros_sched.out: $!\n";
	while(<IN>)
	{
		CondorTest::fullchomp($_);
		push @lines, $_;
	}
};

$success = sub
{
    my %args = @_;
	my $cluster = $args{"cluster"};
	my $home;
	my $workdir = getcwd();
	my $host = CondorTest::getFqdnHost();
	my $random;

	chdir;
	$home = getcwd;
	CondorTest::debug("My home is $home\n",$debuglevel);
	CondorTest::debug("My host is $host\n",$debuglevel);
	chdir($workdir);
	load_up_lines();
	foreach my $item ( @lines )
	{
		CondorTest::debug("ARG -$item-\n",$debuglevel);
	}
	$random = $lines[5];
	CondorTest::debug("RANDOM is $random\n",$debuglevel);

	print "Looking for random 2 <= random <= 5 - ";
	if( $random < 2 )
	{
		print "bad\n";
		die "Random value below range\n";
	}
	elsif( $random > 5 )
	{
		print "bad\n";
		die "Random value above range\n";
	}
	print "ok\n";
};

#CondorTest::RegisterExecute($testname, $execute);
#CondorTest::RegisterExitedSuccess( $testname, \&CondorTest::DefaultOutputTest );
CondorTest::RegisterExitedSuccess( $testname, $success );


if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",$debuglevel);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

