#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;

$cmd = 'job_rsc_fcntl_std.cmd';
$testdesc =  'Fcntl Test';
$testname = "job_rsc_fcntl_std";

$foo = <<"_EOX";
F_GETFD gives: 0
F_GETFD gives: 1	(should be 1)
F_GETFD gives: 0	(should be 0)
F_GETFL gives: 0	(should be 0)
F_GETFL gives: 1	(should be 1)
F_DUPFD returns: 5 with arg = 5
_EOX

my @expected_output = split '\n', $foo;

my @skipped_output_lines = (1);
# Line 1: 'Filedes = 32', so we don't know what fd we're going to get

CondorTest::SetExpected(\@expected_output);
CondorTest::SetSkipped(\@skipped_output_lines);


CondorTest::RegisterExitedSuccess( $testname,
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    CondorTest::debug("$testname: SUCCESS\n",1);
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}


