#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Check::SimpleJob;

# This is the "remote" pool where the job will run.
my $poolC = CondorTest::StartCondorWithParams(
    condor_name => "poolC",
    daemon_list => "MASTER, COLLECTOR, SCHEDD, STARTD, NEGOTIATOR"
);

my $poolC_collector = $poolC->GetCollectorAddress();
my $poolC_schedd_name =
    `condor_status -pool $poolC_collector -schedd -format "%s\n" Name`
    || die "Failed to query schedd name.";
chomp $poolC_schedd_name;


my $append_condor_config = '
  # reduce latency in test
  CONDOR_JOB_POLL_INTERVAL = 10
';

# This is the "middle" pool where the job is resubmitted.
my $poolB = CondorTest::StartCondorWithParams(
    condor_name => "poolB",
    daemon_list => "MASTER, COLLECTOR, SCHEDD",
    append_condor_config => $append_condor_config
);

my $poolB_collector = $poolB->GetCollectorAddress();
my $poolB_schedd_name =
    `condor_status -pool $poolB_collector -schedd -format "%s\n" Name`
    || die "Failed to query schedd name.";
chomp $poolB_schedd_name;


# This is the "local" pool where the job is submitted.
# Since it is started last, CONDOR_CONFIG points to it.
CondorTest::StartCondorWithParams(
    condor_name => "poolA",
    daemon_list => "MASTER, COLLECTOR, SCHEDD",
    append_condor_config => $append_condor_config
);

my $append_submit_commands = "
  remote_universe = grid
  remote_GridResource = condor $poolC_schedd_name $poolC_collector
";

# verify that a job runs
SimpleJob::RunCheck(
    universe => "grid",
    grid_resource => "condor $poolB_schedd_name $poolB_collector",
    append_submit_commands => $append_submit_commands
);

CondorTest::EndTest();
