#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# new test now is a single file and does both local and vanilla universe
# bt 2/13/15

use CondorUtils;
use CondorTest;
use Cwd;
use POSIX;
use Check::SimpleJob;

$topdir = getcwd();
print scalar localtime() . "\n";

$testname = "job_basic_submit-queueitemfrom-1Line";

# where am I running
$currenthost = CondorTest::getFqdnHost();

$mypid = $$;

my $counter = 0;
my $datafileswanted = 3;
my $datafilename = "filepart-macros";
my $extension = ".Fnxmacro";
my $targetname = "";
my @results = ();
my @extraction = ();
my $extractionsize = 0;

my $submitfile = "
	executable = x_print-args.pl
	should_transfer_files = yes
	when_to_transfer_output = ON_EXIT
	output = $testname.out
	log = $testname$mypid.log
	Arguments = \$(ACTION) \$(ITEM)
	queue ACTION,ITEM from (Cook Beans)
";

my $ExitedSuccess = sub {
	print "Job ran fine\n";
};

my $onelinepattern = "Cook Beans";
my %expectedhashcheck = ();
my @expected = split /\s/, $onelinepattern;

foreach my $item (@expected) {
	$expectedhashcheck{$item} = 1;
}


my $submitfilename = "$testname$mypid.cmd";
open(SF,">$submitfilename") or die "failed submit file write:$submitfilename:$!\n";
print SF "$submitfile";
close(SF);

print "Lets see it it runs\n";

CondorTest::RegisterExitedSuccess( $testname, $ExitedSuccess );

if( CondorTest::RunTest($testname, $submitfilename, 0) ) {
    print "Good\n";
    CondorTest::debug("$testname: SUCCESS\n",$debuglevel);
    RegisterResult(1,"test_name","$testname");
} else {
    print "Bad\n";
    RegisterResult(0,"test_name","$testname");
}

my $line = "";
#$expectedhashcheck{$item} = 1;
# we expect to only see things in the hash
open(TN,"<$testname.out") or die "failed to open test output job:$testname.out:$!\n";
while (<TN>) {
	$line = $_;
	chomp($line);
	if(exists $expectedhashcheck{$line}) {
		print "This ouutput was expected - $line - Good\n";
    	RegisterResult(1,"test_name","$testname");
	} else {
		print "This ouutput WAS NOT expected - $line - Bad\n";
    	RegisterResult(0,"test_name","$testname");
	}
}
close(TN);

CondorTest::EndTest();
print scalar localtime() . "\n";
my $result = 0;

if( $result != 0 )
{
	exit(1);
}

CondorTest::debug("$testname SUCCESS\n",1);
exit(0);

