#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_ckpt_open-async-ckpt_std.cmd';
$testname = 'Open Test';

@CondorTest::expected_output = ( 'completed successfully' );

CondorTest::RegisterExitedSuccess( $testname,
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 1) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}

