#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# This tests part of the "allow PRE script to skip node job" feature
# (gittrac #2122).  Both nodes have the skip option enabled; node A's
# job should be run because the PRE script returns 0; node B's job should
# not be run because the PRE script returns a non-skip error -- therefore
# the node (and the DAG) are considered failed.

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_pre_skip-A.dag';
$testdesc =  'Condor submit dag - basic pre_skip node test A - scheduler U';
$testname = "job_dagman_pre_skip-A";
$dagman_args = "-verbose";

$logfile = "job_dagman_pre_skip-A.dag.dagman.out";
@outfiles = ("job_dagman_pre_skip-A_A.out", "job_dagman_pre_skip-A_B.out");
my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log and output files
if (-e $logfile) {
	runcmd("rm -f $logfile");
}
foreach $name (@outfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

$abnormal = sub 
{
	die "Want to see only submit, execute and failed completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and failure\n",1);
};

$failure = sub
{
	CondorTest::debug("failed as expected\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	if (! -e "job_dagman_pre_skip-A_A.out") {
		CondorTest::debug("Error: Node A was not run!\n");
		$diditpass = 0;
	} else {
		CondorTest::debug("Node A was run\n");
	}
	if (-e "job_dagman_pre_skip-A_B.out") {
		CondorTest::debug("Error: Node B was run!\n");
		$diditpass = 0;
	} else {
		CondorTest::debug("Node B was correctly not run\n");
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

$success = sub
{
	die "Error: DAG should fail!\n";
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}
