#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;

$cmd = ['job_dagman_set_attr1.dag', 'job_dagman_set_attr2.dag'];
$testdesc =  'Condor submit dag - test setting ClassAd attributes - scheduler U';
$testname = "job_dagman_set_attr";
$dagman_args = "-verbose -append '+test_attr0 = Dalyan' -append '+test_attr3 = Vrsic' -insert_sub_file job_dagman_set_attr.sub";

@outfiles = ("job_dagman_set_attr.dag.dagman.out",
	"job_dagman_set_attr-nodeA.out",
	"job_dagman_set_attr-nodeB.out");

# Note:  We won't necessarily find the lines in any specific order.
@expected_lines = (
	'test_attr0 = Dalyan',
	'test_attr1 = 234',
	'test_attr2 = "0.987 6.402"',
	'test_attr3 = Vrsic',
	'test_attr4 = 3.14159',
	'test_attr6 = 987',
);

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing output files.
foreach $name (@outfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$failure = sub 
{
	die "Error: DAG is not expected to fail!\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;
	shift @outfiles; # get rid of dagman.out
	foreach $file (@outfiles) {
		CondorTest::debug("Checking $file\n",1);

		$canopen = open(OUT, "<$file");
		if (! (defined $canopen)) {
			CondorTest::debug("Cannot open output file <$file>:$!\n",1);
			$diditpass = 0;
		} else {
			$contents = do { local $/; <OUT>; };
			foreach $eline (@expected_lines) {
				if (index($contents, $eline) >= 0) {
					CondorTest::debug("Found $eline in $file\n",1);
				} else {
					CondorTest::debug("ERROR: $eline not found in $file\n",1);
					$diditpass = 0;
				}
			}
			close(OUT);
		}
	}

	if ($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

