#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorPersonal;

CondorPersonal::DebugOff();
Condor::DebugOff();

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

$testname = 'job_vmu_basic';
$corename = "job_vmu_basic";

# where am I running
$currenthost = `hostname`;
chomp($currenthost);
$primarycollector = $currenthost;
my @adarray;

CondorTest::fullchomp($currenthost);

system("date");

$mypid = CondorPersonal::SaveMeSetup($corename);
$mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

my $vmwareimage = "/scratch/damnsl";

$mysubmitnm = $corename . $mypid . ".cmd";
$mysubmitnmout = $corename . $mypid . ".cmd.out";
$mysubmitnmlog = $corename . $mypid . ".log";
$mysubmitnmout = $corename . $mypid . ".out";
$mycorenm = $corename . ".cmd";
$mycorenmout = $corename . ".cmd.out";
$mycorenmlog = $corename . ".log";

print "Master PID is $mypid\n";
print "Master PID submit file is $mysubmitnm\n";

my $cmdtemplate = "job_vmu_basic.cmd.template";
open(TEMPLATE,"<$cmdtemplate") || die "Can not open template<$cmdtemplate>:$!\n";
open(SUBMIT,">$mysubmitnm") || die "Can not open submit file<$mysubmitnm>:$!\n";
my $line = "";
while(<TEMPLATE>) {
	chomp();
	$line = $_;
	if($line =~ /^\s*vmware_dir\s*=\s*XXXXXX\s*$/) {
		print SUBMIT "vmware_dir = $vmwareimage\n";
	} else {
		print SUBMIT "$line\n";
	}
}
close(TEMPLATE);
close(SUBMIT);

my $version = "vmuniverse";
# get a local scheduler running (side a)
my $configloc = CondorPersonal::StartCondor("x_param.vmware" ,$version);
my @local = split /\+/, $configloc;
my $locconfig = shift @local;
my $locport = shift @local;

print "---local config is $locconfig and local port is $locport---\n";

$ENV{CONDOR_CONFIG} = $locconfig;


print "Saving things and cleaning up....\n";

system("cp *job_vmu_basic* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

exit(0);

my $status = 1;
my $cmd = "condor_rm -all";
$status = CondorTest::runCondorTool($cmd,\@adarray,2);
if(!$status)
{
	print "Test failure due to Condor Tool Failure<$cmd>\n";
	exit(1)
}

sleep(5);

$cmd = "condor_off -fast -master";
$status = CondorTest::runCondorTool($cmd,\@adarray,2);
if(!$status)
{
	print "Test failure due to Condor Tool Failure<$cmd>\n";
	exit(1)
}

system("date");

if( $done == 0 )
{
	# actual test failed but we allowed cleanup
	exit(1);
}

print "job_vmu_basic SUCCESS\n";
system("date");
exit(0);
