#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;
use Check::CondorLog;

$cmd = 'job_core_initialdir_java.cmd';
$testdesc =  'condor_submit initialdir works - java U';
$testname = "job_core_initialdir_java";
my $pid = $$;

my $javainit = CondorTest::JavaInitialize($testname);
if($javainit == 0) {
	die "No java found\n";
}

if(!(-d "initd")) {
	runcmd("mkdir -p initd",{emit_output=>0});

} else {
	runcmd("rm -rf initd/*",{emit_output=>0}); 
}
runcmd("cp x_java_CondorEcho.class initd");

#CondorTest::RegisterExitedSuccess( $testname, \&CondorTest::DefaultOutputTest );


$ExitSuccess = sub 
{
	my %info = @_;

	my $goal = "";
#	# Pull out requested environment values
	my $logs   = $info{"log"};
	print "My user log is:$logs\n";
	my $initialdir = $info{"initialdir"};
	$goal = "$initialdir" . "/" . "$logs";
	print "It should be:$goal\n";
	if( ! -s $goal )
	{
		die "Initialdir does not contain user log\n";
	}
	# clean up
	print "Great it is in the intialdir set for job\n";

	# the test suite has open file handles to the event log, causing
	# the following command to fail on NFS-based workign directories.
	runcmd("rm -rf initd || :",{emit_output=>0});
};


CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

