#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd = 'job_core_holdkillsig_sched.cmd';
$testname = 'Condor allows change of hold kill signal - scheduler U';

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

$abnormal = sub {
	my %info = @_;

	print "keys:".join(" ",keys %info)."\n";
	my $gotsig   = $info{"signal"};
	my $outfile = $info{"log"};
	my $killsig = $info{"hold_kill_sig"};
	print "Want to see $killsig in this file $outfile\n";
};

$aborted = sub {
	my %info = @_;
	my $done;
	print "Abort event expected\n";

	print "keys:".join(" ",keys %info)."\n";
	my $gotsig   = $info{"signal"};
	my $outfile = $info{"output"};
	my $killsig = $info{"hold_kill_sig"};
	print "Want to see $killsig in this file $outfile\n";
	open( FILE, "<$outfile" ) || die "error opening $file: $!\n";
	while(<FILE>)
	{
		CondorTest::fullchomp($_);
		print "Found $_\n";
		if($_ eq $killsig)
		{
			print "Good\n";
			return;
		}
		else
		{
			die "Needed to see $killsig as killing signal\n";
		}
	}
};

$held = sub {
	my %info = @_;
	my $done;
	print "Held event expected\n";
	my $cluster = $info{"cluster"};

	my @adarray;
	my $status = 1;
	my $cmd = "condor_rm $cluster";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);
	if(!$status)
	{
		print "Test failure due to Condor Tool Failure<$cmd>\n";
		exit(t)
	}
	sleep 5;
};

$executed = sub
{
	my %args = @_;
	my $cluster = $args{"cluster"};

	my @adarray;
	my $status = 1;
	my $cmd = "condor_hold $cluster";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);
	if(!$status)
	{
		print "Test failure due to Condor Tool Failure<$cmd>\n";
		exit(1)
	}
	sleep 5;
};

CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

