#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# This tests part of the "allow PRE script to skip node job" feature
# (gittrac #2122).  This makes sure that the PRE_SKIP setting gets put
# into a rescue DAG.

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_pre_skip-C.dag';
$testdesc =  'Condor submit dag - basic pre_skip node with rescue DAG test - scheduler U';
$testname = "job_dagman_pre_skip-C";
$dagman_args = "-verbose";
# Tell DAGMan to write complete (old-style) rescue DAGs.
#testreq: personal
my $config = <<CONDOR_TESTREQ_CONFIG;
	DAGMAN_WRITE_PARTIAL_RESCUE=0
CONDOR_TESTREQ_CONFIG
#endtestreq

$rescuedag = "job_dagman_pre_skip-C.dag.rescue001";

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing rescue DAG file.
if (-e $rescuedag) {
    runcmd("rm -f $rescuedag");
}

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and failure\n",1);
};

$failure = sub
{
	CondorTest::debug("DAG failed as expected\n",1);
	CondorTest::debug("Verifying output\n",1);

	my %info = shift;
	$diditpass = 0;

	$canopen = open(RESCUE,"<$rescuedag");
	if( ! (defined $canopen)) {
		CondorTest::debug("Error: cannot open rescue DAG <$name>:$!\n",1);
	}
	while(<RESCUE>){
		if (/PRE_SKIP A 2/) {
			CondorTest::debug("Found PRE_SKIP line in rescue DAG\n");
			$diditpass = 1;
		}
	}
	close(RESCUE);

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

$success = sub
{
	die "Error: DAG should fail!\n";
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}
