#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$testdesc =  'Jobs complaining cause No FT on when tansfer_executables = true - vanilla U';
$testname = "job_filexfer_trans-excut-true_van";

my $pid = $$;
print "Calling ./x_sanitysubmit.p with PID = <$pid>\n";
my $sanestatus = CondorTest::verbose_system("./x_sanitysubmit.pl $pid");
my $teststatus = CondorTest::verbose_system("./job_filexfer_trans-excut-true_van.pl");

if($sanestatus != 0)
{
        CondorTest::debug("job_filexfer_trans-excut-true_van failed sanity submittest\n",1);
}

if($teststatus != 0)
{
        CondorTest::debug("job_filexfer_trans-excut-true_van failed actual test\n",1);
}

if(($teststatus == 0) && ($sanestatus == 0))
{
        CondorTest::debug("Passed job_filexfer_trans-excut-true_van\n",1);
} else {
		die "Failed job_filexfer_trans-excut-true_van\n";
}

