#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorPersonal;

CondorPersonal::DebugOn();

$cmd_template = "job_core_gcbbasic.template";
$testname = 'job_core_gcbbasic - gcb smoke test';
$corename = "job_core_gcbbasic";

# where am I running
$currenthost = CondorTest::getFqdnHost();
chomp($currenthost);
$primarycollector = $currenthost;

CondorTest::fullchomp($currenthost);

system("date");

$mypid = CondorPersonal::SaveMeSetup($corename);
$mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

$mysubmitnm = $corename . $mypid . ".cmd";
$mysubmitnmout = $corename . $mypid . ".cmd.out";
$mysubmitnmlog = $corename . $mypid . ".log";
$mysubmitnmout = $corename . $mypid . ".out";
$mycorenm = $corename . ".cmd";
$mycorenmout = $corename . ".cmd.out";
$mycorenmlog = $corename . ".log";

int "Master PID is $mypid\n";
print "Master PID submit file is $mysubmitnm\n";

# eventually we want to look for clues as to where the
# gcb collect is that we wish to join to dropped as a hint by platform_pre
# glue

$myparamtemplate = "x_param.gcbbasic.template";
$myparam = "x_param.gcbbasic";

open(TEMPL,"<$myparamtemplate") or die "Could not read<$myparamtemplate>:$!\n";
open(PAR,">$myparam") or die "Could not write<$myparam>:$!\n";
while(<TEMPL>) {
	print PAR "$_";
}

my $version = $mypid . "local";
# get a local scheduler running (side a)
my $configloc = CondorPersonal::StartCondor("x_param.gcbbasic" ,$version);
my @local = split /\+/, $configloc;
my $locconfig = shift @local;
my $locport = shift @local;

print "---local config is $locconfig and local port is $locport---\n";

$primarycollector = $primarycollector . ":" . $locport;

$ENV{CONDOR_CONFIG} = $locconfig;

# there is only a master and a schedd here as we
print "Primary collector for other nodes <<$primarycollector>>\n";

print "sleeping 15\n";
sleep(20);
print "Done sleeping\n";

system("condor_status");

print "sleeping 15\n";
sleep(20);
print "Done sleeping\n";

my $forever = CondorTest::verbose_system("./job_core_gcbbasic.pl");
if($forever != 0) {
	print "Bailing because running job failed to submit\n";
	$bail = 1;
}


system("cp *job_core_gcbbasic* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

# still set to local config
# $ENV{CONDOR_CONFIG} = $locconfig;

my @adarray;
my $status = 1;
#my $cmd = "condor_rm -all";
#$status = CondorTest::runCondorTool($cmd,\@adarray,2);
#if(!$status)
#{
	#print "Test failure due to Condor Tool Failure<$cmd>\n";
	#exit(1)
#}

$status = 1;
$cmd = "condor_off -fast -master";
$status = CondorTest::runCondorTool($cmd,\@adarray,2);
if(!$status)
{
	print "Test failure due to Condor Tool Failure<$cmd>\n";
	exit(1)
}

if( $bail == 1 )
{
	# actual test failed but we allowed cleanup
	exit(1);
}

print "job_core_gcbbasic SUCCESS\n";
system("date");
exit(0);
