#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

## This makes sure that DAGMan works correctly with the new submit
## file globbing features.

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_submit_glob-A.dag';
$testdesc =  'Condor submit dag - submit glob A test - scheduler U';
$testname = "job_dagman_submit_glob-A";
$dagman_args = "-verbose";

@logfiles = ("job_dagman_submit_glob-A.dag.dagman.out");

@outfiles = ("job_dagman_submit_glob-A-nodeA.0.out",
	"job_dagman_submit_glob-A-nodeA.1.out",
	"job_dagman_submit_glob-A-nodeA.2.out",
	"job_dagman_submit_glob-A-nodeB.0.out",
	"job_dagman_submit_glob-A-nodeB.1.out",
	"job_dagman_submit_glob-A-nodeB.2.out",
	"job_dagman_submit_glob-A-nodeC.0.out",
	"job_dagman_submit_glob-A-nodeC.1.out");

# Note: we must find these lines *in the specified order*.
$outlines = "job_dagman_submit_glob-A-nodeA.0.out:\n" .
	"Miguel Indurain\n" .
	"Philippe Thys\n" .
	"job_dagman_submit_glob-A-nodeA.1.out:\n" .
	"Louison Bobet\n" .
	"Charly Gaul\n" .
	"job_dagman_submit_glob-A-nodeA.2.out:\n" .
	"Eddy Merckx\n" .
	"Jacques Anquetil\n" .
	"job_dagman_submit_glob-A-nodeB.0.out:\n" .
	"Eddy Merckx\n" .
	"Jacques Anquetil\n" .
	"job_dagman_submit_glob-A-nodeB.1.out:\n" .
	"Louison Bobet\n" .
	"Charly Gaul\n" .
	"job_dagman_submit_glob-A-nodeB.2.out:\n" .
	"Miguel Indurain\n" .
	"Philippe Thys\n" .
	"job_dagman_submit_glob-A-nodeC.0.out:\n" .
	"Eddy Merckx\n" .
	"Jacques Anquetil\n" .
	"Miguel Indurain\n" .
	"Philippe Thys\n" .
	"job_dagman_submit_glob-A-nodeC.1.out:\n" .
	"Louison Bobet\n" .
	"Charly Gaul\n";

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log files.
foreach $name (@logfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

# Get rid of any existing output files.
foreach $name (@outfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

# Remove any existing rescue DAGs.
runcmd("rm -f job_dagman_submit_glob-A.dag.rescue*");

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	foreach $name (@logfiles) {
		$line = "";
		$passed = 0;
		$canopen = open(OUT,"<$name");
		if( ! (defined $canopen)) {
			CondorTest::debug("Can not open logfile<$name>:$!\n",1);
			$diditpass = 0;
		}
		while(<OUT>) {
			chomp();
			$line = $_;
			if( $line =~ /^.*EXITING WITH STATUS 0.*$/ ) {
				$passed = 1;
				CondorTest::debug("$name: $line\n",1);
			}
		}
		close(OUT);
		if($passed == 1 ) {
			;
		} else {
			CondorTest::debug("failed $name: $line\n",1);
			$diditpass = 0;
		}
	}

	$alloutput = "";
	foreach $name (@outfiles) {
		$canopen = open(OUT,"<$name");
		if( ! (defined $canopen)) {
			CondorTest::debug("Cannot open outfile<$name>:$!\n",1);
			$diditpass = 0;
		}
		$alloutput .= $name . ":\n";
		while(<OUT>) {
			$alloutput .= $_;
		}
		close(OUT);
	}
	CondorTest::debug("Actual output:\n$alloutput");

	if ($outlines ne $alloutput) {
		CondorTest::debug("ERROR:  Actual output does not match expected output:\n$outlines\n");
		$diditpass = 0;
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

$failure = sub
{
	die "Error: DAG is not expected to fail!\n";
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunDagTest() failed\n";
}

