#! /usr/bin/env perl
use CondorTest;
use CondorPersonal;
use Cwd;

CondorPersonal::DebugOff();
Condor::DebugOff();

$testname = 'job_dagman_stork-file-file - Simple dagman/stork job';
$corename = "job_dagman_stork-file-file";
$topdir = getcwd();

print "Working Directory is $topdir\n";

# where am I running
$dummyhost = "gamgee.cs.wisc.edu";
$currenthost = `hostname`;
chomp($currenthost);

system("date");
print "Dummyhost was $dummyhost and really running on $currenthost\n";

$mypid = $$;
$mysaveme = $corename . ".saveme";
system("mkdir $mysaveme");

$mysubmitnm = $corename . $mypid . ".cmd";
$mysubmitnmout = $corename . $mypid . ".cmd.out";
$mysubmitnmlog = $corename . $mypid . ".log";
$mysubmitnmout = $corename . $mypid . ".log";
$mycorenm = $corename . ".cmd";
$mycorenmout = $corename . ".cmd.out";
$mycorenmlog = $corename . ".log";

print "Master PID is $mypid\n";
print "Master PID submit file is $mysubmitnm\n";

my $configloc = CondorPersonal::StartCondor("x_param.storksrvr" ,"local");
my @local = split /:/, $configloc;
my $locconfig = shift @local;
my $locport = shift @local;

print "---local config is $locconfig and local port is $locport---\n";

# find out the directory and cp stork submit file there and 
# build dag file there to submit from there and preserve all logs etc.

my $personaldir = "";
if($locconfig =~ /(.*)\/condor_config/)
{
	$personaldir = $1;
	print "Personal Condor and Dag runtime directory is $personaldir\n";
}


$ENV{CONDOR_CONFIG} = $locconfig;
# submit into stork personal condor
# we can not assume for a dagman test that we have a stork server
# running in the personal condor which is being run for the test suite
# so we setup and run our own.

if( ! -e "job_stork_file-file.in" )
{
	system("date > job_stork_file-file.in");
}

# rather then test a NULL stork data move (--src_url=/dev/null --dest_url=/dev/null)
# we will create a data file and use md5 checksums to verify the file gets correctly
# to its destination before removing the file after the test.

my $storkdatafile = "stork_file-file_data" . $mypid;
system("./x_create_md5data.pl --megs=10 --filenm=$storkdatafile");

# we will move the file via stork to /tmp

my $src_url = $topdir . "/$storkdatafile";
my $dest_url = "/tmp/$storkdatafile";

print "Transfer $src_url to $dest_url\n";
print "Callling ./x_makestorkdag.pl\n";

#my $makeresult = system("./x_makestorkdag.pl --root=$personaldir --dag=dag1 --dagnm=dag1.dag --src_url=/dev/null --dest_url=/dev/null");
my $makeresult = system("./x_makestorkdag.pl --root=$personaldir --dag=dag1 --dagnm=dag1.dag --src_url=$src_url --dest_url=$dest_url");

print "make dag result is <<$makeresult>>\n";

$cmd = "$dagnm";
$testname = 'Condor submit dag - stork transfer test';
$dagman_args = "-v -storklog `condor_config_val LOG`/Stork.user_log";

print "Callling ./x_runstorkdag.pl\n";
$now = getcwd();
print "Calling from here<<$now>>\n";

my $run_result = system("./x_runstorkdag.pl $personaldir/dag1 dag1.dag \"$testname\" 0");
 
print "run dag result is <<$run_result>>\n";

my $data_result = system("./x_test_md5data.pl --oldfile=$src_url --newfile=$dest_url");
print "Result of crafted Stork job is  $data_result\n";

system("rm -f $dest_url*");
system("cp -r $mypid $mysaveme");
system("cp job_stork_file-file.stork* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

my @adarray;
my $status = 1;
my $cmd = "condor_off -master";
$status = CondorTest::runCondorTool($cmd,\@adarray,2);
if(!$status)
{
	print "Test failure due to Condor Tool Failure<$cmd>\n";
	return(1)
}

system("date");

if( $run_result != 0 )
{
	# actual test failed but we allowed cleanup
	print "Stork - Dagman run test failed!\n";
	exit(1);
}

if( $data_result != 0 )
{
	# actual test failed but we allowed cleanup
	print "Stork - Dagman run test worked BUT data check failed!\n";
	exit(1);
}
else
{
	print "Stork test SUCCESS!\n";
}

