#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

## This makes sure that DAGMan correctly prohibits submit files that
## use the new file globbing features when DAGMAN_PROHIBIT_MULTI_JOBS
## is set.

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_submit_glob-B.dag';
$testdesc =  'Condor submit dag - submit glob B test - scheduler U';
$testname = "job_dagman_submit_glob-B";
$dagman_args = "-verbose";

@logfiles = ("job_dagman_submit_glob-B-subA.dag.dagman.out",
	"job_dagman_submit_glob-B-subB.dag.dagman.out",
	"job_dagman_submit_glob-B-subC.dag.dagman.out");


my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log files.
foreach $name (@logfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

# Remove any existing rescue DAGs.
runcmd("rm -f job_dagman_submit_glob-B*.dag.rescue*");

$abnormal = sub 
{
	die "Want to see only submit, execute and failed completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	die "Error: DAG should fail!\n";
};

$failure = sub
{
	CondorTest::debug("DAG failed as expected\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;
	foreach $name (@logfiles) {
		$canopen = open(OUT,"<$name");
		if (! (defined $canopen)) {
			CondorTest::debug("Can not open logfile <$name>:$!\n", 1);
			$diditpass = 0;
		} else {
			$count = 0;
			while (<OUT>) {
				chomp();
				$line = $_;
				if ($line =~ /^.*Submit generated \d job procs; disallowed by DAGMAN_PROHIBIT_MULTI_JOBS setting/ ) {
					CondorTest::debug("$name: $line\n",1);
					if ($count == 0) { $count++; }
				}
				if ($line =~ /^.*Removing any\/all submitted HTCondor jobs\.\.\./) {
					CondorTest::debug("$name: $line\n",1);
					if ($count == 1) { $count++; }
				}
			}
			if ($count ne 2) {
				CondorTest::debug("Missing expected lines in $name\n");
				$diditpass = 0;
			}
		}
	}

	if ($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}

};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunDagTest() failed\n";
}

