#! /usr/bin/env perl
use CondorTest;

$cmd = 'job_core_initialdir_sched.cmd';
$testname = 'condor_submit initialdir works - scheduler U';


system("mkdir -p initd_sched");

#CondorTest::RegisterExitedSuccess( $testname, \&CondorTest::DefaultOutputTest );


$ExitSuccess = sub 
{
	my %info = @_;

	my $goal = "";
	print "Looking for $goal\n";
#	# Pull out requested environment values
	my $logs   = $info{"log"};
	print "Log is $logs\n";
	my $initialdir = $info{"initialdir"};
	print "initialdir is $initialdir\n";
	$goal = "$initialdir" . "/" . "$logs";
	if( ! -s $goal )
	{
		print "Expected logfile not found<$goal>\n";
		die "Initialdir does not contain user log\n";
	}
	# clean up
	print "Expected logfile found<$goal>\n";
	system("rm -rf initd_sched");
};


CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

