#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# This test tests the final DAG node when the DAG succeeds.

# Note: we should check that the jobstate.log file is correct, but I'm
# skipping that for now.  wenger 2011-12-01

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_final-A.dag';
$testdesc =  'Condor submit dag - basic final node test A - scheduler U';
$testname = "job_dagman_final-A";
$dagman_args = "-verbose";

$outfile = "job_dagman_final-A.nodes.out";
$scriptfile = "job_dagman_final-A.scripts.out";

# Note: we must find these lines *in the specified order*.
@node_output_lines = ("  DAG_STATUS=0",
			"  FAILED_COUNT=0",
			"OK done with A_A",
			"  DAG_STATUS=0",
			"  FAILED_COUNT=0",
			"OK done with A_B",
			"  DAG_STATUS=0",
			"  FAILED_COUNT=0",
			"OK done with A_C");

# Note: we must find these lines *in the specified order*.
@script_output_lines = ("  DAG_STATUS=0",
			"  FAILED_COUNT=0",
			"Node A_C Pre",
			"  DAG_STATUS=0",
			"  FAILED_COUNT=0",
			"Node A_C Post");

$statusfile = "job_dagman_final-A.status";
@status_lines = ("DagStatus = 5;.*STATUS_DONE \\(success\\)",
	"Node = \"A_A\";",
	"NodeStatus = 5;.*STATUS_DONE",
	"Node = \"A_B\";",
	"NodeStatus = 5;.*STATUS_DONE",
	"Node = \"A_C\";",
	"NodeStatus = 5;.*STATUS_DONE");

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing output files.
if (-e $outfile) {
	runcmd("rm -f $outfile");
}
if (-e $scriptfile) {
	runcmd("rm -f $scriptfile");
}
if (-e $statusfile) {
	runcmd("rm -f $statusfile");
}

$abnormal = sub 
{
	die "Error: Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Error: Abort event NOT expected\n";
};

$held = sub 
{
	die "Error: Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	# Make sure all expected lines are in the node output file, in the
	# correct order, and there aren't any "extra" lines.
	CondorTest::debug("Checking $outfile\n",1);
	open(CHECK, "<$outfile") ||
			die "Error: Cannot open $outfile: $!\n";
	@lines = <CHECK>;
	close(CHECK);
	$max = $#node_output_lines > $#lines ? $#node_output_lines : $#lines;
	for ($lineindex = 0; $lineindex <= $max; $lineindex++) {
		$line = $lines[$lineindex];
		chomp($line);
		if ($line eq $node_output_lines[$lineindex]) {
			CondorTest::debug("$line\n", 1);
		} else {
			$diditpass = 0;
			CondorTest::debug("Mismatch at line $lineindex: expected <$node_output_lines[$lineindex]>, got <$line>\n", 1);
		}
	}

	# Make sure all expected lines are in the script output file, in the
	# correct order, and there aren't any "extra" lines.
	CondorTest::debug("Checking $scriptfile\n",1);
	open(CHECK, "<$scriptfile") ||
			die "Error: Cannot open $scriptfile: $!\n";
	@lines = <CHECK>;
	close(CHECK);
	$max = $#script_output_lines > $#lines ? $#script_output_lines : $#lines;
	for ($lineindex = 0; $lineindex <= $max; $lineindex++) {
		$line = $lines[$lineindex];
		chomp($line);
		if ($line eq $script_output_lines[$lineindex]) {
			CondorTest::debug("$line\n", 1);
		} else {
			$diditpass = 0;
			CondorTest::debug("Mismatch at line $lineindex: expected <$script_output_lines[$lineindex]>, got <$line>\n", 1);
		}
	}

	# Check the node status file (for gittrac #4209).
	CondorTest::debug("Checking $statusfile\n",1);
	$line = "";
	$passed = 0;
	$canopen = open(OUT,"<$statusfile");
	if (! (defined $canopen)) {
		CondorTest::debug("Can not open node status file<$statusfile>:$!\n",1);
		$diditpass = 0;
	}
	while(<OUT>) {
		chomp();
		$line = $_;
		$target = $status_lines[0];
		if( $line =~ /$target/ ) {
			CondorTest::debug("$name: $line\n",1);
			# Remove the target we just found from the array.
			shift @status_lines;
			if ($#status_lines < 0) {
				last;
			}
		}
	}
	close(OUT);

	if ($#status_lines >= 0) {
		CondorTest::debug("failed missing node status lines:\n");
		foreach $missing (@status_lines) {
			print "  $missing\n";
		}
		$diditpass = 0;
	}

	if($diditpass == 0) {
		die "Error: All expected files and correct output failed\n";
	}
};

$failure = sub
{
	die "Error: DAG is not expected to fail!\n";
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed );
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "Error: $testname: CondorTest::RunTest() failed\n";
}

