#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Cwd;


$topdir = getcwd();

$testdesc =  'job_core_time-deferral-remove_van - vanilla U time deferral-remove';
$testname = "job_core_time-deferral-remove_van";
$cmd = "job_core_time-deferral-remove_van.cmd";
$corename = "job_core_time-deferral-remove_van";

# where am I running
$currenthost = CondorTest::getFqdnHost();
CondorTest::fullchomp($currenthost);

print scalar localtime() . "\n";

$mypid = $$;
$mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

$mysubmitnmlog = $corename . $mypid . ".log" ;
$mysubmitnmerr = $corename . $mypid . ".err" ;
$mysubmitnmout = $corename . $mypid . ".out" ;

$mycorenmlog = $corename . ".log";
$mycorenmerr = $corename . ".err";
$mycorenmout = $corename . ".out";

print "Master PID is $mypid\n";
#print "Master PID submit file is $mysubmitnm\n";

# Edit template config info for signal and location

# get a remote scheduler running (side b)
my $configrem = CondorTest::StartPersonal( "job_core_time-deferral-remove_van", "x_param.timedeferloc" ,"timedeferloc");
my @timedeferloc = split /\+/, $configrem;
my $timedeferlocconfig = shift @timedeferloc;
my $timedeferlocport = shift @timedeferloc;
my $logdir = "";


CondorTest::debug("---local job_core_time-deferral-remove vanilla config is $timedeferlocconfig and remote port is $timedeferlocport---\n",1);

$ENV{CONDOR_CONFIG} = $timedeferlocconfig;

CondorTest::debug("Set config to $timedeferlocconfig\n",1);

my $result = system("./job_core_time-deferral-remove.pl van");
CondorTest::debug("Result of job_core_time-deferral-remove.pl vanilla test  job is  $result\n",1);


system("cp *job_core_time-deferral-remove_van* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmcmdout $mycorenmcmdout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

CondorTest::KillPersonal($timedeferlocconfig);
print scalar localtime() . "\n";

if( $result != 0 )
{
	exit(1);
}

CondorTest::debug("job_core_time-deferral-remove_van SUCCESS\n",1);
exit(0);
