#! /usr/bin/env perl
use CondorTest;

$testname = 'Condor LEAVE_IN_QUEUE policy test - vanilla U';

my $nostatus = CondorTest::verbose_system("job_core_leaveinqueue-false_van.pl");
my $willstatus = CondorTest::verbose_system("job_core_leaveinqueue-true_van.pl");

if($nostatus != 0)
{
	print "LEAVE_IN_QUEUE: failed no trigger test\n";
}

if($willstatus != 0)
{
	print "LEAVE_IN_QUEUE: failed trigger test\n";
}

if(($willstatus != 0) || ($nostatus != 0))
{
	die "Failed one LEAVE_IN_QUEUE test\n";
}


