#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# new test now is a single file and does both local and vanilla universe
# bt 2/13/15

use CondorUtils;
use CondorTest;
use Cwd;
use POSIX;
use Check::SimpleJob;

$topdir = getcwd();
print scalar localtime() . "\n";

$testname = "job_foreach_submit-simple-glob";

# where am I running
$currenthost = CondorTest::getFqdnHost();

$mypid = $$;

my $filedata = '
	this is data for an
	input file.
';

my $counter = 0;
my $datafileswanted = 3;
my $datafilename = "job_foreach_submit-simple-glob";
my $extension = ".tdata1";
my $targetname = "";
my @results = ();
my @extraction = ();
my $extractionsize = 0;

while($counter < $datafileswanted) {
	$targetname = "$datafilename" . "$counter" . "$extension";
	open(FD,">$targetname") or die "Failed to open:$targetname:$!\n";
	print FD "$filedata";
	close(FD);
	$counter += 1;
}

my $submitfile = "
	executable = x_sleep.pl
	arguments = 3
	log = $testname$mypid.log
	transfer_input_files = \$(FILE)
	queue FILE MATCHING (*$extension)
";

my $submitfilename = "$testname$mypid.cmd";
open(SF,">$submitfilename") or die "failed submit file write:$submitfilename:$!\n";
print SF "$submitfile";
close(SF);

my $harvestdatafilename = CondorTest::TempFileName("$testname");
my $cmdtorun = "condor_submit -dry-run $harvestdatafilename $submitfilename";
my $res = system("$cmdtorun");
LoadResults(\@results,$harvestdatafilename);

#runCondorTool("condor_submit -dry-run $submitfilename",\@results,2,{emit_output=>0});

DryExtract(\@results, \@extraction, "TransferInput");

$extractionsize = @extraction;
if($extractionsize ==  $datafileswanted) {
	print "Got $extractionsize as expected\n";
	RegisterResult(1,"test_name",$testname);
} else {
	print "Expected $datafileswanted items GOT $extractionsize\n";
	RegisterResult(0,"test_name",$testname);
}

my $parseerror = 0;
foreach my $line (@extraction) {
	chomp($line);
	#print "got:$line\n";
	if($line =~ /"$datafilename\d+$extension"/) {
	} else {
		$parseerror += 1;
		print "parse error:$line\n";
	}
}
print "Seeing if we got what we expected:";

if($parseerror == 0) {
	print "Great\n";
	RegisterResult(1,"test_name",$testname);
} else {
	print "Bad\n";
	RegisterResult(0,"test_name",$testname);
}


CondorTest::EndTest();
print scalar localtime() . "\n";
my $result = 0;

if( $result != 0 )
{
	exit(1);
}

CondorTest::debug("$testname SUCCESS\n",1);
exit(0);

