#!/usr/bin/env perl
#*******************************************************************************
#*
#* Copyright (C) 2012, Condor Team, Computer Sciences Department,
#* University of Wisconsin-Madison, WI.
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you
#* may not use this file except in compliance with the License.  You may
#* obtain a copy of the License at
#*
#*    http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#*
#*******************************************************************************

use strict;
use warnings;

use CondorUtils;

#
# We don't actually care if the checkpoint succeeds, so we can skip the
# song and dance for determining how to call setarch.  Instead, we just
# need to make sure that the test does not exit with code 0.
#
my $testProgram = "job_ckpt_nscd_std.cndr.exe";
my $rVal = runcmd( "$testProgram Y", { expect_result => \&ANY } );

if( $rVal->{ 'exitcode' } == 0 ) {
    print( "ERROR: program exited successfully instead of (failing to) checkpoint.\n" );
    print( "FAILURE\n" );
    exit( 1 );
}

print( "SUCCESS\n" );
exit( 0 );
