#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_rsc_fread_std.cmd';
$testname = 'Fread Test';

@CondorTest::expected_output = ( 'read 1 items from x_data.in' );

CondorTest::RegisterExitedSuccess( $testname,
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}
