#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

## This tests passing arguments to PRE and POST scripts.

use CondorTest;

$cmd = 'job_dagman_script_args.dag';
$testdesc =  'Condor submit dag - pre/post script arguments test - scheduler U';
$testname = "job_dagman_script_args";
$dagman_args = "-verbose";

@logfiles = ("job_dagman_script_args.dag.dagman.out");
@outfiles = ("job_dagman_script_args-NodeA-Pre.out",
	"job_dagman_script_args-NodeA-Post.out",
	"job_dagman_script_args-NodeB-Pre.out", 
	"job_dagman_script_args-NodeB-Post.out", 
	"job_dagman_script_args-NodeC-Pre.out", 
	"job_dagman_script_args-NodeC-Post.out", 
	"job_dagman_script_args-NodeD-Pre.out",
	"job_dagman_script_args-NodeD-Post.out");
@outlines = ( "<\"Cadel_Evans\"> <0>",
	"<0> <Mark_Cavendish> <Heinrich_Haussler> <0> <[0-9]*\.0>",
	"<'Bernard_Hinault'> <Joop_Zoetemelk> <0>",
	"<0> <Ottavio_Bottechia> <0> <[0-9]*\.0>",
	"<Miguel> <\\\\Indurain> <0>",
	"<0> <Laurent> <Jalabert> <0> <[0-9]*\.0>",
	"<Gilles> <Delion> <Charly> <Mottet> <0>",
	"<0> <Stephen> <Roche> <0> <[0-9]*\.0>");

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log files.
foreach $name (@logfiles) {
	if (-e $name) {
		system("rm -f $name");
	}
}

# Get rid of any existing output files.
foreach $name (@outfiles) {
	if (-e $name) {
		system("rm -f $name");
	}
}

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing, and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	# Check the dagman.out file for successful completion.
	foreach $name (@logfiles) {
		$line = "";
		$passed = 0;
		$canopen = open(OUT,"<$name");
		if( ! (defined $canopen)) {
			CondorTest::debug("Can not open logfile<$name>:$!\n",1);
			$diditpass = 0;
		}
		while(<OUT>) {
			chomp();
			$line = $_;

			if( $line =~ /EXITING WITH STATUS 0/ ) {
				CondorTest::debug("$name: $line\n",1);
				$passed = 1;
			}
		}
		close(OUT);
		if($passed == 1 ) {
			;
		} else {
			CondorTest::debug("FAILED $name: $line\n",1);
			$diditpass = 0;
		}
	}

	# Check the node script output files for proper output.
	for ($filenum = 0; $filenum <= $#outfiles; $filenum++) {
		$name = $outfiles[$filenum];
		$line = "";
		$passed = 0;
		$canopen = open(OUT,"<$name");
		if( ! (defined $canopen)) {
			CondorTest::debug("Can not open logfile<$name>:$!\n",1);
			$diditpass = 0;
		}
		while(<OUT>) {
			chomp();
			$line = $_;

			if( $line =~ /^$outlines[$filenum]/ ) {
				CondorTest::debug("$name: $line\n",1);
				$passed = 1;
			}
		}
		close(OUT);
		if($passed == 1 ) {
			;
		} else {
			CondorTest::debug("FAILED $name: $line\n",1);
			$diditpass = 0;
		}
	}

	if($diditpass == 0) {
		die "All expected files and correct output FAILED\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunDagTest() FAILED\n";
}

