#! /usr/bin/env perl
use CondorTest;

$testname = 'Condor LEAVE_IN_QUEUE policy test - scheduler U';

my $nostatus = CondorTest::verbose_system("job_core_leaveinqueue-false_sched.pl");
my $willstatus = CondorTest::verbose_system("job_core_leaveinqueue-true_sched.pl");

my %listoftests; 
$listoftests{"corename"} = "job_core_leaveinqueue_sched";
$listoftests{"tests"} = [ "job_core_leaveinqueue-true_sched", "job_core_leaveinqueue-false_sched"];
$listoftests{"extensions"} = [ ".cmd", ".cmd.out", ".err", ".out", ".log"];
CondorTest::MergeOutputFiles(\%listoftests);

if($nostatus != 0)
{
	print "LEAVE_IN_QUEUE: failed no trigger test\n";
}

if($willstatus != 0)
{
	print "LEAVE_IN_QUEUE: failed trigger test\n";
}

if(($willstatus != 0) || ($nostatus != 0))
{
	die "Failed one LEAVE_IN_QUEUE test\n";
}


