#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_ckpt_combo-sanity_std.cmd';
$testname = 'Printer Test';
$results = 'job_ckpt_combo-sanity_std.results';

$num_tests = 500;

for( $i=0; $i < $num_tests; $i++ ) {
     push( @expected_error, "set i = $i" );
}

$j = $num_tests - 1;
@expected_results = ( "set i = $j" );

$OutputTest = sub
{
    my %info = @_;

#    -z $info{"output"} ||
#	die "$testname: FAILURE (STDOUT contains data)\n";

    CondorTest::CompareText( $info{"error"}, \@expected_error ) ||
	die "$testname: FAILURE (STDERR doesn't match expected text)\n";

    CondorTest::CompareText( $results, \@expected_results ) || 
	die "$testname: FAILURE ($results doesn't match expected text)\n";
};

CondorTest::RegisterExitedSuccess( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}

