#! /usr/bin/env perl
use CondorTest;

$testname = 'Condor PERIODIC_RELEASE policy test - vanilla U';

my $nostatus = CondorTest::verbose_system("./job_core_perrelease-false_van.pl");
my $willstatus = CondorTest::verbose_system("./job_core_perrelease-true_van.pl");

my %listoftests;
$listoftests{"corename"} = "job_core_perrelease";
$listoftests{"tests"} = [ "job_core_perrelease-false_van", "job_core_perrelease-true_van"];
$listoftests{"extensions"} = [ ".cmd", ".cmd.out", ".err", ".out", ".log"];
CondorTest::MergeOutputFiles(\%listoftests);

if($nostatus != 0)
{
	print "PERIODIC_RELEASE: failed no trigger test\n";
}

if($willstatus != 0)
{
	print "PERIODIC_RELEASE: failed trigger test\n";
}

if(($willstatus != 0) || ($nostatus != 0))
{
	die "Failed one PERIODIC_RELEASE test\n";
}


