#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_rsc_hello_std.cmd';
$testname = 'Hello Test';

$foo = <<"_EOX";
Hello World
Hi there!!!
Goodby World
Normal End Of Job
_EOX

@expected_output = split '\n', $foo;

@expected_error = ( 'Goodby World' );

$results = 'hello.results';
@expected_results = ( 'Hello World' );

$OutputTest = sub
{
    my %info = @_;

   CondorTest::CompareText( $info{"output"}, \@expected_output ) ||
	die "$testname: FAILURE (STDOUT doesn't match expected output)\n";

   CondorTest::CompareText( $info{"error"}, \@expected_error ) || 
	die "$testname: FAILURE (STDERR doesn't match expected text)\n";

   CondorTest::CompareText( $results, \@expected_results ) || 
	die "$testname: FAILURE ($results doesn't match expected text)\n";
};


CondorTest::RegisterExitedSuccess( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: FAILURE (condor_submit failed?)\n";
}

