#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_ckpt_f-printer_std.cmd';
$testname = 'Fortran Printer Test';

$OutputTest = sub
{
    my %info = @_;
    my $output = $info{"output"};
    my $error = $info{"error"};

    -f $error || 
	die "$testname: FAILURE ($error doesn't exist)\n";

    -z $error || 
	die "$testname: FAILURE (STDERR contains data)\n";

    open( OUTPUT, "<$output" ) || die "Can't open $output: $!\n";
    $iter = 0;
    while( <OUTPUT> ) {
	if( /\s*set\s*i\s*=\s*(\d+).*/ ) {
	    $curr = $1;
	    if( $iter != $curr ) {
		die "$testname: FAILURE " . 
		    "(current iteration [$curr] doesn't match expected [$iter])\n";
	    }
	    $iter++;
	} else {
	    $line = $iter + 1;
	    die "$testname: FAILURE (Can't parse output on line $line)\n";
	}
    }
};

CondorTest::RegisterExitedSuccess( $testname, $OutputTest );
CondorTest::RegisterExitedFailure( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
        print "$testname: SUCCESS\n";
        exit(0);
} else {
        die "$testname: CondorTest::RunTest() failed\n";
}

