#!/usr/bin/env perl

use CondorTest;
use File::Path;

$cmd = 'job_core_sh-loop_van.cmd';
$testname = 'Basic shell script loop test';

umask 0;
`chmod 755 job_core_sh-loop_van.sh`;


$foo = <<"_EOX";
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60
Normal End-of-Job
_EOX

@CondorTest::expected_output = split '\n', $foo;

CondorTest::RegisterExitedSuccess( $testname, 
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}

