#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************
##
## This test looks at memory reported in image size plus
## job and machine ads
##
##**************************************************************

use CondorTest;
use CondorUtils;
use Check::SimpleJob;
use Net::Domain qw(hostfqdn);
my $host = hostfqdn();
print "$host\n";


my $firstappend_condor_config = '
	DAEMON_LIST = MASTER,SCHEDD,COLLECTOR,NEGOTIATOR,STARTD
	ALL_DEBUG = 
	NEGOTIATOR_INTERVAL = 5
	NUM_SLOTS = 4
	SUSPEND = FALSE
';
 
my $configfile = CondorTest::CreateLocalConfig($firstappend_condor_config,"memchecker");
my $testname = "job_mem_checker";

CondorTest::StartCondorWithParams(
	condor_name => "memchecker",
	fresh_local => "TRUE",
	condorlocalsrc => "$configfile",
);

my $on_abort = sub {
	CondorTest::debug("Abort from removing sleep 0 jobs.\n",1);
};

my $on_evictedwithoutcheckpoint = sub {
	CondorTest::debug("Evicted Without Checkpoint from removing jobs.\n",1);
};

my $result = 1;
my $running_now = 0;
my $expect_idle = 0;
my $expect_run = 0;
my $checkpslot = "no";

my $on_execute = sub {
};

#Do a couple things before setting currency limits
print "First test basic job\n";
$result = SimpleJob::RunCheck();



$append_submit_commands = '
transfer_input_files = x_job_mem_checker.exe
';

# on this on-execute, check the ads like above
$expect_run = 1;
$expect_idle = 0;
$result = SimpleJob::RunCheck(
	runthis => "x_job_mem_checker.pl",
	test_name => $testname,
	on_abort => $on_abort,
	output => "mem_checker.out",
	error => "mem_checker.err",
	user_log => "mem_checker.log",
	on_execute => $on_execute,
	on_evictedwithoutcheckpoint => $on_evictedwithoutcheckpoint,
	queue_sz => 1,
	should_transfer_files => True,
	when_to_transfer_output => ON_EXIT,
	append_submit_commands => $append_submit_commands,
);
print "******************** Test for correct local resource ClassAds on dynamic slot\n";
if($result == 1) {
	print "ok\n\n\n";
} else {
	print "bad\n\n\n";
}


CondorTest::EndTest();


