executable   = ./job_dagman_vars-B-node.pl
arguments    = $(nodename) $$([DAGParentNodeNames]) $(first) $(second) $(third) $(misc)
# Note: this needs to be vanilla universe for the $$([DAGParentNodeNames])
# expansion to work above.
universe     = vanilla
output       = job_dagman_vars-B-$(nodename).out
error        = job_dagman_vars-B-$(nodename).err
log          = job_dagman_vars-B.log
Notification = NEVER
queue
