#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

## Note: this tests the DAGMan splice/category bug documented in
## gittrac #285.  Also tests for correct name munging of VARS.

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_splice-cat.dag';
$testdesc =  'Condor submit dag - splice/category test - scheduler U';
$testname = "job_dagman_splice-cat";
$dagman_args = "-verbose";

$debug_log = "job_dagman_splice-cat.dag.dagman.out";

my $config = <<CONDOR_TESTREQ_CONFIG;
	DAGMAN_DEBUG = D_TEST
CONDOR_TESTREQ_CONFIG

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log files.
foreach $name (@logfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

$abnormal = sub 
{

	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;
	$locatedexitsuccess = 0;
	$validcats = 1;

	my %expected = (
		'cat0' => [2, 10],
		'+catS' => [4, 2],
		'D0+cat1' => [2, 12],
		'D0+D1+cat2' => [2, 33],
		'D0+D1+cat3' => [2, 22],
		'D0+E1+cat2' => [2, 32],
		'D0+E1+cat3' => [2, 22],
	);
	my @categories = keys %expected;

	open(my $fh, '<', $debug_log) or die "Can not open debug file $debug_log: $!";

	while (my $line = <$fh>) {
		chomp $line;

		if($line =~ /^*.EXITING WITH STATUS 0*.$/) {
			$locatedexitsuccess = 1;
			CondorTest::debug("$line\n", 1);
			last;
		} elsif ($line =~ /^*.CHECK CATEGORY ([a-zA-Z0-9\+]+) (\d+) (\d+)/) {
			if (exists $expected{$1}) {
				$expectednum = $expected{$1}[0];
				$expectedlimit = $expected{$1}[1];
				if ($expectednum != $2 || $expectedlimit != $3) {
					$diditpass = 0;
					CondorTest::debug("Incorrect values for category $1: Total[$2|$expectednum] Limit[$3|$expectedlimit] > KEY[Found|Expected]\n", 1);
				} else {
					@categories = grep { $_ ne $1 } @categories;
				}
			} else {
				$diditpass = 0;
				CondorTest::debug("Unexpected category $1\n", 1);
			}
		}
	}

	close($fh);

	# Did we find a successful DAGMan daemoncore exit line?
	if($locatedexitsuccess == 0) {
		CondorTest::debug("Failed to locate successful daemon exit line\n", 1);
		$diditpass = 0;
	}
	# Did we find all expected categories in log?
	if (@categories) {
		CondorTest::debug("Failed to find all categories: @categories\n", 1);
		$diditpass = 0;
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

