#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Cwd;


$testdesc =  'job_dagman_stork-file-file - Simple dagman/stork job';
$testname = "job_dagman_stork-remove";
$corename = "job_dagman_stork-file-file";
$topdir = getcwd();

CondorTest::debug("Working Directory is $topdir\n",1);

# where am I running
$currenthost = CondorTest::getFqdnHost();
CondorTest::fullchomp($currenthost);

print scalar localtime() . "\n";

$mypid = $$;
$mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

$mysubmitnm = $corename . $mypid . ".cmd";
$mysubmitnmout = $corename . $mypid . ".cmd.out";
$mysubmitnmlog = $corename . $mypid . ".log";
$mysubmitnmout = $corename . $mypid . ".log";
$mycorenm = $corename . ".cmd";
$mycorenmout = $corename . ".cmd.out";
$mycorenmlog = $corename . ".log";

CondorTest::debug("Master PID is $mypid\n",1);
CondorTest::debug("Master PID submit file is $mysubmitnm\n",1);

# generate a running personal condor based on the condor binary
# which we are currently configured to run and return a config_location:port 
# string after starting up that personal condor.

my $configloc = CondorTest::StartPersonal( "job_dagman_stork-remove", "x_param.storksrvr" ,"local");
my @local = split /\+/, $configloc;
my $locconfig = shift @local;
my $locport = shift @local;

CondorTest::debug("---local config is $locconfig and local port is $locport---\n",1);

# find out the directory and cp stork submit file there and 
# build dag file there to submit from there and preserve all logs etc.
# strip off /condor_config.

my $personaldir = "";
if($locconfig =~ /(.*)\/condor_config/)
{
	$personaldir = $1;
	CondorTest::debug("Personal Condor and Dag runtime directory is $personaldir\n",1);
}


$ENV{CONDOR_CONFIG} = $locconfig;

# submit into stork personal condor
# we can not assume for a dagman test that we have a stork server
# running in the personal condor which is being run for the test suite
# so we setup and run our own.

if( ! -e "job_stork_file-file.in" )
{
	system("date > job_stork_file-file.in");
}

CondorTest::debug("Callling ./x_makestorkdag.pl\n",1);

# copy from /dev/random is a stork job which runs forever....
my $makeresult = system("./x_makestorkdag.pl --root=$personaldir --dag=dag1 --dagnm=dag1.dag --src_url=/dev/random --dest_url=/dev/null");

CondorTest::debug("make dag result is <<$makeresult>>\n",1);

$cmd = "$dagnm";
$testdesc =  'Condor submit dag - stork transfer test';
$testname = "job_dagman_stork-remove";
#$dagman_args = "-v -storklog `condor_config_val LOG`/Stork.user_log";
$dagman_args = "-v ";

CondorTest::debug("Callling ./x_runstorkdag.pl\n",1);
$now = getcwd();
CondorTest::debug("Calling from here<<$now>>\n",1);

# pass a timeout so we can remove the dag from the queue and then see
# if dagman correctly removed the "forever" running stork transfer.

my $result = system("./x_runstorkdag.pl $personaldir/dag1 dag1.dag \"$testname\" 30");
 
CondorTest::debug("run dag result is <<$result>>\n",1);

# verify we have a stork job still running after timeout in dag test
# got us control back.

my $cluster = 1;
my @adarray;
my $status = 1;
my $cmd = "stork_status $cluster";
$status = CondorTest::runCondorTool($cmd,\@adarray,2);
if(!$status)
{
	CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",1);
	exit(1)
}

foreach my $line (@adarray)
{
	CondorTest::debug("STORK_STATUS:$line\n",1);
	if($line =~ /status\s*=\s*"processing_request".*$/)
	{
		CondorTest::debug("STORK_STATUS:$line\n",1);
		$result = 0; # good that we have an infinate stork job
	}
}


# remove the dag. condor cluster number for dag just happens to match
# stork dap_id.
$cmd = "condor_rm $cluster";
$status = CondorTest::runCondorTool($cmd,\@adarray,2);
if(!$status)
{
    CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",1);
    exit(1)
}

print scalar localtime() . "\n";
sleep(30); #allow settling time for dag removal ????? how to know remove command has finished?
print scalar localtime() . "\n";

$cmd = "stork_status $cluster";
$status = CondorTest::runCondorTool($cmd,\@adarray,2);
if(!$status)
{
	CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",1);
	exit(1)
}

foreach my $line (@adarray)
{
	CondorTest::debug("STORK_STATUS:$line\n",1);
	if($line =~ /status\s*=\s*"request_removed".*$/)
	{
		CondorTest::debug("STORK_STATUS:$line\n",1);
		$result = 0; # good that we have an infinate stork job
	}
}

system("cp job_stork_file-file.stork* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

CondorTest::KillPersonal($locconfig);
print scalar localtime() . "\n";

if( $run_result != 0 )
{
	# actual test failed but we allowed cleanup
	CondorTest::debug("Stork - Dagman run test failed!\n",1);
	exit(1);
}

CondorTest::debug("job_dagman_stork-remove SUCCESS\n",1);
exit(0);
