#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;


$testdesc =  'Condor PERIODIC_RELEASE policy test - local U';
$testname = "job_core_perrelease_local";
$corename = "job_core_perrelease_local";

# where am I running
$currenthost = CondorTest::getFqdnHost();
CondorTest::fullchomp($currenthost);

print scalar localtime() . "\n";

$mypid = $$;
$mysaveme = $corename . ".saveme";

if($mypid == 0) {
    die "Saveme setup for test failed\n";
}

# get a remote scheduler running (side b)
my $configrem = CondorTest::StartPersonal( "job_core_perrelease_local", "x_param.locperrelease" ,"perrelease_loc");
my @personal = split /\+/, $configrem;
my $personalconfig = shift @personal;
my $personalport = shift @personal;

CondorTest::debug("---personal config is $personalconfig and personal port is $personalport---\n",1);

#Run in this newly created pool
$ENV{CONDOR_CONFIG} = $personalconfig;

my $nostatus = CondorTest::verbose_system("./job_core_perrelease-false_local.pl $mypid");
my $willstatus = CondorTest::verbose_system("./job_core_perrelease-true_local.pl $mypid");

my %listoftests;
$listoftests{"corename"} = "job_core_perrelease_local";
$listoftests{"tests"} = [ "job_core_perrelease-false_local", "job_core_perrelease-true_local"];
$listoftests{"extensions"} = [ ".cmd", ".cmd.out", ".err", ".out", ".log"];
CondorTest::MergeOutputFiles(\%listoftests);

if($nostatus != 0)
{
	CondorTest::debug("PERIODIC_RELEASE: failed no trigger test\n",1);
}

if($willstatus != 0)
{
	CondorTest::debug("PERIODIC_RELEASE: failed trigger test\n",1);
}

system("cp job_core_perrelease-false_local* job_core_perrelease-true_local* job_core_perrelease_local.* $mysaveme");

CondorTest::KillPersonal($personalconfig);
print scalar localtime() . "\n";

if(($willstatus != 0) || ($nostatus != 0))
{
	die "Failed one PERIODIC_RELEASE test\n";
}
CondorTest::debug("job_core_perrelease_local SUCCESS\n",1);
exit(0);
