#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_rsc_ftell_std.cmd';
$testname = 'Ftell Test';

@CondorTest::expected_output =
( 'about to call job_rsc_ftell_std()', 
  'job_rsc_ftell_std succeeds, return value = 0', 
  'job_rsc_ftell_std succeeds, return value = 4' );

CondorTest::RegisterExitedSuccess( $testname,
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}

