#! /usr/bin/env perl
use CondorTest;
#Condor::DebugOn();

$cmd      = 'job_core_holdrelease_sched.cmd';
$testname = 'Jobs properly hold and release - scheduler U';

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

my $alreadydone=0;
my $stat=0;

$execute = sub {
	my %args = @_;
	my $cluster = $args{"cluster"};

	# avoid reentrant death
	if($alreadydone != 0) {
		return true;
	} else {
		$alreadydone = 1;
		CondorTest::RegisterTimed($testname, $timed, 600);
	}
	
	print "Putting cluster $cluster on hold\n";
	my @adarray;
	my $status = 1;
	my $cmd = "condor_hold $cluster";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);
	if($status == 0)
	{
		print "Test failure due to Condor Tool Failure<$cmd>\n";
		exit(1)
	}

};

$abort = sub {
	print "Job is gone now, cool.\n";
};

$hold = sub
{
	my %args = @_;
	my $cluster = $args{"cluster"};

	print "Good. Cluster $cluster is supposed to be held.....\n";
	print "Releasing cluster $cluster\n";
	my @adarray;
	my $status = 1;
	my $cmd = "condor_release $cluster";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);
	if($status == 0)
	{
		print "Test failure due to Condor Tool Failure<$cmd>\n";
		exit(1)
	}
	# must reschedule to get released job out of Inactive and into Running
	$cmd = "condor_reschedule";
	$stat = CondorTest::runCondorTool($cmd,\@adarray,2);
	if($stat == 0)
	{
		print "Test failed - could not reschedule\n";
		exit(1);
	}
};

$release = sub
{
	my %args = @_;
	my $cluster = $args{"cluster"};

	print "Good hold and release both worked! removing job\n";
	$cmd = "condor_rm $cluster";
	$stat = CondorTest::runCondorTool($cmd,\@adarray,2);
	if($stat == 0)
	{
		print "Test worked but runCondorTool $cmd failed\n";
		exit(0);
	}
};

$success = sub
{
	die "Hold/Release/Remove/Abort is expected event trail!\n";
};

$timed = sub
{
	die "Job should have ended by now. Hold/Realease broken!\n";
};

CondorTest::RegisterExecute($testname, $execute);
CondorTest::RegisterAbort($testname, $abort);
CondorTest::RegisterHold($testname, $hold);
CondorTest::RegisterRelease($testname, $release);
CondorTest::RegisterExitedSuccess($testname, $success);

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

