#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_ckpt_getrusage-loop_std.cmd';
$testname = 'Loop and getrusage() Test';

$OutputTest = sub
{
    my %info = @_;
    my $output = $info{"output"};
    my $error = $info{"error"};

    -z $error || 
	die "$testname: FAILURE ($error contains data)\n";

    open( OUTPUT, "<$output" ) || die "Can't open $output: $!\n";

    $lineno = 0;
    $prev_iter = -1;
    $prev_user = 0;
    $prev_sys = 0;

    while( <OUTPUT> ) {

	$lineno++;

	# skip lines that begin with "Checkpointing..."
	next if /Checkpointing\.\.\./;

	# If we see "Normal End of Job" we should be at the end
	if( /(.*)Normal End of Job(.*)/ ) {
	    eof(OUTPUT) || 
		die "$testname: FAILURE (output found after expected end)\n";
	    last;
	}

	# Grab a line.  It should look something like:
	# 0  UserTime = 0.140000  SystemTime = 0.030000
	if( /(\d*)\t\tUserTime = (\d+\.\d+)\tSystemTime = (\d+\.\d+)/ ) {
	    $cur_iter = $1;
	    $cur_user = $2;
	    $cur_sys = $3;
	} else {
	    die "$testname: FAILURE (Can't parse output on line $lineno)\n";
	}

	if( $cur_iter <= $prev_iter ) {
	    die "$testname: FAILURE (line $lineno: " .
		"current iteration [$cur_iter] is <= prev [$prev_iter])\n"; 
	}
	if( $cur_user < $prev_user ) {
	    die "$testname: FAILURE (line $lineno: " .
		"current UserTime [$cur_user] is < prev [$prev_user])\n"; 
	}
	if( $cur_sys < $prev_sys ) {
	    die "$testname: FAILURE (line $lineno: " .
		"current SystemTime [$cur_sys] is < prev [$prev_sys])\n"; 
	}
	$prev_iter = $cur_iter;
	$prev_user = $cur_user;
	$prev_sys = $cur_sys;
    }
};

CondorTest::RegisterExitedSuccess( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 1) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}
