#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_ckpt_open-N-parallel_std.cmd';
$testname = 'Files Test';

$foo = <<"_EOX";
Opened 8 files
About to checkpoint
Returned from checkpoint
OK
About to checkpoint
Returned from checkpoint
OK
Normal End of Job
_EOX

@CondorTest::expected_output = split '\n', $foo;

CondorTest::RegisterExitedSuccess( $testname,
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}
