#! /usr/bin/env perl
use CondorTest;

$testname = 'Jobs complaining cause No FT on when tansfer_executables = true - vanilla U';

my $sanestatus = CondorTest::verbose_system("./x_sanitysubmit.pl");
my $teststatus = CondorTest::verbose_system("./job_filexfer_trans-excut-true_van.pl");

if($sanestatus != 0)
{
        print "job_filexfer_trans-excut-true_van failed sanity submittest\n";
}

if($teststatus != 0)
{
        print "job_filexfer_trans-excut-true_van failed actual test\n";
}

if(($teststatus == 0) && ($sanestatus == 0))
{
        print "Passed job_filexfer_trans-excut-true_van\n";
} else {
		die "Failed job_filexfer_trans-excut-true_van\n";
}

