#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;

$cmd = 'job_ckpt_f-areauc_std.cmd';
$testdesc =  'Fortran Area Under a Curve Test';
$testname = "job_ckpt_f-areauc_std";

$OutputTest = sub {
	my %info = @_;

	$output = $info{"output"};
	open( OUTPUT, "<$output" ) || die "Can't open $output: $!\n";

	# The first line should be SUCCESS or FAILURE
	$line = <OUTPUT>;

	if ((not $line =~ /.*SUCCESS.*/) && 
		(not $line =~ /.*FAILURE.*/))
	{
		close OUTPUT;
		die "$testname: FAILURE (bad output to STDOUT)\n";
	}
	# screw the rest of the lines, if there are any....
	close OUTPUT;
};

CondorTest::RegisterExitedSuccess( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

