#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd_template = "job_core_gcbbasic.template";
$testdesc =  'job_core_gcbbasic - gcb smoke test';
$testname = "job_core_gcbbasic";
$corename = "job_core_gcbbasic";

# where am I running
$currenthost = CondorTest::getFqdnHost();
chomp($currenthost);
$primarycollector = $currenthost;

CondorTest::fullchomp($currenthost);

print scalar localtime() . "\n";

$mypid = $$;
$mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

$mysubmitnm = $corename . $mypid . ".cmd";
$mysubmitnmout = $corename . $mypid . ".cmd.out";
$mysubmitnmlog = $corename . $mypid . ".log";
$mysubmitnmout = $corename . $mypid . ".out";
$mycorenm = $corename . ".cmd";
$mycorenmout = $corename . ".cmd.out";
$mycorenmlog = $corename . ".log";

int "Master PID is $mypid\n";
CondorTest::debug("Master PID submit file is $mysubmitnm\n",1);

# eventually we want to look for clues as to where the
# gcb collect is that we wish to join to dropped as a hint by platform_pre
# glue

$myparamtemplate = "x_param.gcbbasic.template";
$myparam = "x_param.gcbbasic";

open(TEMPL,"<$myparamtemplate") or die "Could not read<$myparamtemplate>:$!\n";
open(PAR,">$myparam") or die "Could not write<$myparam>:$!\n";
while(<TEMPL>) {
	print PAR "$_";
}

my $version = $mypid . "local";
# get a local scheduler running (side a)
my $configloc = CondorTest::StartPersonal( "job_core_gcbbasic", "x_param.gcbbasic" ,$version);
my @local = split /\+/, $configloc;
my $locconfig = shift @local;
my $locport = shift @local;

CondorTest::debug("---local config is $locconfig and local port is $locport---\n",1);

$primarycollector = $primarycollector . ":" . $locport;

$ENV{CONDOR_CONFIG} = $locconfig;

# there is only a master and a schedd here as we
CondorTest::debug("Primary collector for other nodes <<$primarycollector>>\n",1);

CondorTest::debug("sleeping 15\n",1);
sleep(20);
CondorTest::debug("Done sleeping\n",1);

system("condor_status");

CondorTest::debug("sleeping 15\n",1);
sleep(20);
CondorTest::debug("Done sleeping\n",1);

my $forever = CondorTest::verbose_system("./job_core_gcbbasic.pl");
if($forever != 0) {
	CondorTest::debug("Bailing because running job failed to submit\n",1);
	$bail = 1;
}


system("cp *job_core_gcbbasic* $mysaveme");

if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

CondorTest::KillPersonal($locconfig);
print scalar localtime() . "\n";

if( $bail == 1 )
{
    # actual test failed but we allowed cleanup
    exit(1);
}
CondorTest::debug("job_core_gcbbasic SUCCESS\n",1);
exit(0);
