#! /usr/bin/env perl
use CondorTest;

$cmd = 'job_core_priority_van.cmd';
my $datafile = 'job_core_priority_van.data';
$testname = 'condor_submit priority works - vanilla U';

my @sdata =
(
"1",
"8",
"3",
"10",
"5",
"2"
);

my @vdata =
(
"1",
"2",
"3",
"5",
"8",
"10"
);

my @skiplines = ();


my $doonlyonce = "";
my $count = 6;  # have to wait for a 6 to complete


$ExitSuccess = sub 
{
	my %info = @_;

	$count = $count - 1;

	if( $count != 0 )
	{
		return(0);
	}

	CondorTest::CompareText( $datafile, \@vdata, @skiplines );
};

system("rm -rf job_core_priority_van.data");
system("touch job_core_priority_van.data");

CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

