#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

## This makes sure that the -usedagdir flag works correctly.

use CondorTest;

$cmd = 'job_dagman_usedagdir-subdir/job_dagman_usedagdir.dag';
$testdesc =  'Condor submit dag - usedagdir test - scheduler U';
$testname = "job_dagman_usedagdir";
$dagman_args = "-verbose -usedagdir";

@logfiles = ("job_dagman_usedagdir-subdir/job_dagman_usedagdir.dag.dagman.out");

@outfiles = ("job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeA-post.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeA-pre.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeA.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeB-post.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeB-pre.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeB.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeC-post.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeC-pre.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeC.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeD-post.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeD-pre.out",
	"job_dagman_usedagdir-subdir/job_dagman_usedagdir-NodeD.out");


my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log files.
foreach $name (@logfiles) {
	if (-e $name) {
		system("rm -f $name");
	}
}

# Get rid of any existing output files.
foreach $name (@outfiles) {
	if (-e $name) {
		system("rm -f $name");
	}
}

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	foreach $name (@logfiles) {
		$line = "";
		$passed = 0;
		$canopen = open(OUT,"<$name");
		if( ! (defined $canopen)) {
			CondorTest::debug("Can not open logfile<$name>:$!\n",1);
			$diditpass = 0;
		}
		while(<OUT>) {
			chomp();
			$line = $_;
			if( $line =~ /^*.EXITING WITH STATUS 0*.$/ ) {
				$passed = 1;
				CondorTest::debug("$name: $line\n",1);
			}
		}
		close(OUT);
		if($passed == 1 ) {
			;
		} else {
			CondorTest::debug("failed $name: $line\n",1);
			$diditpass = 0;
		}
	}

	foreach $name (@outfiles) {
		if ( ! -e $name ) {
			CondorTest::debug("Missing output file $name!\n");
			$diditpass = 0;
		}
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunDagTest() failed\n";
}

