#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_splice_connect-C.dag';
$testdesc =  'Condor submit dag - test splice pin connections - scheduler U';
$testname = "job_dagman_splice_connect-C";
$dagman_args = "-verbose";

@outfiles = ("job_dagman_splice_connect-C.dag.dagman.out",
	"job_dagman_splice_connect-C.node3.out",
	"job_dagman_splice_connect-C.Splice1+Node0.out",
	"job_dagman_splice_connect-C.Splice1+Node1.out",
	"job_dagman_splice_connect-C.Splice1+Node2.out",
	"job_dagman_splice_connect-C.Splice1+Node3.out",
	"job_dagman_splice_connect-C.Splice1+Node4.out",
	"job_dagman_splice_connect-C.Splice1+Node5.out",
	"job_dagman_splice_connect-C.Splice1+Node6.out",
	"job_dagman_splice_connect-C.Splice2+Node1.out",
	"job_dagman_splice_connect-C.Splice2+Node2.out",
	"job_dagman_splice_connect-C.Splice2+Node3.out",
	"job_dagman_splice_connect-C.Splice2+Node4.out");

# Lines must be *in order* within a given output file.
@expected_output = (
	"Splice2+Node1,Splice2+Node2,Splice2+Node3,Splice2+Node4 \n",
	"\n",
	"Splice1+Node0 \n",
	"Splice1+Node0 \n",
	"Splice1+Node0 \n",
	"Splice1+Node0 \n",
	"Splice1+Node0 \n",
	"Splice1+Node0 \n",
	"Splice1+Node1,Splice1+Node2,Splice1+Node3 \n",
	"Splice1+Node1,Splice1+Node2,Splice1+Node3,Splice1+Node4,Splice1+Node5,Splice1+Node6 \n",
	"Splice1+Node3,Splice1+Node4,Splice1+Node5,Splice1+Node6 \n",
	"Splice1+Node3,Splice1+Node4,Splice1+Node5,Splice1+Node6 \n");

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing output files.
foreach $file (@outfiles) {
	runcmd("rm -f $file") if (-e $file);
}

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$failure = sub 
{
	die "Error: DAG is not expected to fail!\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;
	shift @outfiles; # Get rid of dagman.out
	foreach $file (@outfiles) {
		CondorTest::debug("Checking $file\n",1);
		$canopen = open(OUT, "<$file");
		if (! (defined $canopen)) {
			CondorTest::debug("Cannot open output file <$file>:$!\n",1);
			$diditpass = 0;
		} else {
			$contents = do { local $/; <OUT>; };
			$expected = shift @expected_output;
			if ($contents ne $expected) {
				CondorTest::debug("ERROR: for file <$file> expected <$expected>; found <$contents>\n");
				$diditpass = 0;
			}
		}
	}

	if ($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

