#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;

$cmd = 'job_rsc_hello_std.cmd';
$testdesc =  'Hello Test';
$testname = "job_rsc_hello_std";

$foo = <<"_EOX";
Hello World
Hi there!!!
Goodby World
Normal End Of Job
_EOX

@expected_output = split '\n', $foo;

@expected_error = ( 'Goodby World' );

$results = 'hello.results';
@expected_results = ( 'Hello World' );

$OutputTest = sub
{
    my %info = @_;

   CondorTest::CompareText( $info{"output"}, \@expected_output ) ||
	die "$testname: FAILURE (STDOUT doesn't match expected output)\n";

   CondorTest::CompareText( $info{"error"}, \@expected_error ) || 
	die "$testname: FAILURE (STDERR doesn't match expected text)\n";

   CondorTest::CompareText( $results, \@expected_results ) || 
	die "$testname: FAILURE ($results doesn't match expected text)\n";
};


CondorTest::RegisterExitedSuccess( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    CondorTest::debug("$testname: SUCCESS\n",1);
    exit(0);
} else {
    die "$testname: FAILURE (condor_submit failed?)\n";
}

