#! /usr/bin/env perl
use CondorTest;
use Cwd;
use Sys::Hostname;

Condor::DebugOff();

$cmd = 'job_schedd_job-tracking_van.cmd';
$testname = ' Is Schedd Loosing jobs - scheduler U';


my $pid = $$;
system("mkdir $pid");
my $curcwd = getcwd();
print "current directory is $curcwd\n";

$ExitSuccessBase = sub {
	my %info = @_;

};

my @lines;
my $doonce = 0;

$execute = sub
{
	if($doonce == 0)
	{
		Condor::debug( "Good it is running and we'll start the timer....\n");
		CondorTest::RegisterTimed($testname, $timed, 240);
		$doonce = 1;
	}
};

$success = sub
{
    my %args = @_;
	my $cluster = $args{"cluster"};
	$donecount += 1;
	if( $donecount == $submitcount )
	{
		system("date");
		print "All jobs done now!\n";
	}
	else
	{
		my $left = $submitcount - $donecount;
		my $res = $left % 50;
		if( $res == 0 )
		{
			print "$donecount of $submitcount have completed\n";
		}
	}
};

$submit = sub
{
    my %args = @_;
	my $cluster = $args{"cluster"};
	$submitcount += 1;
};

$timed = sub
{
	my $left = $submitcount - $donecount;
	system("date");
	print "Not all kids found in time!!!!!!!!!!!!< $left left >!!!!!!!!!!!!!!!!!!\n";
	exit(1);
};

CondorTest::RegisterExitedSuccess( $testname, $success );
CondorTest::RegisterExecute($testname, $execute);
CondorTest::RegisterSubmit( $testname, $submit );


system("date");
if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

