#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

## This tests tests DAGMan NOOP nodes.  It's partially a copy of
## job_dagman_rescue_recov, to ensure that NOOP nodes are tested
## for rescue DAGs and recovery mode.

## Note: NOOP Stork nodes are supported, but are not included in
## this test because Stork is not supported on all platforms.

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_noop_node-upper.dag';

$testdesc =  'Condor submit dag - noop node DAG test - scheduler U';
$testname = "job_dagman_noop_node";
$dagman_args = "-verbose";

@logfiles = ("job_dagman_noop_node-lower.dag.dagman.out",
	"job_dagman_noop_node-upper.dag.dagman.out");

@rescuedags = ("job_dagman_noop_node-lower.dag.rescue001",
	"job_dagman_noop_node-lower.dag.rescue002");

@nodeoutput = ( "job_dagman_noop_node-nodeA.out",
	"job_dagman_noop_node-nodeB1-pre.out",
	"job_dagman_noop_node-nodeB1-post.out",
	"job_dagman_noop_node-nodeB2.out",
	"job_dagman_noop_node-nodeB2-pre.out",
	"job_dagman_noop_node-nodeB2-post.out",
	"job_dagman_noop_node-nodeD1.out",
	"job_dagman_noop_node-nodeD2-pre.out",
	"job_dagman_noop_node-nodeD2-post.out",
	"job_dagman_noop_node-subdir/job_dagman_noop_node-nodeD3-pre.out",
	"job_dagman_noop_node-subdir/job_dagman_noop_node-nodeD3-post.out",
	"job_dagman_noop_node-nodeF.out",
	"job_dagman_noop_node-nodeUA.out",
	"job_dagman_noop_node-lower.dag.lib.out",
	"job_dagman_noop_node-nodeUC-pre.out",
	"job_dagman_noop_node-nodeUC-post.out",
	"job_dagman_noop_node-nodeUD-pre.out",
	"job_dagman_noop_node-nodeUD-post.out",
	"job_dagman_noop_node-nodeUE-post.out",
	"job_dagman_noop_node-nodeUF-post.out" );

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log files.
foreach $name (@logfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

# Get rid of the rescue DAGs we should have at the end.
unlink <job_dagman_noop_node-lower.dag.rescue???>;

# Get rid of node output files we should have at the end.
foreach $name (@nodeoutput) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

# Make sure we don't have any lock files hanging around...
unlink <job_dagman_noop_node-*.dag.lock>;

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing, and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	foreach $name (@logfiles) {
		$line = "";
		$cache_state = 0;
		$passed = 0;
		$canopen = open(LOG,"<$name");
		if( ! (defined $canopen)) {
			CondorTest::debug("Can not open logfile<$name>:$!\n",1);
			$diditpass = 0;
		}
		while(<LOG>) {
			chomp();
			$line = $_;

			if( $line =~ /^.*EXITING WITH STATUS 0.*$/ ) {
				$passed = 1;
				CondorTest::debug("$name: $line\n",1);
			} elsif( $line =~ /Assertion ERROR/ ) {
				CondorTest::debug("$name ERROR: $line", 1);
				$diditpass = 0;
			} elsif( $line =~ /Unexpected submit event/ ) {
				CondorTest::debug("$name ERROR: $line", 1);
				$diditpass = 0;
			}
		}
		close(LOG);
		if($passed == 1 ) {
			;
		} else {
			CondorTest::debug("failed $name: $line\n",1);
			$diditpass = 0;
		}
	}

	foreach $name (@rescuedags) {
		if (-e $name) {
			CondorTest::debug("$name: $line\n",1);
		} else {
			CondorTest::debug("failed: missing expected rescue DAG $name\n",1);
			$diditpass = 0;
		}
	}

	foreach $name (@nodeoutput) {
		if (-e $name) {
			CondorTest::debug("$name: $line\n",1);
		} else {
			CondorTest::debug("failed: missing expected output file $name\n",1);
			$diditpass = 0;
		}
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunDagTest() failed\n";
}

