#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;

$cmd = 'job_ckpt_combo-sanity_std.cmd';
$testdesc =  'Printer Test';
$testname = "job_ckpt_combo-sanity_std";
$results = 'job_ckpt_combo-sanity_std.results';

$num_tests = 500;

for( $i=0; $i < $num_tests; $i++ ) {
     push( @expected_error, "set i = $i" );
}

$j = $num_tests - 1;
@expected_results = ( "set i = $j" );

$OutputTest = sub
{
    my %info = @_;

#    -z $info{"output"} ||
#	die "$testname: FAILURE (STDOUT contains data)\n";

    CondorTest::CompareText( $info{"error"}, \@expected_error ) ||
	die "$testname: FAILURE (STDERR doesn't match expected text)\n";

    CondorTest::CompareText( $results, \@expected_results ) || 
	die "$testname: FAILURE ($results doesn't match expected text)\n";
};

CondorTest::RegisterExitedSuccess( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    CondorTest::debug("$testname: SUCCESS\n",1);
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}

