#!/usr/bin/env perl

use CondorTest;

$cmd = 'job_rsc_open-N-serial_std.cmd';
$testname = 'Manyfiles Test';

@CondorTest::expected_output = ( "SUCCESS" );

CondorTest::RegisterExitedSuccess( $testname,
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    print "$testname: SUCCESS\n";
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}

