#! /usr/bin/env perl
use CondorTest;

$cmd      = 'job_filexfer_minus1_van.cmd';
$testname = 'Base file transfer short one input file - vanilla U';

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

my $job = $$;
my $baseoutfile = "submit_filetrans_output" . "$job";
my $outd = "$baseoutfile"."d.txt";
my $oute = "$baseoutfile"."e.txt";
my $outf = "$baseoutfile"."f.txt";
my $outg = "$baseoutfile"."g.txt";
my $outh = "$baseoutfile"."h.txt";
my $outi = "$baseoutfile"."i.txt";
my $outj = "$baseoutfile"."j.txt";

my $alreadydone=0;

$execute = sub {
	my %args = @_;
	my $cluster = $args{"cluster"};

	print "Running $cluster\n";

};

$shadow = sub
{
       my %args = @_;
       my $cluster = $args{"cluster"};
       my $error = $args{"shadowerror"};

       print "Shadow Error: Cluster $cluster: $error\n";
       system("condor_rm $cluster");
       sleep 3;
       print "$testname: SUCCESS\n";
       exit(0);
};

$success = sub
{
	die "Base file transfer job!\n";
	if(!-f "$oute"){ print "$oute failed to arrive\n"; exit(1)};
	if(!-f "$outf"){ print "$outf failed to arrive\n"; exit(1)};
	if(!-f "$outg"){ print "$outg failed to arrive\n"; exit(1)};
};

$abort = sub {
	die "Job is gone now, cool.\n";
};

$timed = sub
{
	die "Job should have ended by now. file transfer broken!\n";
};

# make some needed files. All 0 sized and xxxxxx.txt for
# easy cleanup

my $job = $$;
print "Process Id for this script is  $job\n";
my $basefile = "submit_filetrans_input" . "$job";
my $in = "$basefile".".txt";
my $ina = "$basefile"."a.txt";
my $inb = "$basefile"."b.txt";
my $inc = "$basefile"."c.txt";

my $inputdir = "job_"."$job"."_dir";

system("mkdir -p $inputdir");
system("touch $inputdir/$in");
system("touch $inputdir/$ina");
system("touch $inputdir/$inb");
system("touch $inputdir/$inc");

my $line = "";
my $args = "--job=$job --onesetout ";

# pass pid for output file production
# open submitfile and fix
open(CMD,"<$cmd") || die "Can not open command file: $!\n";
open(NEWCMD,">$cmd.new") || die "Can not open command file: $!\n";
while(<CMD>)
{
	chomp;
	print "$_\n";
	$line = $_;
	if( $line =~ /^\s*input\s*=\s*job_\d+_dir\/([a-zA-Z_]+)\d*\.txt\s*$/)
	{
		my $input = "$1"."$job".".txt";
		print "Input file was $1\n";
		print NEWCMD "input = $inputdir/$input\n"
	}
	elsif( $line =~ /^\s*transfer_input_files\s*=\s*.*$/ )
	{
		print NEWCMD "transfer_input_files = $inputdir/$ina,$inputdir/$inb,$inputdir/$inc\n";
	}
	elsif( $line =~ /^\s*transfer_output_files\s*=\s*.*$/ )
	{
		# this one rquests bogus output file d which is missing
		print NEWCMD "transfer_output_files = $outd,$oute,$outf,$outg\n";
	}
	elsif( $line =~ /^\s*arguments\s*=\s*.*$/)
	{
		print NEWCMD "arguments = $args\n";
	}
	else
	{
		print NEWCMD "$line\n";
	}

}
close(CMD);
close(NEWCMD);
system("mv $cmd.new $cmd");

CondorTest::RegisterExecute($testname, $execute);
CondorTest::RegisterShadow($testname, $shadow);
CondorTest::RegisterAbort($testname, $abort);
CondorTest::RegisterExitedSuccess($testname, $success);
CondorTest::RegisterTimed($testname, $timed, 3600);

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

