#! /usr/bin/env perl
use CondorTest;

$testname = 'Jobs casues submit error from a missing specified input file- vanilla U';

my $sanestatus = CondorTest::verbose_system("./x_sanitysubmit.pl");
my $teststatus = CondorTest::verbose_system("./job_filexfer_input-onegone_van.pl");

if($sanestatus != 0)
{
        print "job_filexfer_input-onegone_van failed sanity submittest\n";
}

if($teststatus != 0)
{
        print "job_filexfer_input-onegone_van failed actual test\n";
}

if(($teststatus == 0) && ($sanestatus == 0))
{
        print "Passed job_filexfer_input-onegone_van\n";
} else {
		die "Failed job_filexfer_input-onegone_van\n";
}

