#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd      = 'job_core_corefiles_van.cmd';
$testdesc =  'Core files limited by coresize = xxxxx - vanilla U';
$testname = "job_core_corefiles_van";


$execute = sub {
	my %args = @_;
	my $cluster = $args{"cluster"};

};

$abort = sub {
	CondorTest::debug("Job aborted, cool.\n",1);
	my $corefile = $info{'core'};
	if( $corefile == undef )
	{
		system("ls -l core*");
		die "Die No Core file\n";
	}
	else
	{
		CondorTest::debug("Corefile is called ---$corefile---\n",1);
		CondorTest::debug("-now finish test for coresize = limits-\n",1);
	}
};

my $execute = sub
{
};

CondorTest::RegisterExitedSuccess($testname, $execute);
CondorTest::RegisterExecute($testname, $execute);
CondorTest::RegisterAbort($testname, $abort);
CondorTest::RegisterExitedAbnormal($testname, $abort);
if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

