#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;

$cmd = 'job_ckpt_io-buffer-async-compressed_std.cmd';
$testdesc =  'job_ckpt_io-buffer-async-compressed_std test';
$testname = "job_ckpt_io-buffer-async-compressed_std";

sub OutputTest
{
    my %info = @_;

    # open file, skip to last line, and close
    open( OUTPUT, "<$info{'output'}" ) || 
	die "error opening \"$info{'output'}\": $!\n";
    while( <OUTPUT> )
    {
	$line = $_;
	CondorUtils::fullchomp $line;
    }
    close OUTPUT;

    # check to see if last line indicated success
    unless( $line =~ /^SUCCESS$/ )
    {
	die "$testname: FAILURE (STDOUT doesn't match expected output)\n";
    }
    return 1;
}

my $on_evictedwithcheckpoint = sub {
	CondorTest::debug("Evicted With Checkpoint expected.\n",1);
	CondorTest::AddCheckpoint();
};

CondorTest::RegisterEvictedWithCheckpoint($testname, $on_evictedwithcheckpoint);
CondorTest::RegisterExitedSuccess( $testname, \&OutputTest );

if( CondorTest::RunTest($testname, $cmd, 1) ) {
    CondorTest::debug("$testname: SUCCESS\n",1);
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}


