#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$testdesc =  'Condor CronTab Test - Local Universe';
$testname = "job_core_crontab_local";
$corename = "job_core_crontab_local";

# where am I running
$currenthost = CondorTest::getFqdnHost();
CondorTest::fullchomp($currenthost);

print scalar localtime() . "\n";

$mypid = $$;
$mysaveme = $corename . ".saveme/$mypid";

if($mypid == 0) {
    die "Saveme setup for test failed\n";
}

# get a remote scheduler running (side b)
my $configrem = CondorTest::StartPersonal( "job_core_crontab_local", "x_param.vancrontab" ,"crontab_van");
my @personal = split /\+/, $configrem;
my $personalconfig = shift @personal;
my $personalport = shift @personal;

CondorTest::debug("---personal config is $personalconfig and personal port is $personalport---\n",1);


#Run in this newly created pool
$ENV{CONDOR_CONFIG} = $personalconfig;

##
## We need to pass what universe we would like to test
##
my $result = CondorTest::verbose_system("./job_core_crontab.pl local");

#save key files
system("cp $corename* $mysaveme");

CondorTest::KillPersonal($personalconfig);
print scalar localtime() . "\n";

if($result != 0)
{
	# actuaal job failed but we allowed cleanup
	exit(1);
}

CondorTest::debug("job_core_crontab_local SUCCESS\n",1);
exit(0);
