#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;

my $cmd = 'job_ckpt_io-async_std.cmd';
my $testdesc =  'Io Test';
my $testname = "job_ckpt_io-async_std";


my $on_evictedwithcheckpoint = sub {
	CondorTest::debug("Evicted With Checkpoint expected.\n",1);
	CondorTest::AddCheckpoint();
};

sub OutputTest
{
    my %info = @_;
	my @lines;
	my @numbers;
	my $number;
	my $cnt;

	# grab the output
	@lines = `cat $info{'output'}`;

	# get rid of newlines & collapse contiguous whitespace into a single space
	map {CondorUtils::fullchomp $_; s/\s+/ /g; } @lines;

	# there should be two lines in the output, a string of numbers and
	# a normal end of job line after it.
	if (scalar(@lines) != 2) {
		CondorTest::debug("STDOUT doesn't match expected output. Wrong line count:\n",1);
		CondorTest::debug("$_\n",1);
		die "Aborting test.";
	}

	# The first line should be a series of numbers separated by spaces
	if ($lines[0] =~ /^[0-9 ]+$/) {
		@numbers = split / /, $lines[0];

		# test the ordering of the numbers to make sure there aren't
		# any that are out of order or duplicated.
		$cnt = 0;
		foreach $number (@numbers)
		{
			# coerce the string $number into a real number....
			if ($number != $cnt) {
				CondorTest::debug("STDOUT doesn't match expected output. ".
					"Numbers aren't contiguous:\n",1);
				CondorTest::debug("$_\n",1);
				die "Aborting test.";
			}
			$cnt++;
		}

	} else {
		CondorTest::debug("STDOUT doesn't match expected output. First line not numbers:\n",1);
		CondorTest::debug("$_\n",1);
		die "Aborting test.";
	}

	# second line should be this exact string.
	if ($lines[1] ne "Normal End Of Job") {
		CondorTest::debug("STDOUT doesn't match expected output. ".
			"Second line not sentinel:\n",1);
		CondorTest::debug("$_\n",1);
		die "Aborting test.";
	}

    return 1;
}

CondorTest::RegisterEvictedWithCheckpoint($testname, $on_evictedwithcheckpoint);
CondorTest::RegisterExitedSuccess( $testname, \&OutputTest );

if( CondorTest::RunTest($testname, $cmd, 1) ) {
    CondorTest::debug("$testname: SUCCESS\n",1);
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}
