#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;
use File::Path;

$cmd = 'job_core_sh-loop_van.cmd';
$testdesc =  'Basic shell script loop test';
$testname = "job_core_sh-loop_van";

umask 0;
`chmod 755 job_core_sh-loop_van.sh`;


$foo = <<"_EOX";
1
2
3
4
5
6
7
8
9
10
11
12
Normal End-of-Job
_EOX

my @expected_output = split '\n', $foo;
CondorTest::SetExpected(\@expected_output);


CondorTest::RegisterExitedSuccess( $testname, 
				   \&CondorTest::DefaultOutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
    CondorTest::debug("$testname: SUCCESS\n",1);
    exit(0);
} else {
    die "$testname: CondorTest::RunTest() failed\n";
}

