#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# Tests a final node in combination with a "DAG" in which there is a cycle.

use CondorTest;
use CondorUtils;

$cmd = 'job_dagman_final-H.dag';
$testdesc =  'Condor submit dag - basic final node test H - scheduler U';
$testname = "job_dagman_final-H";
$dagman_args = "-verbose";

$outfile = "job_dagman_final-H.nodes.out";
$rescuefile = "job_dagman_final-H.dag.rescue001";

# Note: we must find these lines *in the specified order*.
@node_output_lines = ("Job for node H_A",
			 "  DAG_STATUS=0",
			 "  FAILED_COUNT=0",
			 "  OK done with H_A",
			 "Job for node H_C",
			 "  DAG_STATUS=5",
			 "  FAILED_COUNT=0",
			 "  OK done with H_C");

my $killedchosen = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing output files.
if (-e $outfile) {
	runcmd("rm -f $outfile");
}
runcmd("rm -f job_dagman_final-H.dag.rescue*");

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	# Make sure all expected lines are in the node output file, in the
	# correct order, and there aren't any "extra" lines.
	CondorTest::debug("Checking $outfile\n",1);
	open(CHECK, "<$outfile") ||
			die "Cannot open $outfile: $!\n";
	@lines = <CHECK>;
	close(CHECK);
	$max = $#node_output_lines > $#lines ? $#node_output_lines : $#lines;
	for ($lineindex = 0; $lineindex <= $max; $lineindex++) {
		$line = $lines[$lineindex];
		chomp($line);
		if ($line eq $node_output_lines[$lineindex]) {
			CondorTest::debug("$line\n", 1);
		} else {
			$diditpass = 0;
			CondorTest::debug("Mismatch at line $lineindex: expected <$node_output_lines[$lineindex]>, got <$line>\n", 1);
		}
	}

	if (! -e $rescuefile) {
		CondorTest::debug("Expected rescue DAG $rescuefile does not exist\n");
		$diditpass = 0;
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success );
CondorTest::RegisterExecute($testname, $executed );
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

