#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

## This test tests the combination of rescue DAGs and DAG recovery
## mode.  There is a top-level DAG that mainly exists so that the
## lower-level DAG can be automatically re-run when it fails.  The
## lower-level DAG will fail twice, generating two different rescue
## DAGs.  Finally, the third time it is run, it will be put on hold
## and then released by one of its own node jobs, so that it goes
## into recovery mode while running a rescue DAG.  This third run of
## the lower-level DAG should succeed.

use CondorTest;

$cmd = 'job_dagman_rescue_recov-upper.dag';

$testdesc =  'Condor submit dag - rescue/recovery DAG test - scheduler U';
$testname = "job_dagman_rescue_recov";
$dagman_args = "-verbose";

@logfiles = ("job_dagman_rescue_recov-lower.dag.dagman.out",
	"job_dagman_rescue_recov-upper.dag.dagman.out");

@rescuedags = ("job_dagman_rescue_recov-lower.dag.rescue001",
	"job_dagman_rescue_recov-lower.dag.rescue002");

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log files.
foreach $name (@logfiles) {
	if (-e $name) {
		system("rm -f $name");
	}
}

# Get rid of the rescue DAGs we should have at the end.
foreach $name (@rescuedags) {
	if (-e $name) {
		system("rm -f $name");
	}
}

$abnormal = sub 
{
	die "Want to see only submit, execute and successful completion\n";
};

$aborted = sub 
{
	die "Abort event NOT expected\n";
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	CondorTest::debug("submitted: This test will see submit, executing, and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	foreach $name (@logfiles) {
		$line = "";
		$cache_state = 0;
		$passed = 0;
		$canopen = open(LOG,"<$name");
		if( ! (defined $canopen)) {
			CondorTest::debug("Can not open logfile<$name>:$!\n",1);
			$diditpass = 0;
		}
		while(<LOG>) {
			chomp();
			$line = $_;

			if( $line =~ /^*.EXITING WITH STATUS 0*.$/ ) {
				$passed = 1;
				CondorTest::debug("$name: $line\n",1);
			} elsif( $line =~ /Assertion ERROR/ ) {
				CondorTest::debug("$name ERROR: $line", 1);
				$diditpass = 0;
			} elsif( $line =~ /Unexpected submit event/ ) {
				CondorTest::debug("$name ERROR: $line", 1);
				$diditpass = 0;
			}
		}
		close(LOG);
		if($passed == 1 ) {
			;
		} else {
			CondorTest::debug("failed $name: $line\n",1);
			$diditpass = 0;
		}
	}

	foreach $name (@rescuedags) {
		if (-e $name) {
			CondorTest::debug("$name: $line\n",1);
		} else {
			CondorTest::debug("failed: missing expected rescue DAG $name\n",1);
			$diditpass = 0;
		}
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

CondorTest::RegisterExitedSuccess( $testname, $success);
CondorTest::RegisterExecute($testname, $executed);
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunDagTest() failed\n";
}

