#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use strict;
use warnings;

my $cmd = "job_core_compressfiles_std.cmd";
my $input = "job_core_compressfiles_std.data";
my $gzinput = "job_core_compressfiles_std.datain";
my $gzinputgz = "job_core_compressfiles_std.datain.gz";
my $gzoutput = "job_core_compressfiles_std.dataout.gz";
my $output = "job_core_compressfiles_std.dataout";

my $testdesc =  'condor_submit compressfiles works - standard U';
my $testname = "job_core_compressfiles_std";
my $debuglevel = 2;

system("rm -f $gzinput $gzinputgz $gzoutput $output");
system("cp $input $gzinput");
system("gzip $gzinput");


my $ExitSuccess = sub {
	my %info = @_;
	my @input;

	system("gunzip $gzoutput");

	open(OUT, "<$output" ) || die "Can't open $output: $!\n";
	open(IN, "<$input" ) || die "Can't open $input: $!\n";
	# load up inputs in order
	while(<IN>)
	{
		CondorTest::fullchomp($_);
		push @input, $_; # add to beginning
	}
	close(IN);
	while(<OUT>)
	{
		my $in = shift @input;
		CondorTest::fullchomp($_);
		if( $in ne $_ )
		{
			die "Input and output vary! $in ne $_\n";
		}
	}
};


CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",$debuglevel);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

