#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;
use strict;
use warnings;


my $testdesc =  'job_core_niceuser_van - niceuser test';
my $testname = "job_core_niceuser_van";
my $corename = "job_core_niceuser_van";
my $debuglevel = 2;

# where am I running
my $currenthost = CondorTest::getFqdnHost();

print scalar localtime() . "\n";

my $mypid = $$;
my $mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

my $mysubmitnm = $corename . $mypid . ".cmd";
#my $mysubmitnmout = $corename . $mypid . ".cmd.out";
my $mysubmitnmlog = $corename . $mypid . ".log";
my $mysubmitnmout = $corename . $mypid . ".out";
my $mycorenm = $corename . ".cmd";
my $mycorenmout = $corename . ".cmd.out";
my $mycorenmlog = $corename . ".log";

CondorTest::debug("Master PID is $mypid\n",$debuglevel);
CondorTest::debug("Master PID submit file is $mysubmitnm\n",$debuglevel);

my $version = $mypid . "local";
# get a local scheduler running (side a)
my $configloc = CondorTest::StartPersonal( "job_core_niceuser_van", "x_param.niceuser" ,$version);
my @local = split /\+/, $configloc;
my $locconfig = shift @local;
my $locport = shift @local;

CondorTest::debug("---local config is $locconfig and local port is $locport---\n",$debuglevel);

# Ensure previous runs don't pollute our results.
# (Can cause failures)
unlink $mycorenmlog;

my $outcome = system("./job_core_niceuser_van.pl");
#fails due to directory matching pattern
runcmd("cp *job_core_niceuser_van* $mysaveme",{expect_result=>\&ANY});

if( -e "$mysubmitnm" )
{
	runcmd("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	runcmd("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	runcmd("cp $mysubmitnmlog $mycorenmlog");
}

CondorTest::KillPersonal($locconfig);
print scalar localtime() . "\n";

if( $outcome != 0 )
{
	print "job_core_niceuser_van.pl returnes<$outcome>\n";
	# actual test failed but we allowed cleanup
	exit(1);
}

CondorTest::debug("job_core_niceuser_van SUCCESS\n",$debuglevel);
exit(0);
