#! /usr/bin/env perl
use CondorTest;

#Condor::DebugOn();

$cmd = 'job_core_initialdir_van.cmd';
$testname = 'condor_submit initialdir works - vanilla U';

@CondorTest::expected_output =
(
'one',
'two',
'three',
'four',
);

system("mkdir -p initd_van");

CondorTest::RegisterExitedSuccess( $testname, \&CondorTest::DefaultOutputTest );

#CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

