#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd = 'job_core_signal-suicide_sched.cmd';
$testdesc =  'Does condor record signal-death properly? - scheduler U';
$testname = "job_core_signal-suicide_sched";

$died = sub {
	my %info = @_;
	my $expectedsig = $info{"job"}+1;
	my $gotsig      = $info{"signal"};
	if($expectedsig != $gotsig) {
		die "Expecting program to have died by sig $expected but it was $gotsig.\n";
	} else {
		CondorTest::debug("Good, signal $gotsig came through fine.\n",1);
	}
};

$success = sub {
	my %info = @_;
	my $cluster = $info{"cluster"};
	my $job     = $info{"job"};
	die "None of the suiciders should have succeeded! $cluster.$job did.\n";
};


CondorTest::RegisterExitedAbnormal( $testname, $died );
CondorTest::RegisterExitedSuccess( $testname, $success );
CondorTest::RegisterAbort( $testname, sub{} ); # ignore aborts

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

