#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Digest::MD5;
#use strict;
use warnings;

my $stats = 0;

my $cmd = 'job_core_copytospool_van.cmd';
my $testdesc =  'Does copytospool work - vanilla U';
my $testname = "job_core_copytospool_van";
my $debuglevel = 2;

my $aborted = sub {
	my %info = @_;
	my $done;
	CondorTest::debug("Abort event expected as we clear job\n",$debuglevel);
};

my $submitted = sub {
	my %info = @_;
	my $cluster = $info{"cluster"};
	my $program = $info{"executable"};
	my $spool = `condor_config_val SPOOL`;
	CondorTest::fullchomp($spool);

	CondorTest::debug("Checking spool dir --$spool--\n",$debuglevel);
	CondorTest::debug("Executable is $program\n",$debuglevel);
	CondorTest::debug("Transfer job worked..... need to check spool file.\n",$debuglevel);

	CondorTest::debug("MD5 of $program is needed first\n",$debuglevel);

	open(DATA,"<$program") || die "Can't open input file $!\n";
	my $datamd5 = Digest::MD5->new;
	$datamd5->addfile(DATA);
	close(DATA);
	my $hexexemd5 = $datamd5->hexdigest;
	CondorTest::debug("executable md5: $hexexemd5\n",$debuglevel);

	my $spoolfile = $spool . "/cluster$cluster" . ".ickpt.subproc0";
	CondorTest::debug("Spool file should be $spoolfile\n",$debuglevel);
	#system("ls $spool");

	open(DATA1,"<$spoolfile") || die "Can't open input file $!\n";
	my $sdatamd5 = Digest::MD5->new;
	$sdatamd5->addfile(DATA1);
	close(DATA1);
	my $shexexemd5 = $sdatamd5->hexdigest;
	CondorTest::debug("spooled executable md5: $shexexemd5\n",$debuglevel);

	CondorTest::debug("OK remove the job!\n",$debuglevel);

	print "Comparing md5 of original file and copy in spool - ";
	if( $hexexemd5 ne $shexexemd5 )
	{
		print "bad\n";
		die "Spooled executable and executable have DIFFERENT MD5 checksums!!!\n";
	}

	print "ok\n";
	my @adarray;
	my $status = 1;
	my $cmd = "condor_rm $cluster";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);
	if(!$status)
	{
		CondorTest::debug("Test failure due to Condor Tool Failure<$cmd>\n",$debuglevel);
		exit(1)
	}

};

CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterSubmit($testname, $submitted);

if(CondorTest::RunTest($testname, $cmd, 0)) {
	CondorTest::debug("$testname: SUCCESS\n",$debuglevel);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

