#!/usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use CondorTest;

$cmd = 'job_rsc_f-direct-write_std.cmd';
$testname = 'Fortran Direct File I/O Test';

#push( @CondorTest::expected_output,
#	  "  Will open direct access file for reading" );
#push( @CondorTest::expected_output, " T T T" );

$OutputTest = sub {
	my %info = @_;

	$output = $info{"output"};
	open( OUTPUT, "<$output" ) || die "Can't open $output: $!\n";

	$line = <OUTPUT>;
	print "Checking Line: $line";
	if ($line !~ /Will open direct access file for reading/)
	{
		close OUTPUT;
		die "$testname: FAILURE (bad output to STDOUT)\n";
	}

	$line = <OUTPUT>;
	print "Checking Line: $line";
	if ((not $line =~ /T,?\s*T,?\s*T/) && 
		(not $line =~ /3\s*\*\s*T/))
	{
		close OUTPUT;
		die "$testname: FAILURE (bad output to STDOUT)\n";
	}
	close OUTPUT;

};

CondorTest::RegisterExitedSuccess( $testname, $OutputTest );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	print "$testname: SUCCESS\n";
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

