#! /usr/bin/env perl
#testreq: personal
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

# This test checks that negotiator state survives across an HTCondor restart.

use CondorTest;
use CondorUtils;
use Data::Dumper;

$cmd = 'job_negotiator_restart.dag';
$testdesc =  'Test negotiator state across HTCondor restart';
$testname = "job_negotiator_restart";
$dagman_args = "-verbose";

@logfiles = ("job_negotiator_restart.dag.dagman.out");

my $killedchosen = 0;

$wasevicted = 0;

# truly const variables in perl
sub IDLE{1};
sub HELD{5};
sub RUNNING{2};

# Get rid of any existing log files.
foreach $name (@logfiles) {
	if (-e $name) {
		runcmd("rm -f $name");
	}
}

# Make sure we don't have a lock file hanging around -- that would
# goof up the test.
runcmd("rm -f job_negotiator_restart.dag.lock");

$abnormal = sub 
{
	my %info = @_;
	CondorTest::debug("Got Abnormal job exit:\n");
	print Dumper($info);
	die "Abnormal exit was NOT expected - aborting test\n";
};

$aborted = sub 
{
	die "Abort event NOT expected - aborting test\n";
};

$evicted = sub
{
	CondorTest::debug("Good. DAGMan job was evicted<$info{cluster}>\n",1);
	$wasevicted = 1;
};

$held = sub 
{
	die "Held event NOT expected\n";
};

$executed = sub
{
	my %info = @_;

	CondorTest::debug("Good. We need the dag to run<$info{cluster}>\n",1);
};

$submitted = sub
{
	my %info = @_;
	CondorTest::debug("DAG $info{cluster} submitted:\n\tWe should see submit, executing, and successful completion\n",1);
};

$success = sub
{
	CondorTest::debug("executed successfully\n",1);
	CondorTest::debug("Verifying output\n",1);
	$diditpass = 1;

	if (!$wasevicted) {
		CondorTest::debug("DAGMan job was not evicted (this means HTCondor was not restarted); test failed\n",1);
		$diditpass = 0;
	}

	# Check for proper exit in the dagman.out file.
	foreach $name (@logfiles) {
		$line = "";
		$passed = 0;

		$canopen = open(LOG,"<$name");
		if( ! (defined $canopen)) {
			CondorTest::debug("Can not open logfile<$name>:$!\n",1);
			$diditpass = 0;
		}
		while(<LOG>) {
			chomp();
			$line = $_;

			if( $line =~ /^.*EXITING WITH STATUS 0.*$/ ) {
				$passed = 1;
				CondorTest::debug("$name: $line\n",1);
			}
		}
		close(LOG);

		if (!$passed) {
			CondorTest::debug("Missing line in $name\n",1);
			$diditpass = 0;
		}
	}

	if($diditpass == 0) {
		die "All expected files and correct output failed\n";
	}
};

$failure = sub
{
	CondorTest::debug("Test DAG failed\n",1);

	@errfiles = ("job_negotiator_restart-nodeA.err",
		"job_negotiator_restart-nodeB.err",
		"job_negotiator_restart-nodeC.err");
	foreach $name (@errfiles) {
	    open (OUTPUT, "<$name") or die "Can't open error file: $!";
		while (<OUTPUT>) {
			CondorTest::debug("$_",1);
		}
		close (OUTPUT);
	}

	exit(1);
};

CondorTest::RegisterExitedSuccess( $testname, $success );
CondorTest::RegisterExitedFailure( $testname, $failure );
CondorTest::RegisterExecute($testname, $executed );
CondorTest::RegisterExitedAbnormal( $testname, $abnormal );
CondorTest::RegisterAbort( $testname, $aborted );
CondorTest::RegisterEvictedWithoutCheckpoint( $testname, $evicted );
CondorTest::RegisterHold( $testname, $held );
CondorTest::RegisterSubmit( $testname, $submitted );

if( CondorTest::RunDagTest($testname, $cmd, 0, $dagman_args) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

