#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;
use Check::SimpleJob;
use strict;
use warnings;

my $testname = "job_core_niceuser_van";
my $debuglevel = 2;

# where am I running
#my $currenthost = CondorTest::getFqdnHost();
my $pid = $$;

# ---  TESTING STRATEGY ----
#  submit a cluster with 2 procs to a single slot pool
#  proc0 has nice_user=true, proc1 does not
#  verify that proc1 runs before proc0 by having the jobs
#  append a message to a common file, and then reading the file
#  on completion of the cluster
#

print scalar localtime() . "\n";

my $firstappend_condor_config = '
    DAEMON_LIST = MASTER,SCHEDD,COLLECTOR,NEGOTIATOR,STARTD
    NUM_CPUS = 1
    NEGOTIATOR_INTERVAL = 5
';

my $configfile = CondorTest::CreateLocalConfig($firstappend_condor_config,"jobcoreniceuservan");
print "local config file:$configfile\n";

CondorTest::StartCondorWithParams(
    condor_name => "jobcoreniceuservan",
    fresh_local => "TRUE",
    condorlocalsrc => "$configfile",
);

# where am I running
#$currenthost = CondorTest::getFqdnHost();


#my @sdata =
#(
#"1",
#"8",
#"3",
#"10",
#"5",
#"2"
#);

my @vdata =
(
"rude",
"rude",
"nice-user",
"nice-user"
);

my @skiplines = ();
my $datafile = "job_core_niceuser_van$pid.data";


my $doonlyonce = "";
my $count = 4;


my $ExitSuccess = sub 
{
	my %info = @_;

	print "Job Completed.....\n";
	$count = $count - 1;

	print "Count now $count\n";
	if( $count != 0 )
	{
		return(0);
	}

	my $res = CondorTest::CompareText( $datafile, \@vdata, @skiplines );
	if($res == 0) {
		RegisterResult(0, "text_name", "$testname");
	} else {
		RegisterResult(1, "text_name", "$testname");
	}
};

CreateEmptyFile("$datafile");

# this is inserted just before the first queue statement
my $submitextras = '
	nice_user = true
';

# this is inserted after the first queue statement
my $multiqueue = "
	nice_user = false
	arguments = 1 $datafile
	queue
";


SimpleJob::RunCheck(
    runthis=>"x_do_niceuser.pl",
	duration=>'$(accounting_group) ' . $datafile,
	should_transfer_files=>"YES",
	when_to_transfer_output=>"ON_EXIT",
	transfer_input_files=>"$datafile",
	transfer_output_files=>"$datafile",
	on_success=>$ExitSuccess,
	queue_sz=>"accounting_group in (nice-user, rude, rude, nice-user)"
#	append_submit_commands=>"$submitextras",
#	multi_queue=>$multiqueue,
);

CondorTest::EndTest();
print scalar localtime() . "\n";
my $result = 0;

if( $result != 0 )
{
    exit(1);
}

CondorTest::debug("$testname SUCCESS\n",1);
exit(0);
