#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


my @got;
$testname = 'lib_classad - runs prebuilt classad tests from testbin_dir';
$test = "../testbin_dir/test_classads";

system("date");

open(ELOG,"$test 2>&1 |") || die "Could not run test<<$test>>: $!\n";
while(<ELOG>) {
	push  @got, $_;
}
close(ELOG);

my $lastsave = "";
foreach $line (@got) {
	chomp($line);
	$lastsave = $line;
	print "$line\n";
}


if($lastsave =~ /^.*All\s+329\s+tests\s+passed.*$/) {
	print "ClassAd Test passed with 329 successful tests!\n";
} else {
	die "329 tests were expected to pass <$lastsave>\n";
}

