#! /usr/bin/env perl
use CondorTest;
use CondorPersonal;

CondorPersonal::DebugOff();
Condor::DebugOff();

$param_template = "x_param.cputracking-snapshot";
$testname = 'lib_procapi_cputracking-snapshot - CPU Remote usage reporting test ';
$corename = "lib_procapi_cputracking-snapshot";
$mytestnegotiation = "x_secneg_clR_dmnR_secprepostsrc";
$mytestnegotiation_result = "yes";
$mycmdfile = "lib_procapi_cputracking-snapshot.cmd";


# where am I running
$dummyhost = "gamgee.cs.wisc.edu";
$currenthost = `hostname`;
CondorTest::fullchomp($currenthost);

system("date");
print "Dummyhost was $dummyhost and really running on $currenthost\n";

$pid = $$;
$mypid = $pid;
$myvariation = 1;
$mysaveme = $corename . ".saveme";
system("mkdir $mysaveme");
$mypiddir = $mysaveme . "/" . $mypid;
system("mkdir $mypiddir");
#make a symbolic link for personal condor module to use
system("ln -s $mypiddir $mypid");

	#print "$line\n";
	$myparamname = $corename . $mypid . ".param";
	$mysubmitnm = $corename . $mypid . ".cmd";
	$mysubmitnmout = $corename . $mypid . ".cmd.out";
	$mysubmitnmlog = $corename . $mypid . ".log";
	$mysubmitnmout = $corename . $mypid . ".log";
	$mycorenm = $corename . ".cmd";
	$mycorenmout = $corename . ".cmd.out";
	$mycorenmlog = $corename . ".log";

	print "Master PID is $mypid\n";
	print "Master PID submit file is $mysubmitnm\n";

	system("cp $mycmdfile $mysubmitnm");
	system("cp $param_template $myparamname");

	#my $configsec = CondorPersonal::DebugOn();
	my $configsec = CondorPersonal::StartCondor($myparamname ,"cputracking", $mypid);
	my @cputrackingpool = split /\+/, $configsec;
	my $secconfig = shift @cputrackingpool;
	my $secport = shift @cputrackingpool;

	print "---cputracking config is $secconfig and cputrackingpool port is $secport---\n";
	

	$ENV{CONDOR_CONFIG} = $secconfig;
	# submit into local schedd (side a)

	my $result = system("./lib_procapi_cputracking-snapshot.pl  $mycmdfile");
	print "Result of crafted cpu tracking by snapshot job is  $result\n";

	system("cp *$corename* $mysaveme");
	
	if( -e "$mysubmitnm" )
	{
		system("cp $mysubmitnm $mycorenm");
	}

	if( -e "$mysubmitnmout" )
	{
		system("cp $mysubmitnmout $mycorenmout");
	}

	if( -e "$mysubmitnmlog" )
	{
		system("cp $mysubmitnmlog $mycorenmlog");
	}

	my @adarray;
	my $status = 1;
	my $cmd = "condor_off -master";
	$status = CondorTest::runCondorTool($cmd,\@adarray,2);
	if(!$status)
	{
		print "Test failure due to Condor Tool Failure<$cmd>\n";
		exit(1)
	}

	if(!$status)
	{
		print "Test failure due to Condor Tool Failure<$cmd>\n";
		exit(1)
	}

system("date");

if( $result != 0 )
{
	# actual test failed but we allowed cleanup
	exit(1);
}

