#! /usr/bin/env perl 
##**************************************************************
##
## Copyright (C) 1990-2011, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


use strict;

my $allTestsPassed = 0;

open(ELOG,"./classad_unit_tester 2>&1 |") || die "Could not run classad_unit_tester: $!\n";
while(<ELOG>) {
	print $_;
	if (/^Finished with no errors/) {
		$allTestsPassed = 1;
	}
}
close(ELOG);

if ($allTestsPassed == 1) {
	print "classad_unit_tester passed\n";
	exit(0);
} else {
	die "classad_unit_tester failed\n";
}
