#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;
use Check::SimpleJob;
#use Check::CondorLog;
use Check::ProcInfo;

my $configfile = "";
my $ClusterId = 0;
my $testname =  "lib_param_conditionals";


my $firstappend_condor_config = '
';

$configfile = CondorTest::CreateLocalConfig($firstappend_condor_config,"name1");

my $condorinfo =CondorTest::StartCondorWithParams(
	condor_name => "name1",
	fresh_local => "TRUE",
	config_minimal => "TRUE",
	condorlocalsrc => "$configfile",
);

my $unit_test = "x_conditional_params.exe";

if(!(-f "$unit_test")) {
	die "Needed unit_test <$unit_test> not available\n";
}

my $test_status = 0;
$test_status = system("$unit_test");
if($test_status != 0) {
	die "failure: $unit_test returned $test_status\n";
}

print "checking if nesting using condor_config_val\n";

# FIXME: write this part of the test.

CondorTest::RegisterResult(1,{test_name => $testname});

CondorTest::EndTest();
