#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Check::SimpleJob;
use Check::CondorLog;


#testreq: personal
my $config = <<CONDOR_TESTREQ_CONFIG;
  # test with submit daemons using CCB
  PRIVATE_NETWORK_NAME=BAR
  SCHEDD.PRIVATE_NETWORK_NAME=FOO
  SHADOW.PRIVATE_NETWORK_NAME=FOO
  SCHEDD.CCB_ADDRESS = $(COLLECTOR_HOST)
  SHADOW.CCB_ADDRESS = $(COLLECTOR_HOST)
  DAEMON_LIST = MASTER, COLLECTOR, NEGOTIATOR, STARTD, SCHEDD
  COLLECTOR_DEBUG = $(COLLECTOR_DEBUG) D_FULLDEBUG

  USE_SHARED_PORT = FALSE
CONDOR_TESTREQ_CONFIG
#endtestreq

# verify that a job runs
SimpleJob::RunCheck();

# verify that at least one connection was made via CCB
CondorLog::RunCheck(
    daemon => "COLLECTOR",
    match_regexp => "CCB: received 'success' from target daemon"
);

CondorTest::EndTest();
