#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use File::Basename;

my $testname = basename( $0, ".run" );

# Start personal condor.
# This sets the environment variable CONDOR_CONFIG.
my $condor_info = CondorTest::StartPersonal( $testname, "$testname.boot", "local");

my @condor_info = split /\+/, $condor_info;
my $condor_config = shift @condor_info;
my $collector_port = shift @condor_info;
CondorTest::debug("Started personal condor with config $condor_config and collector port $collector_port\n",1);

my $test_status = CondorTest::verbose_system("./$testname.pl");

CondorTest::KillPersonal($condor_config);

if( $test_status != 0 )
{
	exit(1);
}

CondorTest::debug("$testname SUCCESS\n",1);
exit(0);
