#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Cwd;


my $topleveldir = getcwd();
my $name4test = `whoami`;
CondorTest::fullchomp($name4test);
CondorTest::debug("Adjusting mapfile for <$name4test>\n",1);

$param_template = "x_param.protocol-ssl.template";
$testdesc =  'lib_auth_protocol-ssl - Security Protocol SSL Authentication Test';
$testname = "lib_auth_protocol-ssl";
$corename = "lib_auth_protocol-ssl";
$mycustomconfig = "x_secssl_configpostsrc";
$mytestnegotiation = "x_secneg_clR_dmnR_secprepostsrc";
$mytestnegotiation_result = "yes";
$mycmdfile = "lib_auth_protocol-ssl.cmd";
$mysslcerts = "x_lib_auth-ssl_keys.tgz";

$mycafile = "ssl_keys/ca-cert.pem";
$mycadir = "ssl_keys/cadir";
$mycertfile = "ssl_keys/user.cert";
$mykeyfile = "ssl_keys/user.key";

# where am I running
$currenthost = CondorTest::getFqdnHost();
CondorTest::fullchomp($currenthost);

print scalar localtime() . "\n";

$myvariation = 1;

$mypid = $$;
$mysaveme = $corename . ".saveme";

if($mypid == 0) {
	die "Saveme setup for test failed\n";
}

# make sure path exists since we have not called StartPersonal yet
my $saveme = $topleveldir . "/" . $mysaveme;
system("mkdir -p $saveme");
my $lowerlevel = $saveme . "/" . $mypid;
system("mkdir -p $lowerlevel");

$pidleveldir = $topleveldir . "/" . $mysaveme . "/" . $mypid;
print "changing to $pidleveldir\n";
chdir("$pidleveldir");
system("pwd");
system("tar -zxvf ../../$mysslcerts");
chdir("ssl_keys");

$newmap = "condor_mapfile.new";
$oldmap = "condor_mapfile";

open(OLD,"<$oldmap") || die "Can't open mapfile:$!\n";
open(NEW,">$newmap") || die "Can't open new mapfile:$!\n";
$line = "";
while(<OLD>) {
	chomp;
	$line = $_;
	if($line =~ /^SSL\s+(.*)\s+USER$/ ) {
		print NEW "SSL $1 $name4test";
		CondorTest::debug("SSL $1 $name4test\n",1);
	} else {
		print NEW;
	}
}
close(OLD);
close(NEW);
system("mv $oldmap $oldmap.old");
system("mv $newmap $oldmap");

chdir("$topleveldir");

#print "$line\n";
$myparamname = $corename . $mypid . ".param";
$mysubmitnm = $corename . $mypid . ".cmd";
$mysubmitnmout = $corename . $mypid . ".cmd.out";
$mysubmitnmlog = $corename . $mypid . ".log";
$mysubmitnmout = $corename . $mypid . ".log";
$mycorenm = $corename . ".cmd";
$mycorenmout = $corename . ".cmd.out";
$mycorenmlog = $corename . ".log";

CondorTest::debug("Master PID is $mypid\n",1);
CondorTest::debug("Master PID submit file is $mysubmitnm\n",1);

# Edit submit file to submit to scheduler at securitypool (side b) schedd.
my $line;
open(CSUB,">$myparamname") || die "Can't open new submit file $myparamname: $!\n";
open(TPLATE,"<$param_template") || die "Can't open param template $param_template: $!\n";
while(<TPLATE>)
{
	CondorTest::fullchomp($_);
	$line = $_;
	if( $line =~ /^\s*secprepostsrc\s*=\s*.*$/ )
	{
		CondorTest::debug("Setting up for $mytestnegotiation\n",1);
		print CSUB "secprepostsrc = $mytestnegotiation\n";
	}
	else
	{
		CondorTest::debug("template: $line\n",1);
		print CSUB "$line\n";
	}
}
close(TPLATE);
close(CSUB);
sleep 10;

my $configtemplate = $mycustomconfig . ".template";
open(CONFIG,">$mycustomconfig") || die "Can't open new postconfig file $mycustomconfig: $!\n";
open(CONFIGTPLATE,"<$configtemplate") || die "Can't open postconfig template $configtemplate: $!\n";
while(<CONFIGTPLATE>)
{
	$tmp = "";
	CondorTest::fullchomp($_);
	$line = $_;
	if($line =~ /^AUTH_SSL_SERVER_CAFILE\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "AUTH_SSL_SERVER_CAFILE = $tmp\n";
	} elsif($line =~ /^AUTH_SSL_SERVER_CADIR\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "AUTH_SSL_SERVER_CADIR = $tmp\n";
	} elsif($line =~ /^AUTH_SSL_SERVER_CERTFILE\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "AUTH_SSL_SERVER_CERTFILE = $tmp\n";
	} elsif($line =~ /^AUTH_SSL_SERVER_KEYFILE\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "AUTH_SSL_SERVER_KEYFILE = $tmp\n";
	} elsif($line =~ /^AUTH_SSL_CLIENT_CAFILE\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "AUTH_SSL_CLIENT_CAFILE = $tmp\n";
	} elsif($line =~ /^AUTH_SSL_CLIENT_CADIR\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "AUTH_SSL_CLIENT_CADIR = $tmp\n";
	} elsif($line =~ /^AUTH_SSL_CLIENT_CERTFILE\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "AUTH_SSL_CLIENT_CERTFILE = $tmp\n";
	} elsif($line =~ /^AUTH_SSL_CLIENT_KEYFILE\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "AUTH_SSL_CLIENT_KEYFILE = $tmp\n";
	} elsif($line =~ /^CERTIFICATE_MAPFILE\s*=\s*XXXXX(\/.*)$/) {
		$tmp = $pidleveldir . $1;
		print CONFIG "CERTIFICATE_MAPFILE = $tmp\n";
	} else {
		print CONFIG "$line\n";
	}

}
close(CONFIG);
close(CONFIGTPLATE);

my $configsec = CondorTest::StartPersonal( "lib_auth_protocol-ssl", $myparamname ,"protocol", $mypid);
my @securitypool = split /\+/, $configsec;
my $secconfig = shift @securitypool;
my $secport = shift @securitypool;

CondorTest::debug("---security config is $secconfig and securitypool port is $secport---\n",1);
	

$ENV{CONDOR_CONFIG} = $secconfig;
# submit into local schedd (side a)

my $result = system("./x_lib_auth_protocol.pl $mypid \"protocol\" $mytestnegotiation_result $mycmdfile \"ssl\"");
CondorTest::debug("Result of crafted lib_auth_protocol job is  $result\n",1);

system("cp *$corename* $mysaveme");
	
if( -e "$mysubmitnm" )
{
	system("cp $mysubmitnm $mycorenm");
}

if( -e "$mysubmitnmout" )
{
	system("cp $mysubmitnmout $mycorenmout");
}

if( -e "$mysubmitnmlog" )
{
	system("cp $mysubmitnmlog $mycorenmlog");
}

CondorTest::KillPersonal($secconfig);
print scalar localtime() . "\n";

if($result != 0)
{
    # actuaal job failed but we allowed cleanup
    exit(1);
}

CondorTest::debug("lib_auth_protocol-ssl SUCCESS\n",1);
exit(0);
