#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


my @got;
$testdesc =  'lib_sysapi - runs prebuilt sysapi tests from testbin_dir';
$testname = "lib_sysapi";
$test = "../testbin_dir/condor_sysapi";

print scalar localtime() . "\n";

open(ELOG,"$test 2>&1 |") || die "Could not run test<<$test>>: $!\n";
while(<ELOG>) {
	push  @got, $_;
}
close(ELOG);

my $passedtests = "";
my $lastsave = "";
foreach $line (@got) {
	chomp($line);
	$lastsave = $line;
	#print "$line\n";
	if($line =~ /^Failed\s+tests\s+=\s+(\d+).*$/) {
		if($1 != 0) {
			print "Sysapi failed $1 test(s)\n";
			foreach $outline (@got) {
				print "Error: Sysapi out: $outline\n";
			}
			exit(1);
		} else {
			print "Sysapi passed $passedtests tests\n";
			exit(0);
		}
	} elsif($line =~ /^Passed\s+tests\s+=\s+(\d+).*$/) {
		$passedtests = $1;
	} elsif($line =~ /^.*Failed.*$/) {
		print "$line\n";
	}
}


