#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;
use Check::SimpleJob;
#use Check::CondorLog;
use Check::ProcInfo;

my $configfile = "";
my $ClusterId = 0;
my $testname =  "lib_python_bindings";


# my $firstappend_condor_config = '
# 	DAEMON_LIST = MASTER,SCHEDD,COLLECTOR,NEGOTIATOR,STARTD
# 	NUM_CPUS = 5
# 	SLOT1_CPU_AFFINITY = 0
# 	SLOT2_CPU_AFFINITY = 1
# 	SLOT3_CPU_AFFINITY = 2
# 	SLOT4_CPU_AFFINITY = 3
# 	SLOT5_CPU_AFFINITY = 4
# 	SLOT5_IsGeneralPurposeSlot = False
# 	START = ($(START)) \
# 		&& ((TARGET.RequiresTypeB =?= TRUE && MY.SlotID == 5) \
# 		  || (TARGET.RequiresTypeB =!= TRUE && MY.SlotID != 5))
# 	ALL_DEBUG = 
# ';

# $configfile = CondorTest::CreateLocalConfig($firstappend_condor_config,"name1");

# my $condorinfo =CondorTest::StartCondorWithParams(
# 	condor_name => "name1",
# 	fresh_local => "TRUE",
# 	condorlocalsrc => "$configfile",
# );

# print "We know this about the just started personal condor <$condorinfo>\n";

# my $sleepforever = '
# 	universe = vanilla
# 	executable = x_sleep.pl
# 	log = $sleepforeverlog
# 	notification = never
# 	arguments = 0
# 	queue
# ';

#in build and test, we have a different location for the built python modules for
# HTCondor - set_env("LD_LIBRARY_PATH","$base_dir/condor/bin:$base_dir/condor/lib/python:$ENV{LD_LIBRARY_PATH}");
if(!(exists $ENV{LD_LIBRARY_PATH})) {
	$ENV{LD_LIBRARY_PATH} = "../../release_dir/lib/python";
} else {
	$ENV{LD_LIBRARY_PATH} = "$ENV{LD_LIBRARY_PATH}:../../release_dir/lib/python";
}
#print "First test basic job\n";
#SimpleJob::RunCheck(
	#runthis => "python",
	#duration => "htcondor_tests.py",
	#test_name => $testname,
	#should_transfer_files => "NO",
#);
my $result = 0; # assume good

$result = system("htcondor_tests.py -v"); 

if($result == 0) {
	print "Got good results, outputs follow\n";
	# lets look at the test output
	my @pythonout = `htcondor_tests.py`;
	foreach my $line (@pythonout) {
		print "$line";
	}
}

CondorTest::RegisterResult(1,{test_name => $testname});

$result = system("classad_tests.py -v"); 
CondorTest::RegisterResult(1,{test_name => $testname});

CondorTest::EndTest();

