#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;

$cmd = 'lib_userlog.cmd';
$testdesc =  'Test user log - write all events and expect to read the same';
$testname = "lib_userlog";


my @expected_output =
(
'Job Submited.........',
'Job Remote Error.........',
'Job Executed.........',
'Job Execution Error.........',
'Job Checkpointed.........',
'Job ABORTED by user.........',
'Job Evicted.........',
'Job Terminated.........',
'Node Terminated .........',
'Post Script Terminated.........',
'Job Globus Submit.........',
'Job Globus Submit Failed.........',
'Globus Resource Up.........',
'Globus Resource Down.........',
'Job Image Size Changed.........',
'Job Shadow Exception.........',
'Job Suspended.........',
'Job Unsuspended.........',
'Job Held.........',
'Job Released.........',
'Job Node Execute.........',
'DONE',
);

CondorTest::SetExpected(\@expected_output);

system("rm -f local.log");
my $stats = system("./x_write_joblog.exe");
if($stats != 0)
{
	if( -e "x_write_joblog.exe" )
	{
		die "Write Log... failed.....\n";
	}
	else
	{
		die "Build failed and x_write_joblog.exe does not exist\n";
	}
}

$ExitSuccess = sub {
};


CondorTest::RegisterExitedSuccess( $testname, \&CondorTest::DefaultOutputTest );
#CondorTest::RegisterExitedSuccess( $testname, $ExitSuccess );

if( CondorTest::RunTest($testname, $cmd, 0) ) {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
} else {
	die "$testname: CondorTest::RunTest() failed\n";
}

