#! /usr/bin/env perl

my @got;
$testname = 'lib_unit_tests - runs prebuilt unit tests from testbin_dir';
$test = "../testbin_dir/condor_unit_tests";

system("date");

open(ELOG,"$test 2>&1 |") || die "Could not run test<<$test>>: $!\n";
while(<ELOG>) {
	push  @got, $_;
}
close(ELOG);

my $objects = "";
my $total = 0;
my $passed = 0;
my $failed = 0;
my $aborted = 0;
my $skipped = 0;

foreach $line (@got) {
	chomp($line);
	if($line =~ /^.*Total\s+Tested\s+Objects:\s+(\d+).*$/) {
		$objects = $1;
	} elsif($line =~ /^.*Total\s+Unit\s+Tests:\s+(\d+).*$/) {
		$total = $1;
	} elsif($line =~ /^.*Passed\s+Unit\s+Tests:\s+(\d+).*$/) {
		$passed = $1;
	} elsif($line =~ /^.*Failed\s+Unit\s+Tests:\s+(\d+).*$/) {
		$failed = $1;
	} elsif($line =~ /^.*Aborted\s+Unit\s+Tests:\s+(\d+).*$/) {
		$aborted = $1;
	} elsif($line =~ /^.*Skipped\s+Unit\s+Tests:\s+(\d+).*$/) {
		$skipped = $1;
	} else {
		#print "$line\n";
	}
}

print "There were $total tests including $objects objects\n";
if($total == $passed) {
	print "Tests passed($passed) ALL did pass so Success\n";
	print "Failed($failed) / Aborted($aborted) / Skipped($skipped) \n";
} else {
	print "Tests passed($passed) NOT ALL did pass so Failure\n";
	die "Failed($failed) / Aborted($aborted) / Skipped($skipped) \n";
}

exit(0);
