#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2013, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Check::SimpleJob;

my $append_condor_config = '
  DAEMON_LIST = MASTER,SCHEDD,COLLECTOR,NEGOTIATOR,STARTD
  SHADOW = $(SBIN)/condor_shadow_s
';

CondorTest::StartCondorWithParams(
    append_condor_config => $append_condor_config
);

# run a job and look at shadow memory usage
my $append_submit_commands = '
   +WantIOProxy = true
   executable = x_shadow_mem_usage.pl
   arguments = shadow_s
';
my $on_execute = sub {
  my %info = @_; # contains cluster,job,sinful,host
  CondorTest::debug("Job $info{cluster} Executing on $^O.. getting shadow memory usage",1);
  CondorTest::runcmd("condor_who -verbose");
};
SimpleJob::RunCheck(
  # append_submit_commands=>$append_submit_commands
  # ,duration=>5
  # ,on_execute=>$on_execute
);

CondorTest::EndTest();
