#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Condor;
use Cwd;


my $remoteschedd = $ARGV[0];
CondorTest::debug("Using <<$remoteschedd>> for a remote schedd\n",1);

Condor::DebugOn();

$topdir = getcwd();

$testdesc =  'Condor soap test ';
$testname = "soap_job_tests";

@adarray;
@bdarray;
$status = 1;

$status = CondorTest::verbose_system("tar -zxf x_soap_job_tests.tar.gz");

if($status != 0)
{
	CondorTest::debug("SOAP_JOB_TESTS: failed to untar tests\n",1);
}

chdir("soaptests");
$wherenow = getcwd();

CondorTest::debug("CURRENTLY in <<<$wherenow>>>\n",1);

my $pathcmd = `echo $topdir\/soaptests\/lib\/*.jar | tr ' ' ':'`;
CondorTest::fullchomp($pathcmd);
CondorTest::debug("pathcmd so far: $pathcmd\n",1);
my $cpath = $ENV{CLASSPATH} = "$topdir/soaptests:$topdir/soaptests/condor:.:$topdir/soaptests/birdbath:$pathcmd";
CondorTest::debug("CLASSPATH=$cpath\n",1);


my $cmd = "condor_status -schedd -l | grep MyAddress";
$status = CondorTest::runCondorTool($cmd,\@adarray,200);

foreach $name (@bdarray) {
	CondorTest::debug("$name\n",1);
	$myaddress = $name;
}

system("which java");

my $host;
system("which java");
if($remoteschedd eq "") {
	CondorTest::debug("Soap test locally\n",1);
	my $cmd = "condor_status -schedd -constraint \"HasSOAPInterface=?=TRUE\" -l | grep MyAddress";
	$status = CondorTest::runCondorTool($cmd,\@adarray,800);

	if($status != 1)
	{
		CondorTest::debug("SOAP_JOB_TESTS: failed to find <MyAddress>, status for rrunCondorTool is <$status>\n",1);
		my $cmd = "condor_status -schedd -l ";
		$status = CondorTest::runCondorTool($cmd,\@adarray,200);
		foreach $name (@adarray) {
			CondorTest::debug("$name\n",1);
			$myaddress = $name;
		}
		die "$testname: failed\n";
	}

	foreach $name (@adarray) {
		CondorTest::debug("$name\n",1);
		$myaddress = $name;
	}

	$myaddress =~ /^.*\"<(.*)>\".*$/;
	CondorTest::debug("Take this: $1\n",1);
	$host = $1;
} else {
	CondorTest::debug("Soap test to <<$remoteschedd>>\n",1);
	$host = $remoteschedd;
}
$cmd = "java -classpath $cpath -DSCHEDD_ENDPOINT=http://$host ScheddTestSuite";
$status = CondorTest::verbose_system($cmd);

if($status != 0) {
	die "$testname: failed\n";
} esle {
	CondorTest::debug("$testname: SUCCESS\n",1);
	exit(0);
}
