#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use Condor;
use Cwd;


my $remoteschedd = $ARGV[0];
print "Using <<$remoteschedd>> for a remote schedd\n";

Condor::DebugOn();

$topdir = getcwd();

$testname = 'Condor soap test ';

@adarray;
@bdarray;
$status = 1;

$status = CondorTest::verbose_system("tar -zxf x_soap_job_tests.tar.gz");

if($status != 0)
{
	print "SOAP_JOB_TESTS: failed to untar tests\n";
}

chdir("soaptests");
$wherenow = getcwd();

print "CURRENTLY in <<<$wherenow>>>\n";

my $pathcmd = `echo $topdir\/soaptests\/lib\/*.jar | tr ' ' ':'`;
CondorTest::fullchomp($pathcmd);
print "pathcmd so far: $pathcmd\n";
my $cpath = $ENV{CLASSPATH} = "$topdir/soaptests:$topdir/soaptests/condor:.:$topdir/soaptests/birdbath:$pathcmd";
print "CLASSPATH=$cpath\n";


my $cmd = "condor_status -schedd -l | grep MyAddress";
$status = CondorTest::runCondorTool($cmd,\@adarray,200);

foreach $name (@bdarray) {
	print "$name\n";
	$myaddress = $name;
}

system("which java");

my $host;
system("which java");
if($remoteschedd eq "") {
	print "Soap test locally\n";
	my $cmd = "condor_status -schedd -constraint \"HasSOAPInterface=?=TRUE\" -l | grep MyAddress";
	$status = CondorTest::runCondorTool($cmd,\@adarray,800);

	if($status != 1)
	{
		print "SOAP_JOB_TESTS: failed to find <MyAddress>, status for rrunCondorTool is <$status>\n";
		my $cmd = "condor_status -schedd -l ";
		$status = CondorTest::runCondorTool($cmd,\@adarray,200);
		foreach $name (@adarray) {
			print "$name\n";
			$myaddress = $name;
		}
		die "$testname: failed\n";
	}

	foreach $name (@adarray) {
		print "$name\n";
		$myaddress = $name;
	}

	$myaddress =~ /^.*\"<(.*)>\".*$/;
	print "Take this: $1\n";
	$host = $1;
} else {
	print "Soap test to <<$remoteschedd>>\n";
	$host = $remoteschedd;
}
$cmd = "java -classpath $cpath -DSCHEDD_ENDPOINT=http://$host ScheddTestSuite";
$status = CondorTest::verbose_system($cmd);

if($status != 0) {
	die "$testname: failed\n";
} esle {
	print "$testname: SUCCESS\n";
	exit(0);
}
