#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2020, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
##
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
##
##    http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorTest;
use CondorUtils;

my $iswindows = CondorUtils::is_windows();

my $reldir = `condor_config_val release_dir`; chomp $reldir;
my $pathsep = ':';
my $relpy = "$reldir/lib/python3";
if ($iswindows) { $relpy = "$reldir\\lib\\python3"; $pathsep = ';'; }

my $pythonpath = "";
if (exists($ENV{PYTHONPATH})) {
    $pythonpath = $ENV{PYTHONPATH};
    print "\texisting PYTHONPATH=$pythonpath\n";
    if (index($reldir,$pythonpath) != -1) {
        print "\tadding $relpy to PYTHONPATH\n";
        $ENV{PYTHONPATH} = "$relpy$pathsep$pythonpath";
    }
} else {
    print "\tsetting PYTHONPATH to $relpy\n";
    $ENV{PYTHONPATH} = $relpy;
}

my $rv = runCommandCarefully( undef, 'python3', '-m', 'pytest', 'test_htcondor_dags' );
exit $rv->{"exitcode"}
