#! /usr/bin/env perl
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************

use CondorUtils;
use CondorTest;

my @got;
$testdesc =  'async_freader_tests - runs unit tests of MyAsyncFileReader file reader class';
$testname = "lib_async_fread";
$test = "async_freader_tests";
if (CondorUtils::is_windows()) { $test .= ".exe"; }

TLOG "Generating test data files\n";
my @lines = `$test -generate-test-files`;

TLOG "Running tests\n";

open(ELOG,"$test -v 2>&1 |") || die "Could not run test<<$test>>: $!\n";
while(<ELOG>) {
	push  @got, $_;
	print $_;
}
close(ELOG);

foreach $line (@got) {
	chomp($line);
}

print "\n";
print "[$0]\n";

exit(0);
