#!/usr/bin/env perl

use strict;
use warnings;

use CondorTest;

my $rv = system( 'test_sinful' );

my $testname = "test_sinful";
print "test_sinful binary returning:$rv\n";
if( $rv == 0 ) {
	print "value 0 so registering a success\n";
	RegisterResult( 1, "test_name" => $testname );
} else {
	print "value:$rv so registering a failure\n";
	RegisterResult( 0, "test_name" => $testname );
}

EndTest();
#endtest never returns unless called with some arg(any)
