/* condor legal shit */

#include "condor_common.h"
#include "command_strings.h"

struct Translation {
	char *name;
	int number;
};

struct Translation DCTranslation[] = {
	{ "QMGMT_CMD", QMGMT_CMD }, 
	{ "CONTINUE_FRGM_JOB", CONTINUE_FRGN_JOB },
	{ "CONTINUE_CLAIM", CONTINUE_CLAIM },
	{ "SUSPEND_FRGN_JOB", SUSPEND_FRGN_JOB },
	{ "SUSPEND_CLAIM", SUSPEND_CLAIM },
	{ "CKPT_FRGN_JOB", CKPT_FRGN_JOB },
	{ "DEACTIVATE_CLAIM", DEACTIVATE_CLAIM },
	{ "KILL_FRGN_JOB", KILL_FRGN_JOB },
	{ "DEACTIVATE_CLAIM_FORCIBLY", DEACTIVATE_CLAIM_FORCIBLY },
	{ "LOCAL_STATUS", LOCAL_STATUS },
	{ "LOCAL_STATISTICS", LOCAL_STATISTICS },
	{ "PERMISSION", PERMISSION },
	{ "SET_DEBUG_FLAGS", SET_DEBUG_FLAGS },
	{ "PREEMPT_LOCAL_JOBS", PREEMPT_LOCAL_JOBS },
	{ "RM_LOCAL_JOB", RM_LOCAL_JOB },
	{ "START_FRGN_JOB", START_FRGN_JOB },
	{ "AVAILABILITY", AVAILABILITY },
	{ "NUM_FRGN_JOBS", NUM_FRGN_JOBS },
	{ "STARTD_INFO", STARTD_INFO },
	{ "SCHEDD_INFO", SCHEDD_INFO },
	{ "NEGOTIATE", NEGOTIATE },
	{ "SEND_JOB_INFO", SEND_JOB_INFO },
	{ "NO_MORE_JOBS", NO_MORE_JOBS },
	{ "JOB_INFO", JOB_INFO },
	{ "GIVE_STATUS", GIVE_STATUS },
	{ "RESCHEDULE", RESCHEDULE },
	{ "PING", PING },
	{ "NEGOTIATOR_INFO", NEGOTIATOR_INFO },
	{ "GIVE_STATUS_LINES", GIVE_STATUS_LINES },
	{ "END_NEGOTIATE", END_NEGOTIATE },
	{ "REJECTED", REJECTED },
	{ "X_EVENT_NOTIFICATION", X_EVENT_NOTIFICATION },
	{ "RECONFIG", RECONFIG },
	{ "GET_HISTORY", GET_HISTORY },
	{ "UNLINK_HISTORY_FILE", UNLINK_HISTORY_FILE },
	{ "UNLINK_HISTORY_FILE_DONE", UNLINK_HISTORY_FILE_DONE },
	{ "DO_NOT_UNLINK_HISTORY_FILE", DO_NOT_UNLINK_HISTORY_FILE },
	{ "SEND_ALL_JOBS", SEND_ALL_JOBS },
	{ "SEND_ALL_JOBS_PRIO", SEND_ALL_JOBS_PRIO },
	{ "REQ_NEW_PROC", REQ_NEW_PROC },
	{ "PCKPT_FRGN_JOB", PCKPT_FRGN_JOB },
	{ "SEND_RUNNING_JOBS", SEND_RUNNING_JOBS },
	{ "CHECK_CAPABILITY", CHECK_CAPABILITY },
	{ "GIVE_PRIORITY", GIVE_PRIORITY },
	{ "MATCH_INFO", MATCH_INFO },
	{ "ALIVE", ALIVE },
	{ "REQUEST_CLAIM", REQUEST_CLAIM },
	{ "REQUEST_SERVICE", REQUEST_SERVICE },
	{ "RELEASE_CLAIM", RELEASE_CLAIM },
	{ "RELINQUISH_SERVICE", RELINQUISH_SERVICE },
	{ "VACATE_SERVICE", VACATE_SERVICE },
	{ "ACTIVATE_CLAIM", ACTIVATE_CLAIM },
	{ "PRIORITY_INFO", PRIORITY_INFO },
	{ "PCKPT_ALL_JOBS", PCKPT_ALL_JOBS },
	{ "VACATE_ALL_CLAIMS", VACATE_ALL_CLAIMS },
	{ "GIVE_STATE", GIVE_STATE },
	{ "SET_PRIORITY", SET_PRIORITY },
	{ "GIVE_CLASSAD", GIVE_CLASSAD },
	{ "GET_PRIORITY", GET_PRIORITY },
	{ "GIVE_REQUEST_AD", GIVE_REQUEST_AD },
	{ "RESTART", RESTART },
	{ "DAEMONS_OFF", DAEMONS_OFF },
	{ "DAEMONS_ON", DAEMONS_ON },
	{ "MASTER_OFF", MASTER_OFF },
	{ "CONFIG_VAL", CONFIG_VAL },
	{ "RESET_USAGE", RESET_USAGE },
	{ "SET_PRIORITYFACTOR", SET_PRIORITYFACTOR },
	{ "RESET_ALL_USAGE", RESET_ALL_USAGE },
	{ "DAEMONS_OFF_FAST", DAEMONS_OFF_FAST },
	{ "MASTER_OFF_FAST", MASTER_OFF_FAST },
	{ "GET_RESLIST", GET_RESLIST },
	{ "ATTEMPT_ACCESS", ATTEMPT_ACCESS },
	{ "VACATE_CLAIM", VACATE_CLAIM },
	{ "PCKPT_JOB", PCKPT_JOB },
	{ "DAEMON_OFF", DAEMON_OFF },
	{ "DAEMON_OFF_FAST", DAEMON_OFF_FAST },
	{ "DAEMON_ON", DAEMON_ON },
	{ "GIVE_TOTALS_CLASSAD", GIVE_TOTALS_CLASSAD },
	{ "DUMP_STATE", DUMP_STATE },
	{ "DC_SIGSUSPEND", DC_SIGSUSPEND },
	{ "DC_SIGCONTINUE", DC_SIGCONTINUE },
	{ "DC_SIGSOFTKILL", DC_SIGSOFTKILL },
	{ "DC_SIGHARDKILL", DC_SIGHARDKILL },
	{ "DC_SIGPCKPT", DC_SIGPCKPT },
	{ "DC_BASE", DC_BASE },
	{ "DC_RAISESIGNAL", DC_RAISESIGNAL },
	{ "DC_PROCESSEXIT", DC_PROCESSEXIT },
	{ "DC_CONFIG_PERSIST", DC_CONFIG_PERSIST },
	{ "DC_CONFIG_RUNTIME", DC_CONFIG_RUNTIME },
	{ "DC_RECONFIG", DC_RECONFIG },
	{ "DC_OFF_GRACEFUL", DC_OFF_GRACEFUL },
	{ "DC_OFF_FAST", DC_OFF_FAST },
	{ "DC_CONFIG_VAL", DC_CONFIG_VAL },
	{ "DC_CHILDALIVE", DC_CHILDALIVE },
	{ "DC_FETCH_LOG", DC_FETCH_LOG },
	{ "FILETRANSFER_BASE", FILETRANSFER_BASE },
	{ "FILETRANS_UPLOAD", FILETRANS_UPLOAD },
	{ "FILETRANS_DOWNLOAD", FILETRANS_DOWNLOAD },
	{ "PW_BASE", PW_BASE },
	{ "PW_SETPASS", PW_SETPASS },
	{ "PW_GETPASS", PW_GETPASS },
	{ "PW_CLEARPASS", PW_CLEARPASS },
	{ "DCSHADOW_BASE", DCSHADOW_BASE },
	{ "SHADOW_UPDATEINFO", SHADOW_UPDATEINFO },
	{ "TAKE_MATCH", TAKE_MATCH },
	{ "MPI_START_COMRADE", MPI_START_COMRADE },
	{ "NULL", 0 }
};

struct Translation CollectorTranslation[] = {
	{ "UPDATE_STARTD_AD", UPDATE_STARTD_AD },
	{ "UPDATE_SCHEDD_AD", UPDATE_SCHEDD_AD },
	{ "UPDATE_MASTER_AD", UPDATE_MASTER_AD },
	{ "UPDATE_GATEWAY_AD", UPDATE_GATEWAY_AD },
	{ "UPDATE_CKPT_SRVR_AD", UPDATE_CKPT_SRVR_AD },
	{ "QUERY_STARTD_ADS", QUERY_STARTD_ADS },
	{ "QUERY_SCHEDD_ADS", QUERY_SCHEDD_ADS },
	{ "QUERY_MASTER_ADS", QUERY_MASTER_ADS },
	{ "QUERY_GATEWAY_ADS", QUERY_GATEWAY_ADS },
	{ "QUERY_CKPT_SRVR_ADS", QUERY_CKPT_SRVR_ADS },
	{ "QUERY_STARTD_PVT_ADS", QUERY_STARTD_PVT_ADS },
	{ "UPDATE_SUBMITTOR_AD", UPDATE_SUBMITTOR_AD },
	{ "QUERY_SUBMITTOR_ADS", QUERY_SUBMITTOR_ADS },
	{ "INVALIDATE_STARTD_ADS", INVALIDATE_STARTD_ADS },
	{ "INVALIDATE_SCHEDD_ADS", INVALIDATE_SCHEDD_ADS },
	{ "INVALIDATE_MASTER_ADS", INVALIDATE_MASTER_ADS },
	{ "INVALIDATE_GATEWAY_ADS", INVALIDATE_GATEWAY_ADS },
	{ "INVALIDATE_CKPT_SRVR_ADS", INVALIDATE_CKPT_SRVR_ADS },
	{ "INVALIDATE_SUBMITTOR_ADS", INVALIDATE_SUBMITTOR_ADS },
	{ "UPDATE_COLLECTOR_AD", UPDATE_COLLECTOR_AD },
	{ "QUERY_COLLECTOR_ADS", QUERY_COLLECTOR_ADS },
	{ "INVALIDATE_COLLECTOR_ADS", INVALIDATE_COLLECTOR_ADS },
	{ "QUERY_HIST_STARTD", QUERY_HIST_STARTD },
	{ "QUERY_HIST_STARTD_LIST", QUERY_HIST_STARTD_LIST },
	{ "QUERY_HIST_SUBMITTOR", QUERY_HIST_SUBMITTOR },
	{ "QUERY_HIST_SUBMITTOR_LIST", QUERY_HIST_SUBMITTOR_LIST },
	{ "QUERY_HIST_GROUPS", QUERY_HIST_GROUPS },
	{ "QUERY_HIST_GROUPS_LIST", QUERY_HIST_GROUPS_LIST },
	{ "QUERY_HIST_SUBMITTORGROUPS", QUERY_HIST_SUBMITTORGROUPS },
	{ "QUERY_HIST_SUBMITTORGROUPS_LIST", QUERY_HIST_SUBMITTORGROUPS_LIST },
	{ "QUERY_HIST_CKPTSRVR", QUERY_HIST_CKPTSRVR },
	{ "QUERY_HIST_CKPTSRVR_LIST", QUERY_HIST_CKPTSRVR_LIST },
	{ "UPDATE_LICENSE_AD", UPDATE_LICENSE_AD },
	{ "QUERY_LICENSE_ADS", QUERY_LICENSE_ADS },
	{ "INVALIDATE_LICENSE_ADS", INVALIDATE_LICENSE_ADS },
	{ "UPDATE_STORAGE_AD", UPDATE_STORAGE_AD },
	{ "QUERY_STORAGE_ADS", QUERY_STORAGE_ADS },
	{ "INVALIDATE_STORAGE_ADS", INVALIDATE_STORAGE_ADS },
	{ "QUERY_ANY_ADS", QUERY_ANY_ADS },
	{ NULL, 0 }
};

static char * get_name_from_num( int num, struct Translation *table ) {

	if ( num < 0 ) return NULL;

	int i, found = FALSE;

	for ( i=0 ; (table[i].name != NULL) ; i++ ) {
		if ( table[i].number == num ) {
			found = TRUE;
			break;
		}
	}

	if ( found ) {
		return table[i].name;
	} else {
		return NULL;
	}
}

static int get_num_from_name( char * command, struct Translation *table ) {

	if ( !command ) return -1;

	int i, found = FALSE;
	
	for ( i=0 ; (table[i].name != NULL) ; i++ ) {
		if ( !stricmp ( table[i].name, command ) ) {
			found = TRUE;
			break;
		}
	}

	if ( found ) {
		return table[i].number;
	} else {
		return -1;
	}
}

char * get_command_string( int num ) {
	return get_name_from_num(num,DCTranslation);
}

int get_command_num( char * command ) {
	return get_num_from_name(command,DCTranslation);
}

char * get_collector_command_string( int num ) {
	return get_name_from_num(num,CollectorTranslation);
}

int get_collector_command_num( char * command ) {
	return get_num_from_name(command,CollectorTranslation);
}






