#!/bin/sh
# This script builds the new ClassAd library
# It is meant to be given to the Condor external build system
# It is unlikely that anyone will want to use it. 
# This script is renamed to something like build_classads-0.9.7

##### Configure and Build ClassAds #####
./configure --enable-namespace --prefix $PACKAGE_INSTALL_DIR
if [ $? -ne 0 ]
then
    echo "Configure failed"
    exit 1
fi

make
if [ $? -ne 0 ]
then
    echo "Build failed"
    exit 1
fi

##### Test the ClassAd build #####
./classad_unit_tester
if [ $? -ne 0 ]
then
    echo "Unit tests failed"
    exit 2
fi

./classad_functional_tester functional_tests.txt
if [ $? -ne 0 ]
then
    echo "Functional tests failed"
    exit 2
fi

##### Install the ClassAd build #####
make install
if [ $? -ne 0 ]
then
    echo "Install failed"
    exit 3
fi

exit 0
