#ifndef __CLASSAD_FEATURES_H_
#define __CLASSAD_FEATURES_H_

#define COLLECTIONS
/*#define EXPERIMENTAL*/

#ifndef CLASSAD_DISTRIBUTION
#define CLASSAD_DEPRECATED
#endif

/*#define ENABLE_SHARED_LIBRARY_FUNCTIONS*/

#endif 
