#ifndef CREDD_CONSTANTS_H
#define CREDD_CONSTANTS_H

#define CREDD_SUCCESS 0

#define CREDD_CREDENTIAL_NOT_FOUND 1
#define CREDD_ERROR_CREDENTIAL_ALREADY_EXISTS 2
#define CREDD_ERROR_NOT_AUTHORIZED 3
#define CREDD_UNABLE_TO_STORE 4

#endif
