#!/usr/bin/env perl

######################################################################
# Submit-side NMI build system infrastructure to cleanup platform
# specific input for completd test jobs.  All we have to do is 
# remove the architecture-dependent results.tar.gz file 
# after we know we do not need it.
######################################################################

use Cwd;

# autoflush our STDOUT
$| = 1;

my $BaseDir = getcwd();

print "Currently in $BaseDir which contains the following:\n";
system("ls -l");

my $results = "results.tar.gz";
-f $results || die "platform_post: $results does not exist!\n";

if( ($ENV{NMI_PLATFORM} =~ /winnt/) ) {
    print "No platform_post work for windows\n";
    print "All steps completed successfully\n";
    exit 0;
}

# Finally, blow away anything still in public and the results.tar.gz
print "Removing all other arch-dependent data\n";
system( "rm -rf $results" );
if( $? ) {
    die "'rm -rf $results' failed with status $?\n";
}

exit 0;
