#!/bin/sh

# $Id: remote_post_always,v 1.1.2.3 2004-06-24 19:52:43 wright Exp $

# Condor implementation of NMI test infrastructure interface
# Simple wrapper to source the environment file and spawn the
# corresponding perl script for a given stage of the test.

ENV_FILE=setup_test_env

# include the environment info from the pre-script
if [ ! -f $ENV_FILE ]; then
    echo "$ENV_FILE does not exist!"
    exit 1
fi
. $ENV_FILE

exec ./test_post_always.pl $*
