#!/bin/bash

prog=${0##*/}

fail () {
    echo "$prog:" "$@" >&2
    exit 1
}


# Pool password; used for PASSWORD auth or for the collector to generate tokens from.
if [[ -f /root/secrets/pool_password ]]; then
    umask 077
    install -o root -g root -m 0600 -D /root/secrets/pool_password /etc/condor/passwords.d/POOL ||\
        fail "/root/secrets/pool_password found but unable to copy"
    umask 022
fi

# A token.
if [[ -f /root/secrets/token ]]; then
    umask 077
    install -o condor -g condor -m 0600 -D /root/secrets/token /etc/condor/tokens.d/token ||\
        fail "/root/secrets/token found but unable to copy"
    umask 022
fi


# vim:et:sw=4:sts=4:ts=8
