#!/bin/sh
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


# Usage: import_links directory obj_file...
#
# Import a set of ".o" files from the given directory as a set of
# symbolic links.

if [ $# -lt 2 ]
then
	echo Usage $0 directory obj_file ...
fi

DIR=$1
shift

while [ $# -gt 0 ]
do
	SRC=${DIR}/$1
	DST=$1

	if ls ${DST} > /dev/null 2>&1
	then
		:
	else			
		# doesn't exist - create the symlink
		echo ln -s ${SRC} ${DST}
		ln -s ${SRC} ${DST}
	fi

	shift
done
exit 0
