#!/bin/csh -f
##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


# Usage: import_links directory obj_file...
#
# Import a set of ".o" files from the given directory as a set of
# symbolic links.

if( $#argv < 2 ) then
	echo Usage $0 directory obj_file ...
endif

set DIR = $1
shift

while ($#argv)
	set SRC = ${DIR}/${argv[1]} 
	set DST = ${argv[1]}

		# Check to see that the target is a ".o" file
#	if( ${DST:e} != o ) then
#		echo ${DST}: Not an object file
#		exit 1
#	endif

	if( ! -e ${DST} ) then			# doesn't exist - create the symlink
		echo ln -s ${SRC} ${DST}
		ln -s ${SRC} ${DST}
#	else if( ! -l ${DST} ) then		# does exist - make sure it is a symlink
#		echo Warning: ${DST} - not a symbolic link
	endif

	shift
end
exit 0
