#!/usr/bin/env perl

##/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
##
## Condor Software Copyright Notice
## Copyright (C) 1990-2006, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
##
## This source code is covered by the Condor Public License, which can
## be found in the accompanying LICENSE.TXT file, or online at
## www.condorproject.org.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
## IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
## WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
## FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
## HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
## MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
## ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
## PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
## RIGHT.
##
##***************************Copyright-DO-NOT-REMOVE-THIS-LINE**/


# Configuration variables
$file = "requirements.txt";

# Check args
$type = $ARGV[0];
$name = $ARGV[1];
$comp = $ARGV[2];
$value = $ARGV[3];
if( ! ($type && $name && $comp && $value) ) {
    usage();
}
# Build the proper requirement clause
if( $type eq "string" ) {
    $req = "$name $comp \"$value\"";
} elsif ( $type =~ /(int|float|bool)/ ) {
    $req = "$name $comp $value";
} else { 
    fprintf STDERR "ERROR: The type \"$type\" is not recognized.\n", 
    "You must use one of \"string\", \"bool\", \"int\", or \"float\"\n";
    usage();
}

if( -f $file ) {
    # Harder, have to append the new requirements...
    # TODO
    die "Error: $file already exists.  I don't know how to ", 
    "deal with that.\n";
} else {
    # Easy, just create the new filel
    open( OUT, ">$file" ) || die "Can't open $file: $!\n";
    print OUT "Requirements\t= $req\n";
    close OUT;
}

sub usage {
    print STDERR "Usage: $0 [type] [name] [comparison] [value]\n";
    exit(1);
}
