#!/bin/sh

IS_BOSCO=`condor_config_val IS_BOSCO`
echo "$IS_BOSCO" | grep -q -i true 
if [ $? != 0 ] ; then
    echo "Please source the bosco.[sh|csh] script first."
fi

# Generate the password file, if it doesn't already exist
bosco_passwd=`condor_config_val SEC_PASSWORD_FILE`
if [ ! -e $bosco_passwd ]; then 
    random_string=`echo $RANDOM | md5sum | awk '{print $1}'`
    condor_store_cred -p $random_string -f $bosco_passwd
fi

condor_master
if [ $? == 0 ] ; then
    echo "BOSCO Started"
else
    echo "ERROR: BOSCO not started."
fi

