#!/usr/bin/env perl

##/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
##
## Condor Software Copyright Notice
## Copyright (C) 1990-2006, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
##
## This source code is covered by the Condor Public License, which can
## be found in the accompanying LICENSE.TXT file, or online at
## www.condorproject.org.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
## IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
## WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
## FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
## HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
## MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
## ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
## PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
## RIGHT.
##
##***************************Copyright-DO-NOT-REMOVE-THIS-LINE**/


# Simple perl script to find the arch/opsys of the local system, and
# create a symlink to the file given as an argument which contains
# them.  
# 6/15/00 - Written by Derek Wright <wright@cs.wisc.edu>


$target = shift || die "Must specify a target name\n";

# Try to make sure we can find condor_config_val
$ENV{PATH} = "$ENV{PATH}:./condor_tools";
$ENV{PATH} = "$ENV{PATH}:../condor_tools";
$ENV{PATH} = "$ENV{PATH}:../../condor_tools";
$ENV{PATH} = "$ENV{PATH}:../../../condor_tools";

$arch = `condor_config_val arch`;
$opsys = `condor_config_val opsys`;

chomp($arch);
chomp($opsys);

$arch || die "Can't find arch\n";
$opsys || die "Can't find opsys\n";

$name = "$target.$opsys.$arch";

unlink( $name );
symlink( $target, $name ) || die "Can't create symlink $name -> $target: $!\n";

