#!/usr/bin/env sh

##**************************************************************
##
## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
## 
## Licensed under the Apache License, Version 2.0 (the "License"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at
## 
##    http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##**************************************************************


# This script is run as startd cron job and emits classad for existance of
# alive HDFS daemon on a given machine. This information can then be consumed
# by a Hadoop MapReduce job to schedule task trackers on machines which are more
# probable to host data-files.

DATANODE_STRING="DataNode"
NAMENODE_STRING="NameNode"
ishdfs=0

ps ux |grep $DATANODE_STRING|grep -v "grep" &> /dev/null
res=$?

if [ $res == 0 ]; then
  echo "datanode = 1"
  ishdfs=1
fi

ps ux |grep $NAMENODE_STRING|grep -v "grep" &> /dev/null
res=$?

if [ $res == 0 ]; then
  echo "namenode = 1"
  ishdfs=1
fi

if [ $ishdfs == 1 ]; then
  echo "hdfs = 1"
fi

