#! /usr/bin/env perl

##/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
##
## Condor Software Copyright Notice
## Copyright (C) 1990-2006, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
##
## This source code is covered by the Condor Public License, which can
## be found in the accompanying LICENSE.TXT file, or online at
## www.condorproject.org.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
## IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
## WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
## FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
## HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
## MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
## ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
## PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
## RIGHT.
##
##***************************Copyright-DO-NOT-REMOVE-THIS-LINE**/

#! /usr/bin/perl -w
use strict;
# use warnings;

# Machine info list
my ($MachineInfo) = "/common/usr/share/Info/machineinfo";
if ( defined( $ENV{MACHINE_INFO} ) )
{
    $MachineInfo = $ENV{MACHINE_INFO};
}

# Parse command line...
if ( $#ARGV == 0 )
{
    $MachineInfo = $ARGV[0];
}
elsif ( $#ARGV > 0 )
{
    print STDERR "usage: $0 [machinefile]\n";
    exit 1;
}

# Open the file...
die "can't read '$MachineInfo'" if (! open ( IN, $MachineInfo ) );
while ( <IN> )
{
    chomp;
    next if (! /\|/ );
    s/\s+\|/|/g;
    my ( $Host, $Room, $User, $Sponsor, $OS, $bldging, $Arch ) = split( /\|/ );
    print "$Host;$Room;$User;$Sponsor;$OS;$Arch\n";
}
