#!/bin/sh 
#  THIS SCRIPT IS BEST VIEWED WITH TAB STOPS IN YOUR EDITOR AT 4 SPACES
#	Author Todd Tannenbaum, 6/97

############################Copyright-DO-NOT-REMOVE-THIS-LINE##
#
# Condor Software Copyright Notice
# Copyright (C) 1990-2004, Condor Team, Computer Sciences Department,
# University of Wisconsin-Madison, WI.
#
# This source code is covered by the Condor Public License, which can
# be found in the accompanying LICENSE.TXT file, or online at
# www.condorproject.org.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
# FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
# HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
# MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
# ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
# PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
# RIGHT.
#
############################Copyright-DO-NOT-REMOVE-THIS-LINE##


# First, make sure we can find condor_config_val.  If not, print 
# out an error message so the user can fix the problem, instead of
# having condor_compile fail in mysterious ways.
CONDOR_LIBDIR=`condor_config_val LIB 2> /dev/null`
if [ $? != 0 ]; then
    echo "ERROR: Cannot execute condor_config_val"
    echo "You must put the directory that contains condor_config_val"
    echo "in your \$PATH for condor_compile to work."
    exit 1
fi

# Here are the default paths/directories to use.
# These defaults can be overidden with command-line args.
# Customize these if desired.  The defaults provided should be
# correct for most installations, however.

CONDOR_LIBDIR=`condor_config_val LIB`
CONDOR_CLIB=$CONDOR_LIBDIR/libcondorsyscall.a
STATIC_ZLIB=$CONDOR_LIBDIR/libz.a
CONDOR_ZCLIB=$CONDOR_LIBDIR/libcondorzsyscall.a
CONDOR_RT0=$CONDOR_LIBDIR/condor_rt0.o
CONDOR_CPLUS=$CONDOR_LIBDIR/libcondorc++support.a
CONDOR_LD_DIR=$CONDOR_LIBDIR
CONDOR_SPECIAL_CLIB=/not-there-bull

# if I am on a linux box, determine where I should be looking
LINUX_LIB=
if [ `uname` = "Linux" ]; then
	if [ -f /lib/libc-2.2* ]; then
		LINUX_LIB="glibc22"
	elif [ -f /lib/libc-2.1* ]; then
		LINUX_LIB="glibc21"
	elif [ -f /lib/libc-2.0* ]; then
		LINUX_LIB="glibc20"
	else
		LINUX_LIB="libc5"
	fi
fi

# --------------------------------------------------

# Tell our "ld" to link to with the Condor libs
CONDOR_COMPILE=yes
export CONDOR_COMPILE

# Handle any command-line args
while [ A = A ]
do
	if [ $# = 0 ]; then
		break;
	fi


	if [ $1 = "-condor_syscall_lib" ]; then
		shift
		CONDOR_SPECIAL_CLIB=$1
		shift
		continue
	fi

	if [ $1 = "-condor_rt0" ]; then
		shift
		CONDOR_RT0=$1
		shift
		continue
	fi

	if [ $1 = "-condor_c++_support" ]; then
		shift
		CONDOR_CPLUS=$1
		shift
		continue
	fi

	if [ $1 = "-condor_ld_dir" ]; then
		shift
		CONDOR_LD_DIR=$1
		shift
		continue
	fi

	if [ $1 = "-condor_standalone" ]; then
		#
		# This option is ignored.  Standalone checkpointing
		# has the same build procedure as standard jobs now.
		# This option is kept for compatibility.
		#
		shift
		continue
	fi

	if [ $1 = "-condor_lib" ]; then
		shift
		CONDOR_LIBDIR=$1
		shift
		# Reset anything based off of the libdir by default
		CONDOR_CLIB=$CONDOR_LIBDIR/libcondorsyscall.a
		CONDOR_ZCLIB=$CONDOR_LIBDIR/libcondorzsyscall.a
		STATIC_ZLIB=$CONDOR_LIBDIR/libz.a
		CONDOR_RT0=$CONDOR_LIBDIR/condor_rt0.o
		CONDOR_CPLUS=$CONDOR_LIBDIR/libcondorc++support.a
		CONDOR_LD_DIR=$CONDOR_LIBDIR
		continue
	fi

	# if we made it here, there are no more command-line options
	break
done

# if these files exist, then keep them, otherwise append the correct lib dir
# this is so a developer using make release can still use the libs
if [ `uname` = "Linux" ]; then
	if [ ! -f "$CONDOR_CLIB" ]; then
		CONDOR_CLIB=$CONDOR_LIBDIR/$LINUX_LIB/libcondorsyscall.a
	fi

	if [ ! -f "$CONDOR_ZCLIB" ]; then
		CONDOR_ZCLIB=$CONDOR_LIBDIR/$LINUX_LIB/libcondorzsyscall.a
	fi

	if [ ! -f "$CONDOR_RT0" ]; then
		CONDOR_RT0=$CONDOR_LIBDIR/$LINUX_LIB/condor_rt0.o
	fi

	if [ ! -f "$CONDOR_CPLUS" ]; then
		CONDOR_CPLUS=$CONDOR_LIBDIR/$LINUX_LIB/libcondorc++support.a
	fi
fi

#
# If the compressed ckpt library is available, use it.
#

if [ -r $CONDOR_ZCLIB ]; then
	CONDOR_CLIB="$CONDOR_ZCLIB"
fi

#
# However, we still always need the compression library for other purposes.
#

CONDOR_CLIB="$CONDOR_CLIB $STATIC_ZLIB"

if [ -r $CONDOR_SPECIAL_CLIB ]; then
	CONDOR_CLIB="$CONDOR_SPECIAL_CLIB"
fi
	
# Export these so our special "ld" script can find them
export CONDOR_LIBDIR
export CONDOR_CLIB
export CONDOR_RT0
export CONDOR_CPLUS
export CONDOR_LD_DIR

# Since uname and awk live in different places on various
# platforms, use a PATH.  NOTE: we want to add these things to the END
# of the PATH, to make sure people get the version of the compiler
# they thought they were using. 
PATH=$PATH:/bin:/usr/bin:/usr/bsd

# Figure out what architecture we're running on 

# Make sure if we get back something that begins with "IRIX" that we
# strip off anything after it (e.g. "IRIX64", etc).
os=`uname -s | sed 's/IRIX.*/IRIX/'`

osver=`uname -r`
if [ $os = "HP-UX" ]; then
	osmajver=`uname -r | awk -F. '{print $2}' -`
else
	osmajver=`uname -r | awk -F. '{print $1}' -`
fi

osfull="$os$osmajver"
abi=""

# Determine if the system ld has been replaced with our ld script
# or not.
CONDOR_FULLINSTALL=false

case $os in
	IRIX )
		if [ -x /usr/lib/ld.real -a -x /usr/lib/uld.real ]; then
			CONDOR_FULLINSTALL=true
		fi
		
		abi="-32"
		if [ $osver = "6.5" ]; then
			abi="-n32"
		fi


		SGI_ABI=$abi
		export SGI_ABI
		;;
	HP-UX )
		if [ $osmajver = "10" ]; then
			if [ -x /usr/ccs/bin/ld.real ]; then
				CONDOR_FULLINSTALL=true
			fi 
		fi
		if [ $osmajver = "09" ]; then
			if [ -x /bin/ld.real ]; then
				CONDOR_FULLINSTALL=true
			fi 
		fi
		;;
	SunOS )
		if [ $osmajver = 5 ]; then
			if [ -x /usr/ccs/bin/ld.real ]; then
				CONDOR_FULLINSTALL=true
			fi 
		fi
		if [ $osmajver = 4 ]; then
			if [ -x /bin/ld.real ]; then
				CONDOR_FULLINSTALL=true
			fi 
		fi
		;;
	Linux )
		if [ -x /usr/bin/ld.real ]; then
			CONDOR_FULLINSTALL=true
		fi 
		;;
	OSF1 )
		if [ -x /usr/lib/cmplrs/cc/ld.real ]; then
			CONDOR_FULLINSTALL=true
		fi 
		;;
	* )
		if [ -x /bin/ld.real ]; then
			CONDOR_FULLINSTALL=true
		fi 
		;;
esac

# Usage info should go here...
if [ $# = 0 ]; then
	echo "Usage: condor_compile <command> [options/files .... ]"
	if [ $CONDOR_FULLINSTALL = true ]; then
		echo "  where <commmand> is whatever you enter to compile/link your application."
		exit 1
	fi
	echo "  where <command> is one of the following:"
	echo "  gcc, g++, g77, cc, acc, c89, CC, f77, fort77, ld, "
	echo "  pgcc, pgf77, pgf90, or pghpf."
	echo "  (on some platforms, f90 is also allowed)"
	exit 1
fi

# if fully installed, then just run the command - eventually we'll 
# hit our special ld

if [ $CONDOR_FULLINSTALL = true ]; then
	exec $*
fi

# If we were passed a -c, we're not going to be used for linking, so
# we don't have to do anything special to make sure our special ld is
# used.  
ARGS=$*
NAME=$1
while [ A = A ]
do
	if [ $# = 0 ]; then
		break;
	fi
	if [ $1 = "-c" ]; then
		exec $ARGS;
	fi
	shift
done


# If not fully installed, and we didn't see a -c, add options to force
# the compiler to use our special ld

# First of all, we need to strip off any path from our (now) first
# argument, so we can compare it different names, even if the user
# specified a full path to the program.
myname=`echo $NAME | sed "s/.*\///"`

# Handle GNU compilers

if [ $myname = "gcc" ]; then
	exec $ARGS -B$CONDOR_LD_DIR/
fi 

if [ $myname = "g++" ]; then
	exec $ARGS -B$CONDOR_LD_DIR/
fi 

if [ $myname = "g77" ]; then
	exec $ARGS -B$CONDOR_LD_DIR/
fi 

# Handle Portland compilers.
# Notice that we explicitly do _not_ support Portland C++.
# Their run-time support libraries conflict with libcondorc++support.a

if [ $myname = "pgcc" ]; then
	exec $ARGS -Yl,$CONDOR_LD_DIR/
fi 

if [ $myname = "pgf77" ]; then
	exec $ARGS -Yl,$CONDOR_LD_DIR/
fi 

if [ $myname = "pgf90" ]; then
	exec $ARGS -Yl,$CONDOR_LD_DIR/
fi 

if [ $myname = "pghpf" ]; then
	exec $ARGS -Yl,$CONDOR_LD_DIR/
fi 

# Handle ld (linker).  Since the user might have specified a full path
# to ld, we want to shift (to get rid of the ld we were passed), and
# call our ld directly with the remaining arguments.
if [ $myname = "ld" ]; then
	shift;
	exec $CONDOR_LD_DIR/ld $ARGS
fi

# Handle all the vendor system compilers ---------------
# the idea here is to simply append whatever command line
# option(s) allows us to use $CONDOR_LIBDIR/ld instead
# of the default path for ld.

case $os in 

	IRIX )
		# IRIX has some special cases with the compiler taking different
		# flags depending what version yout have, this tries to sort that out

		if [ $myname = "cc" ]; then
			VCCRET=`cc -tul 2>&1 | head -1 | grep 'WARNING'`
			if [ "X$VCCRET" = "X" ]; then
				exec $ARGS -tul -h$CONDOR_LD_DIR -B
			else
				exec $ARGS -Y l,$CONDOR_LD_DIR -B dynamic
			fi
		fi

		if [ $myname = "CC" ]; then
			VCPPRET=`CC -tul 2>&1 | head -1 | grep 'WARNING'`
			if [ "X$VCPPRET" = "X" ]; then
				exec $ARGS -tul -h$CONDOR_LD_DIR -B
			else
				exec $ARGS -Y l,$CONDOR_LD_DIR -B dynamic
			fi
		fi

		if [ $myname = "c89" ]; then
			VC89RET=`c89 -tul 2>&1 | head -1 | grep 'WARNING'`
			if [ "X$VC89RET" = "X" ]; then
				exec $ARGS -tul -h$CONDOR_LD_DIR -B
			else
				exec $ARGS -Y l,$CONDOR_LD_DIR -B dynamic
			fi
		fi

		if [ $myname = "f77" ]; then
			VF77RET=`f77 -tul 2>&1 | head -1 | grep 'WARNING'`
			if [ "X$VF77RET" = "X" ]; then
				exec $ARGS -tul -h$CONDOR_LD_DIR -B
			else
				exec $ARGS -Y l,$CONDOR_LD_DIR -B dynamic
			fi
		fi 
	
		if [ $myname = "f90" ]; then	
			VF90RET=`f90 -tul 2>&1 | head -1 | grep 'WARNING'`
			if [ "X$VF90RET" = "X" ]; then
				exec $ARGS -tul -h$CONDOR_LD_DIR -B
			else
				exec $ARGS -Y l,$CONDOR_LD_DIR -B dynamic
			fi
		fi 

		;;
	
	OSF1 )
		if [ $myname = "cc" ]; then
			exec $ARGS -tl -h$CONDOR_LD_DIR -B
		fi

		if [ $myname = "CC" ]; then
			exec $ARGS -tl -h$CONDOR_LD_DIR -B
		fi

		if [ $myname = "cxx" ]; then
			exec $ARGS -tl -h$CONDOR_LD_DIR -B
		fi

		if [ $myname = "c89" ]; then
			exec $ARGS -tl -h$CONDOR_LD_DIR -B
		fi

		if [ $myname = "f77" ]; then
			exec $ARGS -tl -h$CONDOR_LD_DIR -B
		fi 
	
		if [ $myname = "f90" ]; then	
			exec $ARGS -tl -h$CONDOR_LD_DIR -B
		fi 

		if [ $myname = "KCC" ]; then	
			exec $ARGS --backend -tl --backend \
			-h$CONDOR_LD_DIR --backend -B
		fi 

		;;

	HP-UX )
		if [ $myname = "cc" ]; then
			exec $ARGS -tl,$CONDOR_LD_DIR/ld
		fi

		if [ $myname = "CC" ]; then
			exec $ARGS +A -tl,$CONDOR_LD_DIR/ld
		fi

		if [ $myname = "aCC" ]; then
			exec $ARGS +A -tl,$CONDOR_LD_DIR/ld
		fi

		if [ $myname = "c89" ]; then
			exec $ARGS -tl,$CONDOR_LD_DIR/ld
		fi

		if [ $myname = "f77" ]; then
			exec $ARGS -tl,$CONDOR_LD_DIR/ld
		fi 

		if [ $myname = "fort77" ]; then
			exec $ARGS -tl,$CONDOR_LD_DIR/ld
		fi 
		
		;;

	SunOS )
		use_qpath=`cc -help -flags | grep Qpath | wc -l`
		if [ $myname = "cc" -a $use_qpath = 0 ]; then
			exec $ARGS -Yl,$CONDOR_LD_DIR
		fi
		if [ $myname = "cc" -a $use_qpath != 0 ]; then
			exec $ARGS -Qpath $CONDOR_LD_DIR
		fi

		if [ $myname = "acc" ]; then
			exec $ARGS -Qpath $CONDOR_LD_DIR
		fi

		if [ $myname = "CC" ]; then
			exec $ARGS -Qpath $CONDOR_LD_DIR
		fi

		if [ $myname = "f77" ]; then
			exec $ARGS -Qpath $CONDOR_LD_DIR
		fi 
		
		if [ $myname = "f90" ]; then
			exec $ARGS -Qpath $CONDOR_LD_DIR
		fi 
		
		;;

	Linux )
		# Linux's system compilers are GNU 
		if [ $myname = "cc" ]; then
			exec $ARGS -B$CONDOR_LD_DIR/
		fi 

		if [ $myname = "CC" ]; then
			exec $ARGS -B$CONDOR_LD_DIR/
		fi 

		if [ $myname = "c++" ]; then
			exec $ARGS -B$CONDOR_LD_DIR/
		fi 

		if [ $myname = "f77" ]; then
			exec $ARGS -B$CONDOR_LD_DIR/
		fi 
		
		;;
esac

# If we made it here, we did not do anything, so print out usage
	echo "Usage: condor_compile <command> [options/files .... ]"
	if [ $CONDOR_FULLINSTALL = true ]; then
		echo "  where <commmand> is whatever you enter to compile/link your application."
		exit 1
	fi
	echo "  where <command> is one of the following:"
	echo "  gcc, g++, g77, cc, acc, c89, CC, f77, fort77, ld, "
	echo "  pgcc, pgf77, pgf90, or pghpf."
	echo "  (on some platforms, f90 is also allowed)"
	exit 1
