#! /usr/bin/env perl
#! /usr/bin/perl -w
use strict;
# use warnings;

# How to run the cluster tool...
{
    my $Tool = "/unsup/condor/bin/condor_cluster_tool";
    my $ToolArgs = "check";

    # Run the cluster tool...
    my $Cmd = "$Tool $ToolArgs";
    die "Can't run '$Cmd'" if ( ! open( IN, "$Cmd|" )  );
    while ( <IN> )
    {
	chomp;
	if ( /(.*): Condor is (\w+)/ )
	{
	    my $Host = $1;
	    my $Status = $2;
	    if ( /reserved/ )
	    {
		if ( $Status eq "on" )
		{
		    # print STDERR "$Host: Reserved and on!\n";
		}
		print "$Host\n";
	    }
	}
    }
    close( IN );
}

# How to run the NEW cluster tool...
{
    my $Tool = "/unsup/condor/bin/condor_new_cluster_tool";
    my $ToolArgs = "check";

    # Run the cluster tool...
    my $Cmd = "$Tool $ToolArgs";
    die "Can't run '$Cmd'" if ( ! open( IN, "$Cmd|" )  );
    while ( <IN> )
    {
	chomp;
	if ( /(.*)\s+is\s+(\S+)/ )
	{
	    my $Host = $1;
	    my $Status = $2;
	    print "$Host\n" if ( $Status =~ /reserved/ );
	}
    }
    close( IN );
}
