#! /usr/bin/env perl
BEGIN { $^W = 1 }
use strict;
use FindBin;

exit main();

sub main {
	print "Starting Condor-C Launcher\n";
	submit('condorc-launcher');
	print "Starting Condor-C Advertiser\n";
	submit('condorc-advertiser');
}

sub submit {
	my($executable) = @_;
	my $bin_path = $FindBin::Bin;
	my $sbin_path = $bin_path;
	$sbin_path =~ s|/bin/*|/sbin|;
	local *OUT;
	open(OUT, "|condor_submit")
		or die "FATAL ERROR: unable to launch condor_submit";
	print OUT <<END;
executable=$bin_path/$executable
universe=scheduler
output=/tmp/$executable.$>.$$.out
error=/tmp/$executable.$>.$$.err
environment=PATH=\$ENV(PATH):$bin_path:$sbin_path
notification=never
queue
END
	close OUT;
}
