#!/bin/sh
# condor_cleanckpts  Todd Tannenbaum, 2/97
# 	updated for Condor V6 1/98
#
# THIS SCRIPT IS BEST VIEWED WITH TABSTOPS=4 
#
# This script cleans out old checkpoints from the checkpoint server 
# directory.  Run as root or condor. 

ckptdir=`condor_config_val CKPT_SERVER_DIR`

cd $ckptdir

hosts=`find *.*.*.* -type d -prune -print`

for host in $hosts
do

cd $ckptdir/$host

hostname=`nslookup $host | grep Name | awk '{print $2}'`
echo Gathering jobs from host $hostname

condor_q -name $hostname > /tmp/cgq.$$ 2>&1
if [ $? != 0 ]; then
	down=1;
else
	down=`grep "Error" /tmp/cgq.$$ | wc -l`
fi
if [ $down != 0 ]; then
	echo Cannot fetch jobs for host $host
	rm -f /tmp/cgq.$$
	continue
fi
awk -F. '{printf "%s A_JOB\n", $1}' /tmp/cgq.$$ | awk '{printf "%s %s\n",$1,$2}' -  > /tmp/joblist.$$ 

echo Gathering checkpoint files in subdir $host
find . -name cluster\* -print | sed -e s/cluster/cluste\#/ -e s/\.proc/\#/ | awk -F\# '{printf "%s CKPT_FILE %s\n",$2,$0}' - | sed -e s/cluste\#/cluster/ -e s/\#/\.proc/ > /tmp/ckptlist.$$

echo Removing any old checkpoint files from subdir $host
`cat /tmp/joblist.$$ /tmp/ckptlist.$$ | sort | uniq | awk '
($2 == "A_JOB") {  jobid = $1 ; }
($2 == "CKPT_FILE") {
	 if ($1 != jobid) {
		if ( first_flag == 0 ) {
			first_flag = 1; 
			printf "rm -f"; 
		} 
		printf" %s",$3 ; 
	} 
}' - `

rm -f /tmp/joblist.$$ /tmp/ckptlist.$$ /tmp/cgq.$$

done
