#!/usr/bin/env python3

import htcondor
import argparse
import json
import os
import sys
import signal
import datetime as dt
from time import sleep
from collections import defaultdict

# Constants (TODO make these config attributes)
COMMAND_PREFIX = "DIAG_CCS" # Prefix for command statistics attributes
REAP_PREFIX = "DIAG_CRS" # Prefix for command reaper statistics attributes
FSYNC_PREFIX = "DIAG_CFS"
TIMER_PREFIX = "DCTimer_"
TIMER_SUFFIX = "Runtime"
DANGER_THRESHOLD = 20 # Threshold for highlighting a user in red (% runtime)
WARNING_THRESHOLD = 10 # Threshold for highlighting a user in yellow (% runtime)

# Define terminal colors for printing
class colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    DANGER = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

# Cleanly exit on SIGINT (Ctrl+C)
signal.signal(signal.SIGINT, lambda x, y: exit(0))

# Initialize global variables
old = None

# Hardcoded kwargs for querying the schedd
kwargs = {
    'daemon_type':htcondor.DaemonTypes.Schedd,
    'statistics':'All:2',
} 


def get_name():
    """Returns the name of the schedd, or exits if it can't be found."""
    collector = htcondor.Collector()
    machine = htcondor.param['FULL_HOSTNAME']
    # Query for the schedd ad
    ads = collector.query(htcondor.AdTypes.names["Schedd"],
                                    constraint=f"Machine == {machine}",
                                    projection=['Name'])
    # if that doesn't work, remove the constraint and try again
    if len(ads) == 0:
        ads = collector.query(htcondor.AdTypes.names["Schedd"],
                                    projection=['Name'])
    # Still doesn't work -> we have an error
    if len(ads) == 0:
        print(f"Error: Couldn't find hostname for schedd")
        sys.exit(1)
    return ads[0]['Name']


def map_dict(d, lambda_):
    """Maps a lambda function over a (possibly nested) dictionary
    d: The dictionary to map over
    lambda_: The function to apply to each value
    returns: The modified dictionary
    """
    for key, value in d.items():
        if isinstance(value, dict):
            d[key] = map_dict(value, lambda_)
        else:
            d[key] = lambda_(value)
    return d


def bimap_dict(d1, d2, lambda_, fail_=None):
    """Maps a lambda function over two (possibly nested) dictionaries, combining them.
    Searches through the keys of d1, applying fail if the key is not in d2.
    d1: The first dictionary to map over
    d2: The second dictionary to map over
    lambda_: The function to apply to each pair of values
    returns: A combined dictionary
    """
    res = {}
    for key, value in d1.items():
        if key not in d2:
            if fail_ is not None:
                res[key] = fail_(value)
            else:
                continue
        if isinstance(value, dict):
            res[key] = bimap_dict(value, d2[key], lambda_, fail_)
        else:
            res[key] = lambda_(value, d2[key])
    return res


def add_totals_dict(d):
    """Adds a total key to dict fields recursively.
    dict: The dictionary to add totals to
    returns: The modified dictionary
    """
    res = {}
    # Base case, flat dictionary. Add total key and return
    if not any(isinstance(value, dict) for value in d.values()): 
        res = {key: value for key, value in d.items()}
        res['total'] = sum(d.values())
        return res

    # Recursive case, add totals to sub-dictionaries
    else:
        for key, value in d.items():
            if isinstance(value, dict):
                res[key] = add_totals_dict(value)
        res['total'] = sum([value['total'] for value in res.values()])
        
    return res


def invert_dict(d):
    """Inverts stats from (user->command) to (command->user)
    d: The dictionary to invert
    returns: The inverted dictionary
    """
    new = defaultdict(lambda: defaultdict(lambda: 0))
    for category, table in d.items():
        if category == "Commands":
            for user, commands in table.items():
                for command, value in commands.items():
                    new[command][user] = value
            d["Commands"] = new
    return d


def get_fields(dict, ad, title, prefix="", suffix="", splituser=False):
    """Populates a dictionary with statistics from a given prefix
    dict: The dictionary to populate
    ad: The ad to pull statistics from
    prefix: The prefix to search for
    title: The top-level key to add to the dictionary
    splituser: Whether the ad needs to be split into user and value
    """
    names = [key[len(prefix):] for key in ad.keys() if key.startswith(prefix) and key.endswith(suffix)]
    if splituser:
        for name in names:
            user, value = name.split("_", 1)
            dict[title][user][value] = ad[prefix + name]
    else:
        for name in names:
            dict[title][name] = ad[prefix + name]

    return dict


def get_stats():
    """Queries the collector for command statistics on the schedd.
    returns: A tuple of the statistics and the time the statistics were taken
    """
    try:
        collector = htcondor.Collector()
        ad = collector.directQuery(**kwargs)
    except Exception as e:
        print(f"Error: Couldn't query collector: {e}")
        sys.exit(1)

    # Get useful metadata
    recent_dcdc = ad['RecentDaemonCoreDutyCycle']
    pump_cycle = ad['RecentDCPumpCycleSum']
    cpu_time = recent_dcdc * args.window
    server_time = ad['MyCurrentTime']
    format_time = dt.datetime.fromtimestamp(server_time)

    # Lets us make entries arbitrarily deep
    recursive_defaultdict = lambda: defaultdict(recursive_defaultdict)
    stats = recursive_defaultdict()
    # Get the statistics for each category
    if args.c or args.all:
        get_fields(stats, ad, "Commands", prefix=COMMAND_PREFIX, splituser=True)
    if args.r or args.all:
        get_fields(stats, ad, "Reapers", prefix=REAP_PREFIX)
    if args.t or args.all:
        get_fields(stats, ad, "Timers", prefix=TIMER_PREFIX, suffix=TIMER_SUFFIX)
    if args.f or args.all:
        stats["Fsync"] = {"total": ad["DCfsyncRuntime"]}

    # Invert table before we add extra top-level keys
    if args.invert:
        stats = invert_dict(stats)

    stats |= {
        'Time': pump_cycle,
        'CPU': cpu_time,
        'RecentDCDC': recent_dcdc,
    } # Shove ancillary data in with the command statistics, kinda messy but we can filter it later
    return stats, format_time


def get_diffs(old, new):
    """Calculates the difference between two sets of statistics.
    old: The previous set of statistics
    new: The current set of statistics
    returns: A tuple of the new statistics and the difference between the two sets
    """
    global CPU_OVERFLOW
    CPU_OVERFLOW = False
    if old is None:
        print("Waiting on second sample...")
        return new, {}
    else:
        # Filter out metadata
        old_stats = {key: value for key, value in old.items() if isinstance(value, dict)} 
        new_stats = {key: value for key, value in new.items() if isinstance(value, dict)} 
    
        diff = bimap_dict(old_stats, new_stats, lambda x, y: y - x, fail_=lambda x: x)
        diff = add_totals_dict(diff)
        # Renormalize the totals if they go over 100% of CPU time
        if diff['total'] > new['CPU']:
            new['CPU'] = diff['total']
            CPU_OVERFLOW = True
        # Use the total CPU time to calculate the "Other" category then discard
        diff["Other"] = {"total": new['CPU'] - diff["total"]}
        del diff["total"]
        if args.rel:
            diff = map_dict(diff, lambda x: x / new['CPU'] * 100)
        else:
            diff = map_dict(diff, lambda x: x / args.window * 100)
        return new, diff


def print_stat(key, value, spacing, bullet, color=False):
    """Prints a single statistic with color coding
    key: The key to print
    value: The value to print
    spacing: The number of tabs to indent
    bullet: The bullet to print before the key
    color: Whether to color code the output
    """
    if value == 0:
        return
    if not color:
        print(f"\t{' ' * spacing} {bullet} {key}: {value:.2f}%")
        return
    
    print_color = ""
    whitespace = "  " * spacing
    if value >= DANGER_THRESHOLD:
        print_color = colors.DANGER
    elif value >= WARNING_THRESHOLD:
        print_color = colors.WARNING
    print(print_color, f"{whitespace} {bullet} {key}: {value:.2f}%", colors.ENDC)


def print_dict(d, depth, bullets, color_flags, sort_ascending=False):
    """Recursively prints a dictionary of statistics
    d: The dictionary to print
    depth: The current depth of the recursion
    bullets: A list of bullets to print at each depth
    color_flags: A list of flags to determine whether to color code the output at that depth
    (Anything beyond the end of the list will default to no color)
    """
    subdicts = [i for i in d.items() if isinstance(i[1], dict)]
    if not subdicts:
        for key, value in sorted(d.items(), key=lambda x: x[1], reverse=not sort_ascending):
            if key == "total":
                continue
            print_stat(key, value, depth, bullets[min(depth, len(bullets) - 1)], color_flags[min(depth, len(color_flags) - 1)])
    else:
        for key, value in sorted(subdicts, key=lambda x: x[1]['total'], reverse=not sort_ascending):
            if isinstance(value, dict):
                print_stat(key, value["total"], depth, bullets[min(depth, len(bullets) - 1)], color_flags[min(depth, len(color_flags) - 1)])
                print_dict(value, depth+1, bullets, color_flags)


def print_stats(diff, stats, time):
    """Prints the user statistics
    diff: The difference between the two sets of statistics
    stats: The current set of statistics (used for CPU time, RecentDCDC, etc.)
    time: The time the current set of statistics were taken
    """
    BULLETS = ["*", "-", ">"]
    if not diff:
        return
    else:
        # Print header
        os.system("clear")
        print(f"{time}" + "-" * 61) #Timestamp is 19 characters until 10000AD
        print(f"Sample Window: {args.window:7.0f} s")
        print(f"CPU Time: {stats['CPU']:12.3f} s")
        print(f"CPU Usage: {(stats['RecentDCDC'] * 100):12.2f}%")
        print("-" * 80)
        if CPU_OVERFLOW:
            print(colors.DANGER, "WARNING: Summed statistics exceeded CPU time! These values are renormalized!", colors.ENDC)
            print(colors.DANGER, "This typically happends when traffic spikes faster then CPU Usage can update.", colors.ENDC)
        order = sorted([(k,v) for (k,v) in diff.items() if k != "Other"], key=lambda x: x[1]['total'], reverse=not args.ascending)
        for key, table in order:
            if key == "total" or table["total"] == 0:
                continue
            print(colors.BOLD, f"{key}: {(table['total'] * stats['CPU'] / 100):.3f}s ({table['total']:.2f}%)", colors.ENDC)
            print_dict(table, depth=0, bullets=BULLETS, color_flags=[True, True, False], sort_ascending=args.ascending)
        # Always put "Other" on bottom
        print(colors.BOLD, f"Other: {(diff['Other']['total'] * stats['CPU'] / 100):.3f}s ({diff['Other']['total']:.2f}%)", colors.ENDC)
        print("-" * 80)


def save_stats(stats, old, time, filename):
    """Saves the command statistics to a json file.
    stats: A dict of statistics to save
    time: The time the statistics were taken
    filename: The name of the file to save to
    """
    if not stats or not old:
        return
    stats = stats | {"Time": str(time)}
    stats = stats | {"RecentDCDC": old["RecentDCDC"]}
    stats = stats | {"CPU": old["CPU"]}
    stats = stats | {"Window": args.window}
    if os.path.exists(filename):
        with open(filename, "r+") as f:
            base = json.load(f)
            base.append(stats)
            f.seek(0)
            json.dump(base, f, indent=4)
    else:
        with open(filename, "w") as f:
            json.dump([stats], f)
    

def parse_args():
    """Parses command line arguments"""
    parser = argparse.ArgumentParser()
    parser.add_argument("-w", "--window", default=240, type=int, help="Seconds between updates (default 240)")
    parser.add_argument("-s", "--save", default=None, help="Save statistics to a file (default None)")
    parser.add_argument("-i", "--invert", action="store_true", help="Invert the user/command ordering")
    parser.add_argument("-a", "--ascending", action="store_true", help="Sort values in ascending order")
    parser.add_argument("-c", action="store_true", help="Show command statistics")
    parser.add_argument("-r", action="store_true", help="Show reaper statistics")
    parser.add_argument("-t", action="store_true", help="Show timer statistics")
    parser.add_argument("-f", action="store_true", help="Show fsync statistics")
    parser.add_argument("--all", action="store_true", help="Show all statistics")
    parser.add_argument("--rel", action="store_true", help="Show percentages relative to CPU time")
    return parser.parse_args()


def wait(seconds):
    """Waits for a number of seconds and prints the remaining time to console."""
    for i in range(seconds):
        print(f"Waiting {seconds - i} seconds    ", end='\r') # Spaced so carriage return works on 10->9, etc.
        sleep(1)
    print(" " * 30, end="\r")


if __name__ == "__main__":
    kwargs['name'] = get_name()
    print(f"Monitoring {kwargs['name']}...")
    args = parse_args()

    # Main driver loop
    while True:
        stats, time = get_stats()
        old, diff = get_diffs(old, stats)
        print_stats(diff, old, time)
        if args.save:
            save_stats(diff, old, time, args.save)
        if args.window:
            wait(args.window)
        else:
            break