#!/usr/bin/env perl

##/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
##
## Condor Software Copyright Notice
## Copyright (C) 1990-2006, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
##
## This source code is covered by the Condor Public License, which can
## be found in the accompanying LICENSE.TXT file, or online at
## www.condorproject.org.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
## IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
## WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
## FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
## HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
## MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
## ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
## PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
## RIGHT.
##
##***************************Copyright-DO-NOT-REMOVE-THIS-LINE**/


# This perl script is used by our build environment to make
# a soft-link directory tree.  The first arg is the name of the
# directory we wish to create, and the 2nd arg is the root of the
# source tree we want to make the links to.  
#
# Written on 7/2/99 by Derek Wright <wright@cs.wisc.edu>

# Process args
$dir = shift;
$root = shift;

# First, remove anything we've got here already
`rm -rf $dir`;

# Let the world know what we're doing, and immediately flush output in
# case of errors.
$| = 1;
print "Creating soft-link directory tree for $dir... ";

# Now, call our function, which we might call recursively, if it's
# actually a directory tree we're creating.
make_dir( $dir, $root );

print "done.\n";
exit(0);

sub make_dir {
    my( $dir, $root ) = @_;
    my( $file, $DIR );

    # First, create the dir:
    mkdir( $dir, 0777 ) || die "\nCan't make directory $dir: $!\n";

    # Now, cd into it:
    chdir $dir;

    opendir( DIR, "$root/$dir" );
    foreach $file ( readdir(DIR) ) {
	# Skip over ".", "..", and "CVS", but allow other dot files
	next if( $file =~ /^\.$/ );
	next if( $file =~ /^\.\.$/ );
	next if( $file =~ /^CVS/ );
	if( -d "$root/$dir/$file" ) {
	    # It's a directory we're about to create, so just call
	    # ourself recursively to do the job.
	    make_dir( "$file", "$root/$dir");
	} else {
	    # Regular file, make the soft link.
	    symlink( "$root/$dir/$file", $file ) || 
		die "\nCan't link $file to $root/$dir/$file: $!\n";
	}
    }
    # Clean-up
    closedir( DIR );
    chdir "..";
}

