#!/usr/bin/env perl

##/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
##
## Condor Software Copyright Notice
## Copyright (C) 1990-2006, Condor Team, Computer Sciences Department,
## University of Wisconsin-Madison, WI.
##
## This source code is covered by the Condor Public License, which can
## be found in the accompanying LICENSE.TXT file, or online at
## www.condorproject.org.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
## IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
## WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
## FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
## HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
## MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
## ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
## PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
## RIGHT.
##
##***************************Copyright-DO-NOT-REMOVE-THIS-LINE**/


# This script performs all steps necessary to make the
# static_dir/release.tar file on platforms where special magic must be
# done.  It should be run in the top-level src directory.
#
# For now, this is specific to Linux/glibc21, where the statically
# linked version needs to include seperate lib subdirectories for each
# version of libc that we might be installed on: libc5, glibc20, and
# glibc21.  We get the libc5 and glibc20 versions from tarballs in
# AFS land that are put there by the build on other platforms.
#
# Derek Wright <wright@cs.wisc.edu>, 11/3/99

# Autoflush the output
$| = 1;

umask(022);
chomp($home_dir = `pwd`);

# First, create all the appropriate subdirs
mkdir( "static_dir/lib/libc5", 0777 );
mkdir( "static_dir/lib/glibc20", 0777 );
mkdir( "static_dir/lib/glibc21", 0777 );

# Now, move all the platform specific stuff out of static_dir/lib into
# the glibc21 subdir.
`mv static_dir/lib/*.[oa] static_dir/lib/glibc21`;

# Next, unpack the libtar files in AFS land into the appropriate
# subdirs:
foreach $lib ( "libc5", "glibc20") {
    print "Working on $lib...\n";
    $afs_file = "/p/condor/workspaces/release/libtars/lib-$lib.tar";
    chdir( "static_dir/lib/$lib" );
    print `tar -xvf $afs_file`;
    chdir( $home_dir );
}
	
# Now, we're nearly done.  All we have to do is make the release.tar
# file itself...
chdir( "static_dir" );
print "Making release.tar...\n";
print `tar -cvf release.tar etc include lib bin sbin`;
print "Done.\n";
