#!/s/std/bin/perl

$filename = $ENV{'HOME'} . "/.globus/my-contacts";

##$glidein = `which condor_glidein`;
$glidein = "/u/m/i/mikeu/condor_glidein";

##$submit = `which condor_submit`;
$submit = "/u/m/i/mikeu/submit/condor_submit";

$username = `whoami`;
chomp( $filename, $glidein, $submit, $username );

if ( ! -r $filename ) {
	print "can't find $filename\n";
	exit;
}
if ( ! -x $glidein ) {
	print "can't execute $glidein\n";
	exit;
}
if ( ! -x $submit ) {
	print "can't execute $submit\n";
	exit;
}

use Getopt::Long;
$result = GetOptions(
	"runfor=i" => \$runfor
);

if ( !$result ) {
	print( STDERR "usage: $0 [options]\n"
		. "   Valid options are:\n"
		. '--runfor <mins>  Gracefully shutdown Condor daemons after <mins>\n' );
	exit( 0 );
}
$OPTARGS = "";
if ( $runfor ) {
	$OPTARGS .= " --runfor $runfor";
}
if ( $kill ) {
	$OPTARGS .= " --kill";
}

open( CONTACTS, $filename );

chomp( @CONTACTS = <CONTACTS> );

$num = 0;
foreach $CONTACT ( @CONTACTS ) {
	if ( $CONTACT !~ /#/ ) {
		print "GLIDING TO: $CONTACT\n";
		glidein();
		$num++;
	}
}

sub glidein() {
	open( FILE, "|$submit" );
	print FILE <<"EOF";
Getenv = true
Universe = globus
GlobusExecutable = \$(HOME)/Condor_glidein/$username.$num/sbin/condor_master
GlobusArguments = -c \$(HOME)/Condor_glidein/$username.$num/condor_config.host -f -n $username.$num 

GlobusScheduler = $CONTACT
Queue
EOF

	close( FILE );
}
