/***************************************************************
 *
 * Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
 * University of Wisconsin-Madison, WI.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License.  You may
 * obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ***************************************************************/


#ifndef _CONDOR_CLAIMID_PARSER_H
#define _CONDOR_CLAIMID_PARSER_H

// ClaimIdParser knows how to extract parts of a claim id string.
// It expects the following format (generated by the starter's claim.C)
// "<ip:port>#...#secret_cookie"

// the Lite version can parse a claim id it does not own.
class ClaimIdParserLite {
public:
	ClaimIdParserLite() = default;
	ClaimIdParserLite(const char * id) {
		if (id) {
			claim_id = {id};
			hash_off = claim_id.rfind('#');
		}
	}
	ClaimIdParserLite(const std::string & id) : claim_id(id), hash_off(claim_id.rfind('#')) {}

	~ClaimIdParserLite() {}

	void clear() { claim_id = {}; hash_off = 0; }
	bool empty() const { return claim_id.empty(); }

	void setClaimId(char const *id) {
		if (id) {
			claim_id = {id};
			hash_off = claim_id.rfind("#");
		} else { clear(); }
	}

	// we know that claim_id.data() is null terminated
	// because we construct on a const char * or std::string
	const char * claimId() const { return claim_id.data(); }

	// Return the public part of the claim id.  (without "#..." appended)
	// which is everything up to the last #, zero length if no #
	std::string_view publicPart() const {
		if (claim_id.empty()) return claim_id;
		if (hash_off == std::string_view::npos) {
			// if no hash, return a zero length string..
			return {claim_id.data(), claim_id.data()};
		}
		return {claim_id.data(), claim_id.data()+hash_off};
	}
	// return the private part of the claim id, (after the last #)
	// or the whole string if there is no # (should never happen)
	std::string_view privatePart() const {
		std::string_view ret = claim_id;
		if (hash_off != std::string_view::npos) {
			ret.remove_prefix(hash_off+1);
		}
		return ret;
	}
	// build a string that has the public part of the claim id with "#..." appended..
	std::string publicClaimId() const {
		std::string pub(publicPart());
		if ( ! pub.empty()) { pub += "#..."; }
		return pub;
	}
	// alternate form a bit more convenient for use in dprintf
	const char * publicClaimId(std::string & pub) const {
		pub = publicClaimId();
		return pub.c_str();
	}
	// the session is the public part, everything up to the last #
	std::string_view secSessionId() const {
		return publicPart();
	}
	const char * secSessionId(std::string & sessId) const {
		sessId = secSessionId();
		return sessId.c_str();
	}

	// the session info is just after the #, everything in [] (if any)
	std::string_view secSessionInfo() const {
		std::string_view info(privatePart());
		if (info.empty()) { return info; }
		size_t len = 0;
		if (info.front() == '[') {
			len = info.rfind(']');
			if (len != std::string_view::npos) len += 1; // include the ]
		}
		return {info.data(), info.data()+len};
	}
	const char * secSessionInfo(std::string & sessInfo) const {
		sessInfo = secSessionInfo();
		return sessInfo.c_str();
	}
	// the session key is after the #[..], or after # if no []
	std::string_view secSessionKey() const {
		std::string_view key(privatePart());
		if (key.empty() || key.front() != '[') { return key; }
		// got session info at the front [INFO]key
		auto off = key.rfind(']');
		if (off != std::string_view::npos) { key.remove_prefix(off+1); }
		return key;
	}
	const char * secSessionKey(std::string & sessKey) const {
		sessKey = secSessionKey();
		return sessKey.c_str();
	}
	// return the public part, and split the private part into key and info
	std::string_view secSessionSplit(std::string_view & key, std::string_view & info) {
		info = secSessionInfo();
		key = secSessionKey();
		return publicPart();
	}

	std::string_view startdSinfulAddr() const {
		std::string_view sinful(publicPart());
		if (sinful.empty() || sinful.front() != '<') return sinful;
		// TODO: can we use sinful.back() == '>' as an optimization?
		auto off = sinful.find('>');
		if (off != std::string::npos) {
			sinful.remove_suffix(sinful.size() - (off+1));
		}
		return sinful;
	}
	const char * startdSinfulAddr(std::string & sinful) const {
		sinful = startdSinfulAddr();
		return sinful.c_str();
	}

	CondorVersionInfo secSessionInfoVersion() {
		int maj=0,min=0,sub=0;
		// call secSessionInfo to force the m_session_info member to populate
		auto info = secSessionInfo();
		if ( ! info.empty()) {
			// then we can look inside it to find the ShortVersion
			auto ver = info.find("ShortVersion=\"");
			if (ver != std::string::npos) {
				const char * short_version = info.data() + ver + 14;
				char *pos = NULL;
				maj = strtol(short_version, &pos, 10);
				min = (pos[0] == '.') ? strtol(pos+1, &pos, 10) : 0;
				sub = (pos[0] == '.') ? strtol(pos+1, &pos, 10) : 0;
			}
		}
		return {maj,min,sub};
	}

	// build a capability string (i.e. a claimid, from the various parts)
	static std::string make(std::string_view sessId, std::string_view sessInfo, std::string_view sessKey) {
		std::string cap;
		size_t cb = sessId.size() + 1 + sessInfo.size() + sessKey.size() + 1;
		cap.reserve(cb);
		cap = sessId;
		cap.push_back('#');
		if ( ! sessInfo.empty()) {
			ASSERT(sessInfo.front() == '[');
			ASSERT(sessInfo.back() == ']');
			ASSERT(sessInfo.find('#') == std::string_view::npos);
			cap += sessInfo;
		}
		ASSERT(sessKey.find('#') == std::string_view::npos);
		cap += sessKey;
		return cap;
	}

	// build a capability string (i.e. a claimid, from the various parts) as a strdup pointer
	static char * make_strdup(std::string_view sessId, std::string_view sessInfo, std::string_view sessKey) {
		size_t cb = sessId.size() + 1 + sessInfo.size() + sessKey.size() + 1;
		char * cap = (char*)malloc(cb);
		char * p = cap;
		memcpy(p, sessId.data(), sessId.size());
		p += sessId.size();
		*p++ = '#';
		if (sessInfo.size()) {
			ASSERT(sessInfo.front() == '[');
			ASSERT(sessInfo.back() == ']');
			ASSERT(sessInfo.find('#') == std::string_view::npos);
			memcpy(p, sessInfo.data(), sessInfo.size());
			p += sessInfo.size();
		}
		ASSERT(sessKey.find('#') == std::string_view::npos);
		memcpy(p, sessKey.data(), sessKey.size());
		p +=  sessKey.size();
		*p = 0;
		return cap;
	}

protected:
	std::string_view claim_id{};
	size_t hash_off{0}; // offset of # within claim id
};

// define this to have the old ClaimIdParser use the Lite parser to do the actually parsing
// which turns the ClaimIdParser into a cache of substrings of the claim id.
#define USE_CLAIM_ID_PARSER_LITE 1

class ClaimIdParser {
 public:
	ClaimIdParser()
	{ }
	ClaimIdParser(char const *claim_id):
		m_claim_id(claim_id)
	{ }
	ClaimIdParser(char const *session_id,char const *session_info,char const *session_key)
	{
	#ifdef USE_CLAIM_ID_PARSER_LITE
		// string_view constructor does not handle nullptr
		const char * info = session_info ? session_info : "";
		m_claim_id = ClaimIdParserLite::make(session_id, info, session_key);
	#else
		formatstr(m_claim_id,"%s#%s%s",
						   session_id ? session_id : "",
						   session_info ? session_info : "",
						   session_key ? session_key : "");
		ASSERT( !session_info || !strchr(session_info,'#') );
		ASSERT( !session_key || !strchr(session_key,'#') );
	#endif
	}
	void setClaimId(char const *claim_id) {
		m_claim_id = claim_id;
		m_sinful_part.clear();
		m_public_part.clear();
		m_session_id.clear();
		m_session_info.clear();
	}
	char const *claimId() const {
		return m_claim_id.c_str();
	}
	char const *startdSinfulAddr() {
		if( m_sinful_part.empty() ) {
		#ifdef USE_CLAIM_ID_PARSER_LITE
			m_sinful_part = ClaimIdParserLite(m_claim_id).startdSinfulAddr();
		#else
			char const *str = m_claim_id.c_str();
			char const *end;
			if ( str[0] == '<' ) {
				end = strchr(str, '>');
				if ( end != NULL ) {
					end++;
				}
			} else {
				end = strchr(str, '#');
			}
			if (end) m_sinful_part.assign(str,end);
		#endif
		}
		return m_sinful_part.c_str();
	}
	char const *publicClaimId() {
		if( m_public_part.empty() ) {
		#ifdef USE_CLAIM_ID_PARSER_LITE
			m_public_part = ClaimIdParserLite(m_claim_id).publicClaimId();
		#else
			char const *str = m_claim_id.c_str();
			char const *end = strrchr(str,'#');
			if (end) {
				m_public_part.assign(str,end);
				m_public_part += "#...";
			}
		#endif
		}
		return m_public_part.c_str();
	}

	char const *secSessionId(bool ignore_session_info=false) {
			// This must return the same thing for both the schedd and
			// the startd, so be careful making any version-incompatible
			// changes.
		if( !ignore_session_info && !secSessionInfo() ) {
				// There is no session info, so no security session
				// was created.
			return "";
		}
		if( m_session_id.empty() ) {
		#ifdef USE_CLAIM_ID_PARSER_LITE
			m_session_id = ClaimIdParserLite(m_claim_id).secSessionId();
		#else
			char const *str = m_claim_id.c_str();
			char const *end = strrchr(str,'#');
			if (end) m_session_id.assign(str,end);
		#endif
		}
		return m_session_id.c_str();
	}
	char const *secSessionKey() {
			// expected format: blah#blah#...#[session_info]SESSION_KEY
	#ifdef USE_CLAIM_ID_PARSER_LITE
		auto key = ClaimIdParserLite(m_claim_id).secSessionKey();
		if (key.empty()) return "";
		return key.data(); // we know key is at the end and is null terminated.
	#else
		char const *str = m_claim_id.c_str();
		char const *ptr = strrchr(str,'#');
		if(ptr) {
			ptr+=1;
		}
		char const *ptr2 = strrchr(str,']');
		if(ptr2) {
			ptr2+=1;
		}
		if( ptr2 > ptr ) {
				// skip past the session info
			ptr = ptr2;
		}
		return ptr ? ptr : "";
	#endif
	}
	char const *secSessionInfo() {
			// expected format: blah#blah#...#[session_info]SESSION_KEY
		if( m_session_info.empty() ) {
		#ifdef USE_CLAIM_ID_PARSER_LITE
			m_session_info = ClaimIdParserLite(m_claim_id).secSessionInfo();
		#else
			char const *str = m_claim_id.c_str();
			char const *ptr = strrchr(str,'#');
			char const *endptr;
			if( !ptr ) {
				return "";
			}
			ptr+=1;
			if( *ptr != '[' ) {
				return "";
			}
			endptr = strrchr(str,']');
			if(!endptr || endptr < ptr) {
				return "";
			}
			m_session_info.assign(ptr,endptr+1);
		#endif
		}

		return m_session_info.c_str();
	}
	void setSecSessionInfo(char const *session_info) {
	#ifdef USE_CLAIM_ID_PARSER_LITE
		ClaimIdParserLite cid(m_claim_id);
		std::string_view pub = cid.publicPart();
		std::string_view key = cid.secSessionKey();
		const char * info = session_info ? session_info : "";
		std::string cap = cid.make(pub, info, key);
			// reset everything using the new claim id
		setClaimId(cap.c_str());
	#else
		if(session_info) {
			ASSERT(session_info[0] == '[');
			ASSERT(session_info[strlen(session_info)-1] == ']');
			ASSERT(strchr(session_info,'#') == NULL);
		}

		std::string new_claim_id(secSessionId(true));
		char const *session_key = secSessionKey();
		formatstr_cat(new_claim_id,"#%s%s",
			session_info ? session_info : "",
			session_key ? session_key : "");

			// reset everything using the new claim id
		*this = ClaimIdParser(new_claim_id.c_str());
	#endif
	}

	// extract the version info from the session info
	CondorVersionInfo secSessionInfoVersion()
	{
	#ifdef USE_CLAIM_ID_PARSER_LITE
		return ClaimIdParserLite(m_claim_id).secSessionInfoVersion();
	#else
		int maj=0,min=0,sub=0;
		// call secSessionInfo to force the m_session_info member to populate
		if (secSessionInfo() && !m_session_info.empty()) {
			// then we can look inside it to find the ShortVersion
			auto ver = m_session_info.find("ShortVersion=\"");
			if (ver != std::string::npos) {
				const char * short_version = m_session_info.c_str() + ver + 14;
				char *pos = NULL;
				maj = strtol(short_version, &pos, 10);
				min = (pos[0] == '.') ? strtol(pos+1, &pos, 10) : 0;
				sub = (pos[0] == '.') ? strtol(pos+1, &pos, 10) : 0;
			}
		}
		return {maj,min,sub};
	#endif
	}

 private:
	std::string m_claim_id;
	std::string m_public_part;
	std::string m_sinful_part;

		// The following fields are for SEC_ENABLE_MATCH_PASSWORD_AUTHENTICATION
	std::string m_session_id;
	std::string m_session_info;
};

#endif
