#ifndef _CONDOR_STARTD_STATES_H
#define CONDOR_STARTD_STATES_H

#define RES_FREE	0
#define RES_ALLOCATED	1
#define RES_EVENTINPROG	2
#define RES_SUSPENDED	3
#define RES_EXTERNBUSY	4
#define RES_BUSY	5

#define STARTD_AVAILAVBLE	0
#define STARTD_BUSY		1
#define STARTD_BLOCKED		2	/* XXX? */

#endif /* CONDOR_STARTD_STATES_H */
