
#ifndef CHIRP_PROTOCOL_H
#define CHIRP_PROTOCOL_H

#define CHIRP_LINE_MAX 1024

#define CHIRP_ERROR_NOT_AUTHENTICATED -1
#define CHIRP_ERROR_NOT_AUTHORIZED -2
#define CHIRP_ERROR_DOESNT_EXIST -3
#define CHIRP_ERROR_ALREADY_EXISTS -4
#define CHIRP_ERROR_TOO_BIG -5
#define CHIRP_ERROR_NO_SPACE -6
#define CHIRP_ERROR_NO_MEMORY -7
#define CHIRP_ERROR_INVALID_REQUEST -8
#define CHIRP_ERROR_TOO_MANY_OPEN -9
#define CHIRP_ERROR_BUSY -10
#define CHIRP_ERROR_TRY_AGAIN -11
#define CHIRP_ERROR_UNKNOWN -127

#endif

