/***************************Copyright-DO-NOT-REMOVE-THIS-LINE**
  *
  * Condor Software Copyright Notice
  * Copyright (C) 1990-2004, Condor Team, Computer Sciences Department,
  * University of Wisconsin-Madison, WI.
  *
  * This source code is covered by the Condor Public License, which can
  * be found in the accompanying LICENSE.TXT file, or online at
  * www.condorproject.org.
  *
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  * AND THE UNIVERSITY OF WISCONSIN-MADISON "AS IS" AND ANY EXPRESS OR
  * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  * WARRANTIES OF MERCHANTABILITY, OF SATISFACTORY QUALITY, AND FITNESS
  * FOR A PARTICULAR PURPOSE OR USE ARE DISCLAIMED. THE COPYRIGHT
  * HOLDERS AND CONTRIBUTORS AND THE UNIVERSITY OF WISCONSIN-MADISON
  * MAKE NO MAKE NO REPRESENTATION THAT THE SOFTWARE, MODIFICATIONS,
  * ENHANCEMENTS OR DERIVATIVE WORKS THEREOF, WILL NOT INFRINGE ANY
  * PATENT, COPYRIGHT, TRADEMARK, TRADE SECRET OR OTHER PROPRIETARY
  * RIGHT.
  *
  ****************************Copyright-DO-NOT-REMOVE-THIS-LINE**/
/*
Chirp C Client

This public domain software is provided "as is".  See the Chirp License
for details.
*/

#ifndef CHIRP_PROTOCOL_H
#define CHIRP_PROTOCOL_H

#define CHIRP_LINE_MAX 1024
#define CHIRP_VERSION 2

#define CHIRP_ERROR_NOT_AUTHENTICATED -1
#define CHIRP_ERROR_NOT_AUTHORIZED -2
#define CHIRP_ERROR_DOESNT_EXIST -3
#define CHIRP_ERROR_ALREADY_EXISTS -4
#define CHIRP_ERROR_TOO_BIG -5
#define CHIRP_ERROR_NO_SPACE -6
#define CHIRP_ERROR_NO_MEMORY -7
#define CHIRP_ERROR_INVALID_REQUEST -8
#define CHIRP_ERROR_TOO_MANY_OPEN -9
#define CHIRP_ERROR_BUSY -10
#define CHIRP_ERROR_TRY_AGAIN -11
#define CHIRP_ERROR_UNKNOWN -127

#endif

